### ISSUE TITLE
Segmentation fault after running ls in the NFS mounted folder

### ISSUE THREAD

**Issue by yhung124** [nfs-ganesha/nfs-ganesha#154] opened 2017-03-17 06:58 UTC
Hi, 
I compiled nfs-ganesha (V2.5-dev-17) by myself. After deploying ceph (12.0.0) cluster and setup a RGW. I create rgw account with access_key and secret_key and try to upload some photos to it. And started nfs-ganesha with the following config.
<pre>
EXPORT
{
        Export_ID=1;
        Path = "/";
        Pseudo = "/rgw";
        Access_Type = RW;
        Squash = No_root_squash;
        FSAL {
                Name = RGW;
                User_Id = "developer";
                Access_Key_Id ="test";
                Secret_Access_Key = "test";
        }
}

RGW {
    ceph_conf = "/etc/ceph/ceph.conf";
}
</pre>

Run the nfs-ganesha with
<pre>
# ganesha.nfsd -F -L ganesha.log
</pre>

In another host, I can mount the nfs with
<pre>
# mount -t nfs 192.168.1.1:/ /mnt/nfs
</pre>

However, when I try to ls the folder (I already uploaded some test images)
<pre>
# ls -la /mnt/nfs
</pre>

ganesha.nfsd crashed with the following message
<pre>
# ganesha.nfsd -F -L ganesha.log
*** Caught signal (Segmentation fault) **
 in thread 7fd4fb5c1700 thread_name:ganesha.nfsd
 ceph version 7a0ff7 (87a0ff794eccc57c323a184de8194684a98f92e5)
 1: (()+0x2d8ee1) [0x7fd548d22ee1]
 2: (()+0x10f10) [0x7fd55fc6df10]
 3: (()+0x124e0) [0x7fd55fc6f4e0]
 4: (rgw::RGWLibFS::lookup_fh(rgw::RGWFileHandle*, char const*, unsigned int)+0x39e) [0x7fd548ba770c]
 5: (rgw::RGWLibFS::stat_bucket(rgw::RGWFileHandle*, char const*, unsigned int)+0x21f) [0x7fd548b97fb3]
 6: (rgw_lookup()+0x4e) [0x7fd548b9886c]
 7: (()+0x5d65) [0x7fd548ffcd65]
 8: (()+0x5e17) [0x7fd548ffce17]
 9: (rgw::RGWListBucketsRequest::send_response_data(RGWUserBuckets&)+0x9e) [0x7fd548ba5cde]
 10: (RGWListBuckets::execute()+0x2fc) [0x7fd548bfa49e]
 11: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*, rgw::RGWLibIO*)+0x755) [0x7fd548b8fa35]
 12: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*)+0x4a) [0x7fd548b8fed0]
 13: (rgw::RGWFileHandle::readdir(bool (*)(char const*, void*, unsigned long), void*, unsigned long*, bool*, unsigned int)+0x218) [0x7fd548b96f3a]
 14: (()+0x5b4f) [0x7fd548ffcb4f]
 15: (mdcache_dirent_populate()+0x140) [0x4b4141]
 16: ganesha.nfsd() [0x4ae24d]
 17: (fsal_readdir()+0x1dc) [0x428dfb]
 18: (nfs4_op_readdir()+0x3c1) [0x44c466]
 19: (nfs4_Compound()+0x40d) [0x43e6e0]
 20: (nfs_rpc_execute()+0xf25) [0x434190]
 21: ganesha.nfsd() [0x434796]
 22: ganesha.nfsd() [0x4972ac]
 23: (()+0x7444) [0x7fd55fc64444]
 24: (clone()+0x6d) [0x7fd55f34e61d]
2017-03-17 02:22:42.160683 7fd4fb5c1700 -1 *** Caught signal (Segmentation fault) **
 in thread 7fd4fb5c1700 thread_name:ganesha.nfsd

 ceph version 7a0ff7 (87a0ff794eccc57c323a184de8194684a98f92e5)
 1: (()+0x2d8ee1) [0x7fd548d22ee1]
 2: (()+0x10f10) [0x7fd55fc6df10]
 3: (()+0x124e0) [0x7fd55fc6f4e0]
 4: (rgw::RGWLibFS::lookup_fh(rgw::RGWFileHandle*, char const*, unsigned int)+0x39e) [0x7fd548ba770c]
 5: (rgw::RGWLibFS::stat_bucket(rgw::RGWFileHandle*, char const*, unsigned int)+0x21f) [0x7fd548b97fb3]
 6: (rgw_lookup()+0x4e) [0x7fd548b9886c]
 7: (()+0x5d65) [0x7fd548ffcd65]
 8: (()+0x5e17) [0x7fd548ffce17]
 9: (rgw::RGWListBucketsRequest::send_response_data(RGWUserBuckets&)+0x9e) [0x7fd548ba5cde]
 10: (RGWListBuckets::execute()+0x2fc) [0x7fd548bfa49e]
 11: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*, rgw::RGWLibIO*)+0x755) [0x7fd548b8fa35]
 12: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*)+0x4a) [0x7fd548b8fed0]
 13: (rgw::RGWFileHandle::readdir(bool (*)(char const*, void*, unsigned long), void*, unsigned long*, bool*, unsigned int)+0x218) [0x7fd548b96f3a]
 14: (()+0x5b4f) [0x7fd548ffcb4f]
 15: (mdcache_dirent_populate()+0x140) [0x4b4141]
 16: ganesha.nfsd() [0x4ae24d]
 17: (fsal_readdir()+0x1dc) [0x428dfb]
 18: (nfs4_op_readdir()+0x3c1) [0x44c466]
 19: (nfs4_Compound()+0x40d) [0x43e6e0]
 20: (nfs_rpc_execute()+0xf25) [0x434190]
 21: ganesha.nfsd() [0x434796]
 22: ganesha.nfsd() [0x4972ac]
 23: (()+0x7444) [0x7fd55fc64444]
 24: (clone()+0x6d) [0x7fd55f34e61d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this.

     0> 2017-03-17 02:22:42.160683 7fd4fb5c1700 -1 *** Caught signal (Segmentation fault) **
 in thread 7fd4fb5c1700 thread_name:ganesha.nfsd

 ceph version 7a0ff7 (87a0ff794eccc57c323a184de8194684a98f92e5)
 1: (()+0x2d8ee1) [0x7fd548d22ee1]
 2: (()+0x10f10) [0x7fd55fc6df10]
 3: (()+0x124e0) [0x7fd55fc6f4e0]
 4: (rgw::RGWLibFS::lookup_fh(rgw::RGWFileHandle*, char const*, unsigned int)+0x39e) [0x7fd548ba770c]
 5: (rgw::RGWLibFS::stat_bucket(rgw::RGWFileHandle*, char const*, unsigned int)+0x21f) [0x7fd548b97fb3]
 6: (rgw_lookup()+0x4e) [0x7fd548b9886c]
 7: (()+0x5d65) [0x7fd548ffcd65]
 8: (()+0x5e17) [0x7fd548ffce17]
 9: (rgw::RGWListBucketsRequest::send_response_data(RGWUserBuckets&)+0x9e) [0x7fd548ba5cde]
 10: (RGWListBuckets::execute()+0x2fc) [0x7fd548bfa49e]
 11: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*, rgw::RGWLibIO*)+0x755) [0x7fd548b8fa35]
 12: (rgw::RGWLibProcess::process_request(rgw::RGWLibRequest*)+0x4a) [0x7fd548b8fed0]
 13: (rgw::RGWFileHandle::readdir(bool (*)(char const*, void*, unsigned long), void*, unsigned long*, bool*, unsigned int)+0x218) [0x7fd548b96f3a]
 14: (()+0x5b4f) [0x7fd548ffcb4f]
 15: (mdcache_dirent_populate()+0x140) [0x4b4141]
 16: ganesha.nfsd() [0x4ae24d]
 17: (fsal_readdir()+0x1dc) [0x428dfb]
 18: (nfs4_op_readdir()+0x3c1) [0x44c466]
 19: (nfs4_Compound()+0x40d) [0x43e6e0]
 20: (nfs_rpc_execute()+0xf25) [0x434190]
 21: ganesha.nfsd() [0x434796]
 22: ganesha.nfsd() [0x4972ac]
 23: (()+0x7444) [0x7fd55fc64444]
 24: (clone()+0x6d) [0x7fd55f34e61d]
 NOTE: a copy of the executable, or `objdump -rdS <executable>` is needed to interpret this

           

# cat ganesha.log
17/03/2017 02:20:18 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.5-dev-17
17/03/2017 02:20:18 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_set_param_from_conf :NFS STARTUP :EVENT :Configuration file successfully parsed
17/03/2017 02:20:18 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] init_server_pkgs :NFS STARTUP :EVENT :Initializing ID Mapper.
17/03/2017 02:20:18 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] init_server_pkgs :NFS STARTUP :EVENT :ID Mapper successfully initialized.
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] lower_my_caps :NFS STARTUP :EVENT :CAP_SYS_RESOURCE was successfully removed for proper quota management in FSAL
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] lower_my_caps :NFS STARTUP :EVENT :currenty set capabilities are: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Init_admin_thread :NFS CB :EVENT :Admin thread initialized
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs4_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 90
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_rpc_cb_init_ccache :NFS STARTUP :EVENT :Callback creds directory (/var/run/ganesha) already exists
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_rpc_cb_init_ccache :NFS STARTUP :WARN :gssd_refresh_krb5_machine_credential failed (-1765328160:2)
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Start_threads :THREAD :EVENT :Starting delayed executor.
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Start_threads :THREAD :EVENT :9P/TCP dispatcher thread was started successfully
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[_9p_disp] _9p_dispatcher_thread :9P DISP :EVENT :9P dispatcher started
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Start_threads :THREAD :EVENT :admin thread was started successfully
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Start_threads :THREAD :EVENT :reaper thread was started successfully
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now IN GRACE
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_Start_threads :THREAD :EVENT :General fridge was started successfully
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nsm_connect :NLM :CRIT :failed to connect to statd
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nsm_unmonitor_all :NLM :CRIT :Can not unmonitor all clnt_create returned NULL
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_start :NFS STARTUP :EVENT :             NFS SERVER INITIALIZED
17/03/2017 02:20:19 : epoch 58cb47e2 : 336 : nfs-ganesha-379[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
17/03/2017 02:21:49 : epoch 58cb47e2 : 336 : nfs-ganesha-379[reaper] nfs_in_grace :STATE :EVENT :NFS Server Now NOT IN GRACE
</pre>

Any idea?

**Comment by dang** [comment] 2017-03-17 12:54
Is this reproducible?  If so, could you install the debug packages for ceph, so the backtrace includes symbols?

**Comment by ffilz** [comment] 2020-06-15 18:48
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed** 2020-07-15 21:48 UTC
