### ISSUE TITLE
Can Ganesha add only the posix file systems that are inside the root dir exported?

### ISSUE THREAD

**Issue by darwinTtito** [nfs-ganesha/nfs-ganesha#536] opened 2020-01-31 18:56 UTC
Hi, 

Each time that I try to export a volume through Ganesha, it checks all the posix file systems found on the Ganesha server in order to see if the volume exists or not. So, is there any way that Ganesha only checks the file systems within the root directory exported (ExportID = 0)?

I saw that the `populate_posix_file_systems` method does the process before mentioned.

See the following example:

1. `/exports` was the first volume exported (exportID = 0)
2. `/exports/b` , `/content/a` and `/content/b` are created and mounted through unionfs
3. `/exports/b` is exported through Ganesha
4. The log below is written when the volume `/exports/b` is exported. There we can see that Ganesha adds the file systems `/content/a` and `/content/b`, even when they are out of the root directory exported.

Best Regards

```
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :F_DBG :statfs of /content/bpathlen 0
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :DEBUG :blkid_devno_to_devname of /content/b failed for dev 0.594
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_create_file_system :FSAL :INFO :Added filesystem /content/b namelen=255 dev=0.594 fsid=0x0000000000000000.0x0000000000000252 0.594
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :F_DBG :statfs of /content/a pathlen 0
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :DEBUG :blkid_devno_to_devname of /content/a failed for dev 0.595
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_create_file_system :FSAL :INFO :Added filesystem /content/a namelen=255 dev=0.595 fsid=0x0000000000000000.0x0000000000000253 0.595
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :F_DBG :statfs of /exports/b pathlen 0
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_get_fsid :FSAL :DEBUG :blkid_devno_to_devname of /exports/b failed for dev 0.596
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_create_file_system :FSAL :INFO :Added filesystem /exports/b namelen=255 dev=0.596 fsid=0x0000000000000000.0x0000000000000254 0.596
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_find_parent :FSAL :INFO :File system /content/b is a child of /
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_find_parent :FSAL :INFO :File system /content/a is a child of /
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] posix_find_parent :FSAL :INFO :File system /exports/b is a child of /exports
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :/
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /proc
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /dev
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /dev/pts
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /dev/mqueue
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /dev/shm
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /sys
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /sys/fs/cgroup
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/systemd
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/perf_event
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/devices
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/hugetlb
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/rdma
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/net_cls,net_prio
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/freezer
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/cpu,cpuacct
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/blkio
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/pids
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/memory
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :      /sys/fs/cgroup/cpuset
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /exports
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /exports/b
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /etc/certs
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /etc/certs/hana
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /etc/certs/root-ca
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :    /etc/certs/vrep
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /run/secrets/kubernetes.io/serviceaccount
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /content/a
30/01/2020 12:35:12 : epoch 5e32ca5d : server : nfs-ganesha-21[dbus_heartbeat] show_tree :FSAL :INFO :  /content/b
```

**Comment by ffilz** [comment] 2020-01-31 21:42
Ganesha isn't exporting all those directories, that is just a map of the filesystems Ganesha has detected on scanning mntab, and thus are the filesystems that would be eligible for export.

**Comment by ffilz** [comment] 2020-01-31 21:45
Note that Ganesha creates this list so it can support exporting a filesystem and any filesystems mounted below it. So for example, by exporting /exports, /exports/b is automatically exported if it's available when /exports is mounted (we do not handle sub exporting filesystems sub mounted after the export is created, that would take some extra work), however, sub-mounted filesystems can be exported on a subsequent export because we re-scan mntab on dynamically created exports.

**Comment by k-angelo** [comment] 2020-02-02 16:36
Hello @ffilz and thank you for the response. I think in this issue we didn't state the problem clearly. 

In the example from @darwinTtito where we have the non-exported local mounts and exported mounts, when we issue an `addExports` command, the command may fail with the message that ganesha failed to stat one of the local volumes. Please note that the local volumes are ephemeral and short-lived.

```
30/01/2020 14:12:43 : epoch 5e32ca5d : nfs-ganesha-21[dbus_heartbeat] vfs_get_root_handle :FSAL :MAJ :Could not open VFS mount point /contents/volumes/content/system/admin/system/1: rc = No such file or directory (2)
30/01/2020 14:12:43 : epoch 5e32ca5d : nfs-ganesha-21[dbus_heartbeat] process_claim :FSAL :CRIT :FSAL VFS failed to claim file system /contents/volumes/content/system/admin/system/1 error No such file or directory
```

These volumes are not under `/exports` where our root export is but still the command fails, hence the original question.
Somehow our issue seems to be related with this https://github.com/kubernetes-incubator/external-storage/issues/432 .

**Comment by ffilz** [comment] 2020-02-03 15:35
Ah, ok, if you do a mount command from the command line, what type are these filesystems? We do exclude a few filesystem types (we should exclude more...). If it's a unique filesystem type, we could try skipping them (if you see a unique filesystem type you could add a strcasecmp(mnt->mnt_type, "type") (where you replace "type" with the appropriate string) on about line 1296 in src/FSAL/commonlib.c and see if that's sufficient to remove your error. If the filesystem type is something we would normally want to allow to be exported then that idea won't work.

Are you exporting "/" or "/contents" (or anything deeper in "/contents"? If so then FSAL_VFS may be trying to pick up your ephemeral filesystem from that export. If you export is "/exports" I'm not sure why FSAL_VFS is trying to export them as sub-exports.

You may need to give more details on your export config and the filesystems that mount shows. I have a patch I'm going to add that will add the filesystem type to the log messages regarding the filesystem scan:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/483739

**Comment by k-angelo** [comment] 2020-02-04 15:58
Our mounts are unionfs-fuse type and we want to export them in certain cases but in other cases we don't export them (like in the case of the `contents` example).
The `contents` are on a separate path e.g. `/contents` while the exportable mounts are all under `/exports`.

I do not think that the problem is with Ganesha trying to export these directories. After reading around other issues I think the problem lies in race condition with the `/etc/mtab` file.  Fuse mounts try to write to the mtab file which later gets cached by ganesha. Ganesha then on the next`addExport` will try to stat these directories that may not be there. Do you think that this is a possible scenario ?

**Comment by ffilz** [comment] 2020-02-04 18:08
I'm still not clear why FSAL_VFS is trying to claim a filesystem under /contents if all your exports are under /exports.

Could you turn on debug for FSAL and EXPORTS in the config:

LOG {
   COMPONENTS {
      FSAL=FULL_DEBUG;
      EXPORTS=FULL_DEBUG;
   }
}
And then try your add export? If you are doing this after starting Ganesha using dBUS to add the export, either start Ganesha this way, or issue the Ganesha process a SIGHUP to get it to re-read the log config (that will also re-read the export config - which depending on how you're doing your add export might trigger the add-export).

**Comment by darwinTtito** [comment] 2020-02-05 20:32
Hi @ffilz, I was able to reproduce the problem. Below more details to reproduce it, the Ganesha log file and my analysis:

### Enviroment
```
Ganesha Version 3.0.

NAME="openSUSE Leap"
VERSION="15.0"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.0"
PRETTY_NAME="openSUSE Leap 15.0"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.0"
```

### Steps to reproduce the problem
1. Start the NFS Ganesha with the config file below (_/etc/ganesha/vfs.conf_ )
2. In the Ganesha config file, add the Include statement to point the file  _/etc/ganesha/export-dir1.conf_ (`%include "/etc/ganesha/export-dir1.conf"`). Do not export the volume yet.
3. Execute the command lines specified below (in the order that appears) to get the Ganesha error.

### Ganesha log
https://paste.ubuntu.com/p/HXh495RhWn/

### Analysis

- Note that the `/content` and `/export/dir1` volumes are mounted through the fuse.unionfs command in that order respectively, so, that is the order in which they will appear in `/etc/mtab` and how Ganesha will consider them **(command lines 6,7)**.
- Then, when the `AddExport` method is triggered (to export the `/export/dir1` dir), Ganesha assigns an FSID for each existing volume, let's say that these FSIDs will be `00100` and `00101` for the` /content` and `/export/dir` mounts respectively (populate_posix_file_systems() method), so now Ganesha knows the volumes through their FSIDs **(command line 9)**.
- After removing the export of the `/export/dir1` volume and unmount the two volumes mentioned above, Ganesha will still cache the relationship of the volumes with their FSIDs **(command lines 10,12,13)**.
- Next, when we try to export the `/export/dir1` volume again, Ganesha will assign it an FSID, since the previous 2 FSID were released, the first one (`00100`) will be assigned to the volume (Note that at this point the `/content` volume no longer exists). Here start the problem, it seems that Ganesha does not update its cache and since the `FSID=00100` in the cache still points to the `/content` volume, Ganesha claims that volume instead of the actual one that we are trying to mount **(command lines 14, 15, 17)**.

So, what do you think about it? is it a bug or it is the expected behavior? 
I am looking forward to your response, and thanks for your time dedicated to this thread, I really appreciate it.

_/etc/ganesha/vfs.conf_
```
LOG
{
  COMPONENTS
  {
    CACHE_INODE = FULL_DEBUG;
    NFS_V4_ACL = FULL_DEBUG;
    NFS_V4 = FULL_DEBUG;
    NFSPROTO = FULL_DEBUG;
    FSAL = FULL_DEBUG;
    NFS4 = FULL_DEBUG;
    EXPORT = FULL_DEBUG;
    IDMAPPER = FULL_DEBUG;
  }
}

NFSv4 {
  Only_Numeric_Owners = true;
}
EXPORT_DEFAULTS
{
  Transports = TCP;
  PrivilegedPort = false;
  Access_type = RW;
  SecType = sys;
  Squash = All_Squash;
  Anonymous_Uid = 999;
  Anonymous_Gid = 999;
}
EXPORT{
  Export_Id = 0;
  Filesystem_id = 0.0;
  Protocols = 4;
  Path = /export;
  Pseudo = /;
  FSAL {
    Name = VFS;
  }
}
```

_/etc/ganesha/export-dir1.conf_
```
EXPORT{
  Export_Id = 1;
  Filesystem_id = 1.1;
  Path = /export/dir1;
  Pseudo = /dir1;
  Protocols =  4;
  Transports = TCP;
  Squash = all;
  Anonymous_Uid = 999;
  Anonymous_Gid = 999;
  Access_type = RW;
  Sectype = sys;
  FSAL {
    Name = VFS;
  }
}
```

_command lines_
```
1    $ mkdir -p /data
2    $ mkdir -p /data/1
3    $ mkdir -p /content
4    $ mkdir -p /export/dir1
5    $ 
6    $ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data=RW /content
7    $ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data/1=RW /export/dir1
8    $ 
9    $ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir1)"
10   $ dbus-send --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.RemoveExport uint16:1
11   $ 
12   $ umount /export/dir1
13   $ umount /content
14   $ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data/1=RW /export/dir1
15   $ rm -r /content
16   $ 
17   $ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir1)"
```

**Comment by darwinTtito** [comment] 2020-02-10 14:22
Hi @ffilz, 

Do you have any update for the problem I described above?

Regards

**Comment by ffilz** [comment] 2020-02-10 18:09
Sorry, I missed that, I will take a look at your analysis and think about possible solutions.

**Comment by ffilz** [comment] 2020-02-11 20:15
Ok, yea, so the problem is re-used device ids.

One thing we could do is when we are going to reload the POSIX file systems we scan the ones that are loaded and delete any that no longer are mounted. This could be done in an else block in populate_posix_file_systems right after the else if (!force) { } block.

Hmm, my simple idea doesn't work if you unmount a filesystem but the mount point is still there...

**Comment by ffilz** [comment] 2020-02-11 20:39
Ok, I think I've got something that works, can you try out

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/484594

Also, take a look at

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/484595/1

With the 2nd patch, I added some additional file system types to ignore.

**Comment by ffilz** [comment] 2020-02-14 18:53
I've updated the patches

**Comment by ffilz** [comment] 2020-07-15 15:06
Please take a look at the current next, I have finally merged my export patches and hopefully they address this issue. If they are resolved, please close the issue.

**Comment by ffilz** [comment] 2020-08-13 23:01
With some code changes that should mitigate this, and no action for nearly 30 days, I will close this as resolved.

**Closed as completed by ffilz** 2020-08-13 23:01 UTC
