### ISSUE TITLE
readdir takes too much time

### ISSUE THREAD

**Issue by lee-fan** [nfs-ganesha/nfs-ganesha#223] opened 2017-10-24 06:40 UTC
when i ls a large directory,it takes too much time.
i found that nfs client send readdir request (cookie=0) repeatly from nfs client debug info.
And once i clear the local system cache, this issues can be reproduced.
anyone knows what happened?

**Comment by ffilz** [comment] 2017-10-24 14:17
If you are using next, try the latest, I just fixed a problem where the dirent cache was invalidated on every READDIR request. That patch will be backported to V2.5-stable

**Comment by ffilz** [comment] 2017-10-24 14:17
Specifically this patch: https://review.gerrithub.io/383196

**Comment by dang** [comment] 2017-10-24 15:10
What version of Ganesha?

**Comment by sagarfan** [comment] 2017-10-26 02:28
using NFS-Ganesha Release = V2.5.0.4

**Comment by sagarfan** [comment] 2017-10-26 02:38
configure file ：
CacheInode {
        Dir_Chunk = 0;
}
actually cache is not used.
And after i update linux kernel,this issue does not show up again
very confused.

**Comment by dang** [comment] 2017-10-26 12:46
The dirent cache is used.  There are 2 types of dirent caches in 2.5.x: The full cache, and the chunked cache.  You've disabled the chunked cache, which was designed to fix the exact problem you're seeing.

The original dirent cache in ganesha populated the entire dirent cache before returning anything to the client.  This works well, and is fast, for relatively small directories, but introduces a long delay in the response for large directories or for FSALs that respond to readdir slowly.

The full fix for this is the chunked dirent cache.  It reads the dirents from the FSAL in chunks (specified by Dir_Chunk), and returns to the client in between chunks.  This is the default in 2.6, and the old dirent cache will be removed.

A partial workaround was merged into 2.4 (and is still present in 2.5) that disables the dirent cache entirely for large directories.  This fixes the slow initial readdir, but at the cost of slower readdirs every time.  This is controlled by the Dir_Max option.

Your best bet is to allow dirent chunking (by not setting Dir_Chunk to 0).

**Comment by ffilz** [comment] 2020-06-15 20:51
Closing this, there are numerous readdir fixes since V2.5.0.4.

**Closed by ffilz** 2020-06-15 20:51 UTC
