### ISSUE TITLE
How do I get the space of RGW mountpoint ?

### ISSUE THREAD

**Issue by mkkie** [nfs-ganesha/nfs-ganesha#146] opened 2017-02-23 02:13 UTC
Hi, guys. I'm using ubuntu:14.04, Ceph 10.2.5 and nfs-ganesha V2.4-stable. 
I build it with "cmake -DUSE_FSAL_RGW=ON -DUSE_FSAL_CEPH=ON /nfs-ganesha/src/".
After compilation, I run the nfs-ganesha and it works!
The problem is that when I use df command, I can get the space of Cephfs but not RGW.
Is it a expected behavior ?

Thanks!!

df informations
```
$ df -h .
Filesystem             Size  Used Avail Use% Mounted on
192.168.33.90:/cephfs   91T  1.8G   91T   1% /tmp/nfs
$ mount 
192.168.33.90:/cephfs on /tmp/nfs type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.33.90,local_lock=none,addr=192.168.33.90)

$ df -h .
Filesystem          Size  Used Avail Use% Mounted on
192.168.33.90:/rgw     0     0     0    - /tmp/nfs
$ mount
192.168.33.90:/rgw on /tmp/nfs type nfs4 (rw,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.33.90,local_lock=none,addr=192.168.33.90)
```

Here are my commands.
```
# service rpcbind start
# ganesha.nfsd -F -L ganesha.log
```

The following is my ganesha.conf
```
EXPORT
{
        Export_ID=1;
        Path = "/";
        Pseudo = "/cephfs";
        Access_Type = RW;
        Squash = No_root_squash;
        NFS_Protocols = 3,4;
        Transport_Protocols = TCP;
        FSAL {
                Name = CEPH;
        }     
}
EXPORT
{
        Export_ID=2;
        Path = "/";
        Pseudo = "/rgw";
        Access_Type = RW;
        Squash = No_root_squash;
        NFS_Protocols = 4;
        Transport_Protocols = TCP;
        FSAL {
                Name = RGW;
                User_Id = "admin";
                Access_Key_Id ="admin";
                Secret_Access_Key = "admin";
        }
}

RGW {
    ceph_conf = "/etc/ceph/ceph.conf";
}
```

**Comment by ffilz** [comment] 2017-02-23 04:22
The problem is that QUOTA does lookup of export by Path. The Path is the same for both exports, so it will find whichever export was first in the config.

There is a patch in the 2.5 stream (next branch) which adds a config variable that when set makes NFS v3, 9P, and RQUOTA use Pseudo instead of Path which is exactly what you need here so if you can try the next branch (V2.5-dev-15 is currently the latest tag) that should solve your issue.

**Comment by yhung124** [comment] 2017-03-17 07:16
Hi @ffilz ,
Could you kindly describe how to set properly arguments in ganesha.conf to get right mount quota?
I run nfs-ganesha (V2.5-dev-17) with following ganesha.conf but things still doesn't work.
<pre>
EXPORT
{
        Export_ID=1;
        Path = "/";
        Pseudo = "/rgw";
        Access_Type = RW;
        Squash = No_root_squash;
#        NFS_Protocols = 4;
#        Transport_Protocols = TCP;
        FSAL {
                Name = RGW;
                User_Id = "developer";
                Access_Key_Id ="test";
                Secret_Access_Key = "test";
        }
}
RGW {
    ceph_conf = "/etc/ceph/ceph.conf";
</pre>
When I run the main program with
<pre>
# ganesha.nfsd -L ganesha.log -F
</pre>
Some error message occurs in the log file
<pre>
16/03/2017 10:50:19 : epoch 58ca6dea : 336 : nfs-ganesha-694[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:8): Unknown parameter (NFS_Protocols)
16/03/2017 10:50:19 : epoch 58ca6dea : 336 : nfs-ganesha-694[main] config_errs_to_log :CONFIG :WARN :Config File (/etc/ganesha/ganesha.conf:9): Unknown parameter (Transport_Protocols)
</pre>

<pre>
# df -h .
Filesystem          Size  Used Avail Use% Mounted on
192.168.1.1:/rgw     0     0     0    - /tmp/nfs
</pre>

Actually, I post another issue here, should I try to resolve the problem at first?
#154

**Comment by dang** [comment] 2017-03-17 13:06
In the Export scope, it's "Protocols" and "Transports".  The versions you used are in the NFS_Core_Param scope.  I know, confusing, but that's the way it is.

The parameter to use Pseudo for mounting is "Mount_Path_Pseudo =  true" in the NFS_Core_Param scope.

**Comment by kiwiflyer** [comment] 2017-08-14 17:01
@mkkie Did you ever solve your issue where you couldn't see the user/available space using DF on you RGW export?
We're seeing exactly the same thing, but we only have a single export. 
We're currently testing Ganesha 2.5.0.1 against Ceph luminous RC3 with bluestor.

**Comment by ffilz** [comment] 2020-06-15 22:37
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed by ffilz** 2020-06-15 22:37 UTC
