### ISSUE TITLE
EPROTONOSUPPORT for kernel 6.5.7 when mounting NFSv4.1

### ISSUE THREAD

**Issue by pittburgher** [nfs-ganesha/nfs-ganesha#1025] opened 2023-11-02 20:56 UTC
Hello,

Does Ganesha have some upper limit, as to kernel support, when attempting to mount NFS v4.1?

```
# uname -a
Linux myclient 6.5.7-060507-generic #202310102154 SMP PREEMPT_DYNAMIC Tue Oct 10 22:00:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
# /sbin/mount.nfs4 -vv -o vers=4.1 10.114.82.198:/fs1/ /mnt/nfs
mount.nfs4: timeout set for Thu Nov  2 20:56:52 2023
mount.nfs4: trying text-based options 'vers=4.1,addr=10.114.82.198,clientaddr=10.114.39.251'
mount.nfs4: mount(2): Protocol not supported
mount.nfs4: Protocol not supported
```

```
# /sbin/mount.nfs4 -vv -o vers=4.0 10.114.82.198:/fs1/ /mnt/nfs
mount.nfs4: timeout set for Thu Nov  2 20:57:02 2023
mount.nfs4: trying text-based options 'vers=4.0,addr=10.114.82.198,clientaddr=10.114.39.251
```

Oddly, 4.1 mounts fine under kernel 6.5.0, but not 6.5.7.

**Comment by ffilz** [comment] 2023-11-02 23:00
NFS v4.1 should be NFSv4.1. I'm not sure what the issue would be. You could check for kernel bugs. If you can, take a tcpdump and see if there's some NFSv4.1 request that is failing.

**Comment by jepio** [comment] 2023-11-03 14:22
Cross-referencing because I just investigated this bug here: https://github.com/flatcar/Flatcar/issues/1226#issuecomment-1792493798.

We hit it in stable 5.15.136 and found it fixed in stable 5.15.137. The fix is this https://github.com/torvalds/linux/commit/379e4adfddd6a2f95a4f2029b8ddcbacf92b21f9, which is in v6.5.9 as https://github.com/gregkh/linux/commit/dba32abd641ded1fbbe8aaafb0d6be7ea3fc3ea9.

**Comment by pittburgher** [comment] 2023-11-03 14:44
Thank you so much jepio.

**Comment by ffilz** [comment] 2023-11-03 15:50
If it's confirmed as a client bug, can we then close this issue?

Thanks

Frank

**Comment by pittburgher** [comment] 2023-11-03 15:56
> If it's confirmed as a client bug, can we then close this issue?

Yes please.

**Closed as completed** 2023-11-03 16:53 UTC
Labels: External bug, Can we close?
