### ISSUE TITLE
Crash in RPCAL/nfs_dupreq.c since 9316124

### ISSUE THREAD

**Issue by bjorn-fischer** [nfs-ganesha/nfs-ganesha#810] opened 2022-04-04 10:31 UTC
The new code for handling duplicate calls (Dec 8th, 9316124) triggers some nasty crashes on our Ganesha setup. The daemon often terminates and gets restarted on ```PTHREAD_MUTEX_lock(&dv->mtx)``` returning **EINVAL**:
```
RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex
```

When turning on **FULL_DEBUG** for **DUPREQ**, the log looks like this:
```
04/04/2022 11:46:07 [svc_509] @RPCAL/nfs_dupreq.c:886 :nfs_dupreq_free_dupreq :freeing dupreq entry dv=0x7f05d0842d00, dv xid=4072134093 cksum 3404955372536105482 DUPREQ_COMPLETE
04/04/2022 11:46:07 [svc_498] @RPCAL/nfs_dupreq.c:886 :nfs_dupreq_free_dupreq :freeing dupreq entry dv=0x7f00ef7d6680, dv xid=1757009357 cksum 5520652796123117128 DUPREQ_COMPLETE
04/04/2022 11:46:07 [svc_498] @RPCAL/nfs_dupreq.c:1421 :nfs_dupreq_rele :releasing dv=0x7f01041f3b00 xid=2377831885 on DRC=0x7f0444003000 state=DUPREQ_COMPLETE, refcnt=2
04/04/2022 11:46:07 [svc_509] @RPCAL/nfs_dupreq.c:739 :nfs_dupreq_put_drc :drc 0x7f0444003000 refcnt==3
04/04/2022 11:46:07 [svc_509] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f05d0842d40 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
04/04/2022 11:46:07 [svc_460] @RPCAL/nfs_dupreq.c:590 :nfs_dupreq_get_drc :ref DRC=0x7f0444003000 for xprt=0x7f01eab0c300
04/04/2022 11:46:07 [svc_498] @RPCAL/nfs_dupreq.c:739 :nfs_dupreq_put_drc :drc 0x7f0444003000 refcnt==2
04/04/2022 11:46:07 [svc_460] @RPCAL/nfs_dupreq.c:233 :dupreq_tcp_cmpf :dupreq_tcp_cmpf
04/04/2022 11:46:07 [svc_460] @RPCAL/nfs_dupreq.c:233 :dupreq_tcp_cmpf :dupreq_tcp_cmpf
04/04/2022 11:46:07 [svc_460] @RPCAL/nfs_dupreq.c:233 :dupreq_tcp_cmpf :dupreq_tcp_cmpf
```

This issue did not occur prior to 9316124.

Cheers,
Björn

**Comment by ffilz** [comment] 2022-04-04 22:15
Can you share more details of the crash? Are you using the latest build?

**Comment by bjorn-fischer** [comment] 2022-04-05 11:10
```
root[bf]@cephnfs:/var/log# /opt/ganesha/bin/ganesha.nfsd -version
NFS-Ganesha Release = V4.0.3
ganesha.nfsd compiled on Apr  1 2022 at 13:00:41
Release comment = GANESHA file server is 64 bits compliant and supports NFS v3,4.0,4.1 (pNFS) and 9P
Git HEAD = c40241d1ee5baaf1fcaf6d7c3fd7d9433c01aae6
Git Describe = V4.0.3-0-gc40241d1e
```

For now I have no idea how to trigger the problem. I'm running Ganesha with **FULL_DEBUG** for **THREAD** now and hopefully I'll have some more useful information soon. Yet, ```Error 22``` on ```pthread_mutex_lock()``` is really weird since **PTHREAD_PRIO_PROTECT** does not seem to be used in Ganesha.

**Comment by ffilz** [comment] 2022-04-06 14:18
A few more details in issue 813. I think with that I may have enough clues to solve the issue.

The problem is a PTHREAD_MUTEX_lock after the DRC has been freed by dupreq_entry_put. I'm guessing this is a dupe request while another request is in progress (what https://github.com/nfs-ganesha/nfs-ganesha/commit/9316124dd47ee69d630e3529246ee62cdb75d77e was trying to resolve). I need to look at the locking discipline and make sure we don't lock or unlock a possibly freed DRC.

**Comment by bjorn-fischer** [comment] 2022-04-06 14:20
Ok, with **FULL_DEBUG** for **DUPREQ** and **THREAD** I got a rather large log file, but still no idea what's going wrong:

https://docs.cebitec.uni-bielefeld.de/s/KD9JXRtJ3qWiaNg

Within about 12h I got 15 crashes:

```
root[bf]@cephnfs:/var/log# tail -f ganesha.log | grep -i 'error.*22'
05/04/2022 20:36:49 [svc_1307] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f947d455300 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 22:32:43 [svc_672] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7ff2e4a27040 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 22:43:54 [svc_85] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7fc4369217c0 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 22:52:11 [svc_41] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f420b8dcb40 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 22:52:11 [svc_45] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f45a73f9f80 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 23:01:05 [svc_51] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f1c1c0fd080 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
05/04/2022 23:01:05 [svc_50] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f1f54ec2bc0 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 04:50:39 [svc_1544] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7fb49c3043c0 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 06:36:56 [svc_469] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7fccf7700d80 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 07:25:39 [svc_228] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f560dd61c80 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 07:47:13 [svc_197] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f20bb4b7000 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 07:47:13 [svc_223] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f2513b082c0 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 07:53:01 [svc_24] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f0c1ad45980 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 08:05:27 [svc_104] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7fe3088d5080 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
06/04/2022 08:09:09 [svc_20] @RPCAL/nfs_dupreq.c:1434 :nfs_dupreq_rele :Error 22, acquiring mutex 0x7f3ddc0fdf40 (&dv->mtx) at @RPCAL/nfs_dupreq.c:1434
```

**Comment by ffilz** [comment] 2022-04-06 22:42
Try this patch https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/535979

**Comment by bjorn-fischer** [comment] 2022-04-07 08:13
Great, that was fast. Our ganesha is patched and running again. The next 12h will tell whether it fixes the problem.

Thanks.

**Comment by bjorn-fischer** [comment] 2022-04-08 07:04
Yep, the patch seems to solve the problem. No issues so far.

**Comment by ffilz** [comment] 2022-04-08 15:07
Oops, there was an unmerged patch: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/534561 I will take that instead...

Sorry I didn't merge that earlier...

**Comment by happycouak** [comment] 2022-06-20 20:19
Any chances this patch lands in 4.0 release ?

**Comment by ffilz** [comment] 2022-06-21 19:15
This patch is in V4.0.4. In the next few weeks we will tag V4.1 and push packages out, in the meantime, we encourage anyone trying to use Ganesha V4 to use the latest (currently V4.0.6).

**Comment by ffilz** [comment] 2023-01-24 15:33
V4.3 has been tagged with a fix for this issue. Closing.

**Closed as completed by ffilz** 2023-01-24 15:33 UTC
Labels: Bug, Needs-Verification
