### ISSUE TITLE
Questions for ganesha v4

### ISSUE THREAD

**Issue by Bingo0203** [nfs-ganesha/nfs-ganesha#1051] opened 2024-01-11 09:41 UTC
Hello sir, in response to ganesha v4, I have a couple of questions I would like to ask:
1, The structure 'state_hdl' which records the state of the file, the initialization and assignment process of this piece of content is operated in the mdcache layer, is it all obtained from the entry?
2, I am mounting the file system (nfs v4), the client's export directory does not have information about the files in the server's directory, this is probably where the problem is? Is it related to state_hdl being empty?
3, About the getattr operation, is the whole process in the mdcache layer and not called to the bottom layer (fsal_ceph)?
4, Is fsal_pseudo only initialized inside the purtootfh function? ganesha v4 needs to set a root filesystem, is this it?

Thanks！

**Comment by ffilz** [comment] 2024-01-11 19:48
> Hello sir, in response to ganesha v4, I have a couple of questions I would like to ask: 
> 1, The structure 'state_hdl' which records the state of the file, the initialization and assignment process of this piece of content is operated in the mdcache layer, is it all obtained from the entry?
Yes, mostly it is glist_init, but also for files, a pointer to the fsal_obj_handle

> 2, I am mounting the file system (nfs v4), the client's export directory does not have information about the files in the server's directory, this is probably where the problem is? Is it related to state_hdl being empty?

I'm not sure what the issue is here, can you share your mount command and the ls output?

> 3, About the getattr operation, is the whole process in the mdcache layer and not called to the bottom layer (fsal_ceph)?

If the attributes aren't cached, mdcache will call the underlying FSAL's getattrs

> 4, Is fsal_pseudo only initialized inside the purtootfh function? ganesha v4 needs to set a root filesystem, is this it?

The pseduofs is created during initial export config load, and updated during dynamic export update if necessary. If you have an export with Pseduo = "/"; then FSAL_PSEUDO will not be used.

**Comment by Bingo0203** [comment] 2024-01-12 02:22
1,  The initialization process of state_hdl is largely dependent on which variable inside the entry structure? Or does it not depend on entry, which feels like the latter to me!
2， It's just a simple mount command. 'mount -t -o nfs vers=4 device(server) dir(client)'
But I did some manipulation and the lookup function internally skipped the 'state_hdl.dir.junction_export' part of the judgment logic, not quite sure what this part mainly did that caused my mounted directory to not show the contents of the server-side shared directory.
3, If the getattr function is called during the mount process, what about the underlying layer that getattr is called to? If so, can it be called directly to the bottom layer without going through the mdcache layer?
4，It means that pseudo is only used in the mounting process, and some operations after mounting are generally not used!

**Comment by ffilz** [comment] 2024-01-12 16:27
1. Really the only initialization of state_hdl that is interesting is for files, it includes a pointer to the fsal_obj_handle. It only needs this because originally there was a thought we could run without mdcache, but the truth is, we always need mdcache for handle lookup.
2. Please provide more detail on this? I'm really not understanding what your setup is and what you are doing, what you expect to see, and what you are actually seeing. Please, include network traces and maybe enable EXPORT debugging (add to your config: LOG { COMPONENTS { EXPORT=FULL_DEBUH; } } ). 
3. All calls always go through mdcache, if you configure Attr_Expiration_Time = 0; getattr will always call down to the underlying FSAL
4. It depends, for example, if you mount server:/ /mnt, then the pseudofs will be navigated by the client for operations other than mount. The pseudofs is just directories like any other filesystem, it is just created in memory from the export config and has directories that are junctions to each export.

**Comment by Bingo0203** [comment] 2024-01-13 02:42
1, My current understanding is that this is true, so where is the initialization or assignment process for state_hdl->dir? Or do you normally get it from the entry？
2， I may not be very clear, but let's keep it simple. what does 'state_hdl->dir.junction_export' do in the lookup function? And inside the function if(file_obj->state_hdl->dir.function_export ! =NULL) internal logic mainly?
3,  There is delegate logic inside the getatrr function, is this piece mainly for file manipulation? Is this called only when multiple clients operate on the same file in the same mounted directory?
4. The pseudofs will be navigated by the client for operations other than mount, an example of how this works is？

**Comment by ffilz** [comment] 2024-01-16 19:35
1. state_hdl->dir is zeroed, so junction_export and jct_pseudopath are both NULL, exp_root_refcount is set to 0, then export_roots is initialized with glist_init. state_hdl->jct_lock is also initialized.
2. So if junction_export is not NULL, then this directory is a junction where another export has been pseudo mounted. The logic in lookup then follows that junction into the new export.
3. The delegation logic in getattr is used to trigger recalling the delegation if another client requests attributes.
4. If the client mounts somewhere inside the pseudofs (pseudo root or somewhere else), FSAL_PSEUDO provides the directory navigation, listing, and attributes within the pseudofs. If a lookup reaches a pseudofs node that is a junction to another export, then the junction crossing logic is followed.  Outside of automatically managing a directory tree in the pseudofs to access the other exports, Ganesha doesn't treat the pseudofs any differently than any other export. FSAL_PSEUDO implements everything to manage an in-memory filesystem to represent that directory tree. Because of this, actually any FSAL can be used for the pseudo root, however, Ganesha will only automatically manage the directory tree for FSAL_PSEUDO exports.

Note that it is actually possible to create additional FSAL_PSEUDO exports. For example, perhaps you have two exports with the following pseudo paths:

/export/exp1
/export/exp1/some/path/ep2

However, although some/path makes logical sense, you don't actually want to expose those directories in the filesystem that is exported for exp1, so you create a FSAL_PSEUDO export:

/export/exp1/some

And then Ganesha will automatically create a "path" directory in that pseudo filesystem.

You can specify FSAL_PSEUDO exports just like any other FSAL.

**Comment by Bingo0203** [comment] 2024-01-17 03:03
1. The state_hdl is initialized by 'glist_init', but all the 'glist_init's I've looked at are initialized by the 'state_hdl_init' function, and I haven't seen any other functions assigning or initializing them, is this true?
2. The concept of state_hdl.dir.junction_export is still unclear, what characteristics of the obj does it reflect, or does it indicate that the directory or file is mounted by more than one file?
3. Thank you for explaining "delegation" to me, which has given me a better understanding.
4. Thank you for explaining so much about pseudofs, but I still have some doubts. 
    Simply put, can I understand this way, 
     a）each export in '/etc/ganesha/ganaesha.conf' in the ganesha server is equivalent to a pseudofs；
     b）or that  pseudofs is equivalent to a base, and all these exports are implemented based on this pseudofs?
Am I understanding a) correctly or b) correctly or neither of them
However,  does pseudofs interact with FSAL_CEPH? The call to the different levels I see is through the function pointer obj_ops in fsal_obj_handle, but how does this function pointer get converted from pseudofs to ceph level, this is a piece of detail I've never understood when looking at the code
Sometimes see obj_ops is mdcache layer call to pseudo layer, sometimes is mdcache layer call to fsal_ceph layer, this piece of never understand, obj_ops initialization function also did not see call it.

**Comment by ffilz** [comment] 2024-01-18 00:59
1. I may be confused by this question, but state_hdl_init should be the only place initializing the glist_head in question
2. Ganesha's export tree is built in a similar way to filesystems on Linux. Each export is "mounted" on a directory in some other export. That export could be the automatically constructed pseudofs. The "parent" export will have a directory that is the "mount point" for the "child" export. That directory is labeled a junction. The directory in the "child" export that is exported is labeled an export root. Note you CAN export something like /fs1/exp1 and /fs1/exp1/some/directory where that is all a single ext4 filesystem exported with FSAL_VFS. The directory /fs1/exp1/some/directory will then end up being both a junction AND an export root but typically, the junction is a pseudofs directory and the export root is a real filesystem directory.
3. you're welcome
4. In NFSv4, all exports are represented in a single file tree. When portions of that file tree are not backed by a real filesystem that has been exported, they are labeled part of the pseudofs. Ganesha provides FSAL_PSEUDO to provide the logic for the pseudofs, and it will automatically construct a pseudofs at pseudo root if there is no export specified with Pseudo="/";. If the desired tree includes pseudofs sections other than at root, the admin must explicitly create FSAL_PSEUDO exports for those, but then once they exist, Ganesha will automatically populate them with the directories necessary to reach any exports "mounted" in that portion of the file tree.

When a junction is crossed by LOOKUP or READDIR, the op_ctx is updated to reflect the new export. The lookup (or readdir) then continues in that new export. You can easily follow the path in nfs4_op_lookup.c. See the check for non-NULL junction. Importantly note get_gsh_export_ref, set_op_context_export, nfs_export_get_root_entry. Once that is done, the "current" directory is now the root directory of the new export and lookup proceeds from there. READDIR has some similar logic to handle directory entries in the listing that are junctions. SECINFO can also cross junctions.

**Comment by Bingo0203** [comment] 2024-02-02 08:00
Thanks

**Comment by ffilz** [comment] 2024-02-21 00:50
Can we close this now?

**Comment by ffilz** [comment] 2024-07-23 23:43
Closing, no response in more than 60 days.

**Closed as completed** 2024-07-23 23:43 UTC
Labels: Question, Can we close?
