### ISSUE TITLE
The NFS client cannot access the mounted directory for a long time

### ISSUE THREAD

**Issue by betainc** [nfs-ganesha/nfs-ganesha#756] opened 2021-11-01 12:01 UTC
testing scenarios：
Three ganesha server nodes: Node1, Node2, Node3. The whole system achieves HA through CTDB, each node has three virtual IPs to provide external access services.
A client is mounted on Node1.
The storage backend is ceph. Grace_Period = 10; Lease_Lifetime = 10;  RecoveryBackend = rados_kv;
The ganesha version is 3.3, the nfs-utils version of client is 2.3.3-31, the ceph version is 14.

Test steps:
1. The client is mounted on Node1 through a virtual IP, and the NFS protocol is 4.2.
2. The client server reads and writes data to the mounted directory through vdbench.
3. Disable the network via the ifdown command on Node3.
4. The IOPS of the client vdbench became 0, and it could not be recovered for tens of hours.

Problem analysis:
Disable Node3 network, CTDB will let ganesha on Node1 take over its virtual IP and enter grace.
Then the client vdbench drops 0. Theoretically, after grace is over, the client will return to normal.

In fact, Ganesha ended grace soon, but some errors occurred:
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 10
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 2 nodeid -1 ip 2025:806::182
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip 2025:806::182
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 10
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 2 nodeid -1 ip 100.100.100.8
29/10/2021 13:39:16 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip 100.100.100.8
29/10/2021 13:39:19 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 10
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip 2025:806::182
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 10
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip 192.168.42.102
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
29/10/2021 13:39:21 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
29/10/2021 13:39:24 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
29/10/2021 13:39:29 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
29/10/2021 13:39:34 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
29/10/2021 13:39:34 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE

ganesha exited grace, but the client still cannot access normally. After opening the debug level log, you can see some error messages:

29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] process_one_op :NFS4 :DEBUG :Request 2: opcode 18 is OP_OPEN
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] process_one_op :NFS4 :M_DBG :Check export perms export = 000001e0 req = 00000080
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] check_resp_room :NFS4 :F_DBG :Status of OP_OPEN in position 2 is ok so far, op response size = 152 total response size would be = 248 out of max 1049480/7584
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] nfs4_op_open :STATE :DEBUG :Entering NFS v4 OPEN handler -----------------------------
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] nfs4_op_open :STATE :F_DBG :OPEN: Claim type = 0, Open Type = 1, Share Deny = 0, Share Access = 2 
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] nfs4_op_open :STATE :DEBUG :OPEN Client id = 617b878e00000009
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] create_nfs4_owner :STATE :F_DBG :Key=STATE_OPEN_OWNER_NFSV4 0x7fecaf4bebd0: clientid={0x2bef400 ClientID={Epoch=0x617b878e Counter=0x00000009} CONFIRMED Client={0xa74a310 name=(32:Linux NFSv4.2 host-192-168-9-101) refcount=1} t_delta=0 reservations=1 refcount=4} owner=(24:0x6f70656e2069643a0000003a0000000100022566cec03111) confirmed=1 seqid=0 refcount=1
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] get_state_owner :STATE :F_DBG :Find {STATE_OPEN_OWNER_NFSV4 0x7fecaf4bebd0: clientid={0x2bef400 ClientID={Epoch=0x617b878e Counter=0x00000009} CONFIRMED Client={0xa74a310 name=(32:Linux NFSv4.2 host-192-168-9-101) refcount=1} t_delta=0 reservations=1 refcount=4} owner=(24:0x6f70656e2069643a0000003a0000000100022566cec03111) confirmed=1 seqid=0 refcount=1}
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] get_state_owner :STATE :F_DBG :New {STATE_OPEN_OWNER_NFSV4 0x193afa40: clientid={0x2bef400 ClientID={Epoch=0x617b878e Counter=0x00000009} CONFIRMED Client={0xa74a310 name=(32:Linux NFSv4.2 host-192-168-9-101) refcount=1} t_delta=0 reservations=1 refcount=5} owner=(24:0x6f70656e2069643a0000003a0000000100022566cec03111) confirmed=1 seqid=0 refcount=1}
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] open4_open_owner :STATE :F_DBG :Open: STATE_OPEN_OWNER_NFSV4 0x193afa40: clientid={0x2bef400 ClientID={Epoch=0x617b878e Counter=0x00000009} CONFIRMED Client={0xa74a310 name=(32:Linux NFSv4.2 host-192-168-9-101) refcount=1} t_delta=0 reservations=1 refcount=5} owner=(24:0x6f70656e2069643a0000003a0000000100022566cec03111) confirmed=1 seqid=0 refcount=1
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] nfs4_op_open :NFS4 :DEBUG :open4_validate_claim failed
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] nfs4_op_open :STATE :DEBUG :failed with status NFS4ERR_GRACE
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] dec_state_owner_ref :STATE :F_DBG :Free {STATE_OPEN_OWNER_NFSV4 0x193afa40: clientid={0x2bef400 ClientID={Epoch=0x617b878e Counter=0x00000009} CONFIRMED Client={0xa74a310 name=(32:Linux NFSv4.2 host-192-168-9-101) refcount=1} t_delta=0 reservations=1 refcount=5} owner=(24:0x6f70656e2069643a0000003a0000000100022566cec03111) confirmed=1 seqid=0 refcount=1}
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] complete_op :NFS4 :F_DBG :Current FH  Len=31 0x8070e212000000000000000000000000000000000000000000000000000000
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] complete_op :NFS4 :F_DBG :Saved FH    Len=0 (EMPTY)
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] complete_op :NFS4 :DEBUG :Status of OP_OPEN in position 2 = NFS4ERR_GRACE, op response size is 4 total response size is 92
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] complete_nfs4_compound :NFS4 :DEBUG :End status = NFS4ERR_GRACE lastindex = 3
29/10/2021 14:54:18 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_21] release_nfs4_res_compound :NFS4 :F_DBG :Skipping free of NFS4 result 0x1dcbacc0 refcnt 1
29/10/2021 14:54:19 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_27] nfs4_Compound :NFS4 :DEBUG :COMPOUND: There are 1 operations, res = 0x1679b900, tag = NO TAG
29/10/2021 14:54:19 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_27] process_one_op :NFS4 :DEBUG :Request 0: opcode 53 is OP_SEQUENCE
29/10/2021 14:54:19 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_27] release_nfs4_res_compound :NFS4 :F_DBG :Compound Free 0x1dc69d10 (resarraylen=1)
29/10/2021 14:54:19 : epoch 617b878e : host-192-168-14-152 : ganesha.nfsd-2597756[svc_27] check_resp_room :NFS4 :F_DBG :Status of OP_SEQUENCE in position 0 is ok so far, op response size = 40 total response size would be = 84 out of max 1049480/3416

Can be analyzed from the log:
clientid->cid_cb.v41.cid_reclaim_complete is false.

In addition, it is normal if the directory is remounted through a new client. The new client can read and write normally.
Finally, restart the ganesha process, and the abnormal client will return to normal.

So I want to know how to locate this problem. Any directions or suggestions? thanks.

**Comment by dang** [comment] 2021-11-01 14:00
Things like this have usually been network issues in my experience.  There are lots of potential network problems with IP failover.

First, and most common, is the ARP table on the NFS client.  This is the mapping between the IP address and the physical, network layer address, called the MAC that assigned to the network card on the server.  All computers keep such a mapping, and there's a protocol (named Address Resolution Protocol, ARP) that allows a client to request the MAC associated with a given IP.  When the failover happens, the IP will get a new MAC (the MAC of the new server), but the client will continue to send packets to the old MAC.  To get around this, the new server will send a special ARP packet saying that it now owns the IP, called a Gratuitous ARP.  Sometimes, routers and switches are configured to filter these packets, or clients are configured to ignore them, since they can be used to cause a DoS.  If this is the case, the client will continue to send to the old MAC until it's ARP entry times out, which can be a long time.

The second possibility is that you have a smart switch in the network with it's own ARP table, and it is sending the packets out the wrong port (the one connected to the old server, not the new server).  This can happen if there is a bug in the switch, or if it is configured to ignore the Gratuitous ARP.

You can try doing a packet dump on the three computers (the client, the old server, and the new server) and see where the packets are going.  If they continue to go to the old server rather than the new one, then network issues are the problem.

Because a new client can connect to the new server, it's unlikely to be a problem with Ganesha itself.

**Comment by Liam-program** [comment] 2021-11-02 15:56
I have encountered the same problem.
The old client occasionally fails to recover, but the new client can continue to connect to Ganehsa normally. 
I wonder if there are some bugs in the client code or Ganesha‘s failover process, that prevented the old client from switching over. Because if ARP is a problem, it should be a problem every time, but the reality is not.

**Comment by ffilz** [comment] 2021-11-02 16:40
ARP could still be the problem if something is blocking gratuitous ARP, The new client sends it's own ARP to find the address. If the switch is passing that on but not the gratuitous ARP, then new clients could get the correct MAC address while old clients don't until they time out the TCP session and issue a new ARP.

The best diagnostic here is tcpdump traces from the client, and also possibly from the server nodes involved. The client for sure since we can then see what it actually sees on the wire.

**Comment by betainc** [comment] 2021-11-03 10:35
@dang @ffilz 
Thank you for your replies and suggestions.

Sorry for an error in the test steps described last time. In fact, the IP mounted by the client was originally on Node2. After Node3 disabled the network card, this IP was switched to Node1, and Node1 also received the client's request later. The original virtual IPs of the two normal nodes are also switched.

Next, I plan to reproduce this problem based on your suggestions and analyze it through packet capture.

**Comment by ffilz** [comment] 2021-11-03 17:21
Sounds good.

**Comment by betainc** [comment] 2021-11-15 11:42
@dang @ffilz 
After two weeks of testing, did not find this problem again.
In addition, I have a question. Regarding the configuration of ganesha, the Grace_Period and Lease_Lifetime are both 10s. Is it too short? Would it be more appropriate to change to 30s, or another time?

**Comment by dang** [comment] 2021-11-15 14:31
The lease lifetime is related to the maximum latency that you may expect in your setup.  That is, what is the longest that a client or server can ever take to respond to the other, including potential network issues (such as links failing, and routing updating to a new connection).

Grace period is the maximum amount of time it takes for a replacement server to come up and re-sync with *all* it's clients in the case of a server failure.  It should absolutely be longer than the lease lifetime; a good rule of thumb is 1.5-3x as long as the lease, depending on the lease time.

If you have only fast, local networks (no routing, only switching), then 10 s lease might be okay.  You will need to have a longer grace, however, since grace recovery depends on it being longer than lease.  You essentially need a lease + resync time to ensure grace works correctly (and that assumes no packet loss in the network).

**Comment by ffilz** [comment] 2021-12-20 21:03
Is this still an open question?

**Comment by ffilz** [comment] 2023-01-24 19:45
This has gone more than a year with no activity. Closing as unresolved.

**Comment by zhengfeihu51** [comment] 2023-06-28 12:57
I also encountered this issue with NFS-Ganesha + CephFS backend.

On the server side, we have a three-node cluster, and there's one client that mounts a Ganesha server using a virtual IP. We ran vdbench, and we performed a series of down/up operations on the network interface of two nodes. After a few iterations of these operations, the client's business continuously dropped to 0 and became unrecoverable.

Upon examining the server-side logs, we found frequent virtual IP migrations. Following the failure, the server kept responding to the client's open requests with NFS4ERR_GRACE error. During the failure, we observed RPC errors in the logs. Here are the specific log entries:

19/06/2023 15:46:00 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
19/06/2023 15:46:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:46:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip abca:909::23
19/06/2023 15:46:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
19/06/2023 15:46:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
19/06/2023 15:46:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
19/06/2023 15:46:20 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:46:30 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:46:40 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:46:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:48:52 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_13] complete_op :NFS4 :EVENT :Error status of OP_CREATE_SESSION in position 0 = NFS4ERR_STALE_CLIENTID
19/06/2023 15:51:56 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_20] rpc :TIRPC :EVENT :svc_vc_wait: 0x5932a00 fd 18 recv errno 104 (will set dead)
19/06/2023 15:52:43 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_22] rpc :TIRPC :EVENT :svc_fd_ncreatef: fd 18 getpeername failed (-1)
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_22] rpc :TIRPC :EVENT :clnt_vc_ncreatef: fd 18 svc_fd_ncreatef failed
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_22] nfs_rpc_create_chan_v41 :NFS CB :WARN :can not create back channel, code 22
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_22] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 2 nodeid -1 ip 166.37.165.21
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip 166.37.165.21
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 2 nodeid -1 ip abca:909::21
19/06/2023 15:52:44 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip abca:909::21
19/06/2023 15:52:45 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:45 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 2 nodeid -1 ip abca:909::20
19/06/2023 15:52:45 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_release_v4_clients :STATE :EVENT :NFS Server V4 recovery release ip abca:909::20
19/06/2023 15:52:47 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:47 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip abca:909::21
19/06/2023 15:52:47 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
19/06/2023 15:52:47 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
19/06/2023 15:52:47 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip abca:909::20
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server Now IN GRACE, duration 30
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :NFS Server recovery event 5 nodeid -1 ip 166.37.165.21
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_traverse :CLIENT ID :EVENT :Failed to lst kv ret=-2
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] rados_kv_read_recov_clids_takeover :CLIENT ID :EVENT :Failed to takeover
19/06/2023 15:52:50 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[dbus_heartbeat] nfs_start_grace :STATE :EVENT :grace reload client info completes from backend
19/06/2023 15:52:54 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:52:59 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_23] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:53:04 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:53:14 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:53:14 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_12] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:53:24 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_try_lift_grace :STATE :EVENT :check grace:reclaim complete(0) clid count(0)
19/06/2023 15:53:24 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
19/06/2023 15:53:29 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_20] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:53:45 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_18] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:54:00 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_25] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:54:16 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_12] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:54:31 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_20] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:54:46 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_18] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE
19/06/2023 15:55:02 : epoch 03c5d313 : b75d9f18a98d : ganesha.nfsd-1[svc_25] complete_op :NFS4 :EVENT :Error status of OP_OPEN in position 2 = NFS4ERR_GRACE


In addition, I can't understand why filtering gratuitous ARP on the client side could cause this issue. It seems that the server has completed the virtual IP migration, and the client has established communication with the new server.

**Comment by ffilz** [comment] 2023-06-28 14:49
Please provide a full description of your setup and failover process.

**Comment by zhengfeihu51** [comment] 2023-07-01 03:06
> Please provide a full description of your setup and failover process.

The specific operation is as follows: a single client mounts the Ganesha server through a virtual IP, and the mounted virtual IP is abca:909::20. After the mount, the business runs for a period of time. The testers perform network down and up operations on two fixed nodes of the three-node cluster. The specific operations are: performing a down operation on the network card of node 1, and then immediately performing an up operation; then performing similar operations on node 2, the time for the network card to go down and up may vary from a few seconds to a dozen seconds. There is no waiting for the business to recover during the down and up operations of the node network card. After nodes 1 and 2 repeatedly perform these operations several times, the NFS4ERR_GRACE situation occurs.

In addition, we also performed the same test later to try to reproduce the failure, but it was not successful.

Additionally, here are some additional information: after the failure, we set the logs to debug level and located the error to be in open4_validate_claim function. Combining other log information, we found that there are only two possible error locations:

1. 
case CLAIM_NULL:
    if ((data->minorversion > 0)
        && !clientid->cid_cb.v41.cid_reclaim_complete)
        status = NFS4ERR_GRACE;
    break;

2.
if (status == NFS4_OK) {
    if (take_ref) {
        if (nfs_get_grace_status(want_grace)) {
            *grace_ref = true;
        } else {
            status = want_grace ? NFS4ERR_NO_GRACE :
                            NFS4ERR_GRACE;
        }
    } else {
        *grace_ref = false;
    }
}

**Comment by zhengfeihu51** [comment] 2023-07-01 03:08
> Please provide a full description of your setup and failover process.

The specific operation is as follows: a single client mounts the Ganesha server through a virtual IP, and the mounted virtual IP is abca:909::20. After the mount, the business runs for a period of time. The testers perform network down and up operations on two fixed nodes of the three-node cluster. The specific operations are: performing a down operation on the network card of node 1, and then immediately performing an up operation; then performing similar operations on node 2, the time for the network card to go down and up may vary from a few seconds to a dozen seconds. There is no waiting for the business to recover during the down and up operations of the node network card. After nodes 1 and 2 repeatedly perform these operations several times, the NFS4ERR_GRACE situation occurs.

In addition, we also performed the same test later to try to reproduce the failure, but it was not successful.

Additionally, here are some additional information: after the failure, we set the logs to debug level and located the error to be in open4_validate_claim function. Combining other log information, we found that there are only two possible error locations:

1:case CLAIM_NULL:
    if ((data->minorversion > 0)
        && !clientid->cid_cb.v41.cid_reclaim_complete)
        status = NFS4ERR_GRACE;
    break;

2:if (status == NFS4_OK) {
    if (take_ref) {
        if (nfs_get_grace_status(want_grace)) {
            *grace_ref = true;
        } else {
            status = want_grace ? NFS4ERR_NO_GRACE :
                            NFS4ERR_GRACE;
        }
    } else {
        *grace_ref = false;
    }
}

**Comment by ffilz** [comment] 2023-07-03 15:22
A couple suggestions:

1. Get a network trace and see if that helps clarify which error case is being hit.

2. Add some LogFullDebug messages to clarify the decision making.

And one more question, what is the client? I wonder if the client is doing something wrong.

But it could also be that the bouncing is confusing the grace period logic somehow.

**Comment by zhengfeihu51** [comment] 2023-07-04 01:40
> A couple suggestions:
> 
> 1. Get a network trace and see if that helps clarify which error case is being hit.
> 2. Add some LogFullDebug messages to clarify the decision making.
> 
> And one more question, what is the client? I wonder if the client is doing something wrong.
> 
> But it could also be that the bouncing is confusing the grace period logic somehow.

The version of the Linux kernel is: Linux version 4.18.0-193.14.2.el8_2.x86_64.

In addition, there is some information I forgot to mention: during the failure, other clients mounting the target Ganesha server and running vdbench were functioning normally. Also, the problematic client, when mounted to the target Ganesha server and running vdbench, was able to carry out its operations normally.

I will try your suggestions, but reproducing the issue under normal circumstances may be challenging. I am not sure if it is possible to actively simulate this error by modifying the Ganesha code.

**Comment by ffilz** [comment] 2024-02-21 00:57
Is this still an issue? Can we close it?

**Comment by ffilz** [comment] 2024-07-23 23:42
Closing, no response in more than 60 days.

**Closed as completed by ffilz** 2024-07-23 23:42 UTC
Labels: Question, Can we close?
