### ISSUE TITLE
compile 2.8.3 with dbus failed

### ISSUE THREAD

**Issue by fanzi2009** [nfs-ganesha/nfs-ganesha#523] opened 2019-12-27 08:08 UTC
`git clone https://github.com/nfs-ganesha/nfs-ganesha.git`

`git checkout V2.8.3`

`git submodule update --init --recursive`

`cmake .. -DUSE_GSS=0 -DUSE_CAPS=0 -DUSE_FSAL_LUSTRE=0 -DUSE_9P=0 -DUSE_FSAL_GPFS=0 -DUSE_FSAL_PROXY=0 -DUSE_NLM=0 -DUSE_NFS3=0 -DUSE_GUI_ADMIN_TOOLS=0 -DRPCBIND=0 -DUSE_NFS3=0 -DUSE_NLM=0 -DUSE_DBUS=1`

`make`

Scanning dependencies of target ganesha_nfsd
Linking C shared library libganesha_nfsd.so
[ 90%] Built target fsal_os
../support/CMakeFiles/support.dir/export_mgr.c.o:(.data.rel+0x80): undefined reference to `auth_statistics'
collect2: error: ld returned 1 exit status
make[2]: *** [MainNFSD/libganesha_nfsd.so.2.8] Error 1
make[1]: *** [MainNFSD/CMakeFiles/ganesha_nfsd.dir/all] Error 2
make: *** [all] Error 2

**Comment by kalebskeithley** [comment] 2019-12-27 21:32
I take it fsal_os is your FSAL?

You just need to add a line for auth_statistics to .../src/MainNFSD/libganesha_nfds.ver.

You should send a patch to gerrithub.io for that change. It would be useful to know why your FSAL needs to call auth_statistics() since none of the other FSALs have ever needed it.

**Comment by kalebskeithley** [comment] 2019-12-30 15:37
closing. I presume this  is the solution to your issue.

**Closed as completed by kalebskeithley** 2019-12-30 15:37 UTC

**Comment by joshtriplett** [comment] 2020-02-23 22:27
I can reproduce this, and it seems entirely unrelated to the FSAL using the function.

If `USE_DBUS` is enabled, and `_HAVE_GSSAPI` is disabled (not an uncommon or unreasonable combination), then `src/idmapper/idmapper.c` doesn't compile in the `auth_statistics` structure or corresponding function at all, but `src/support/export_mgr.c` references it unconditionally.

I think `export_mgr.c` needs an `#ifdef` around its use of `auth_statistics`.

Filed as https://github.com/nfs-ganesha/nfs-ganesha/issues/540
