### ISSUE TITLE
Adding VFS backed export fails occassionaly due to an error somewhere around vfs_get_root_handle (V3.3)

### ISSUE THREAD

**Issue by ghost** [nfs-ganesha/nfs-ganesha#599] opened 2020-06-11 09:01 UTC
While testing short-lived NFS mounts on short-lived zfs filesystems, ganesha occasionally fails to add the export.

One example is:
```
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] gsh_export_addexport :EXPORT :INFO :Adding export from file: /export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf with EXPORT(Export_Id=13888)
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] vfs_get_root_handle :FSAL :MAJ :Could not open VFS mount point /run/user/0: rc = No such file or directory (2)
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] process_claim :FSAL :CRIT :FSAL VFS failed to claim file system /run/user/0 error No such file or directory
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] vfs_create_export :FSAL :CRIT :resolve_posix_filesystem(/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/nfs) returned No such file or directory (2)
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] mdcache_fsal_create_export :FSAL :MAJ :Failed to call create_export on underlying FSAL VFS
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] fsal_cfg_commit :CONFIG :CRIT :Could not create export for ((null)) to (/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/nfs)
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] gsh_export_addexport :EXPORT :CRIT :0 export entries in /export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf added because (export create, block validation) errors
09/06/2020 17:48:22 : epoch 5edf916b : devnfs2 : ganesha.nfsd-2572688[dbus_heartbeat] dbus_message_entrypoint :DBUS :MAJ :Method (AddExport) on (org.ganesha.nfsd.exportmgr) failed: name = (org.freedesktop.DBus.Error.InvalidFileContent), message = (0 export entries in /export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf added because (export create, block validation) errors. Details:
Config File (/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf:8): 1 validation errors in block FSAL
Config File (/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf:8): Errors processing block (FSAL)
Config File (/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf:1): 1 validation errors in block EXPORT
Config File (/export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe/export.conf:1): Errors found in configuration block EXPORT
```

The zfs filesystem is /export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe. Directly in the filesystem root there is an export.conf containing the export configuration and a folder "nfs" (in this case) that is the path to be exported.

In this case the error is reported for the seemingly unrelated /run/user/0.

Some partial stat-output:
```
File: /
Device: fd00h/64768d	Inode: 2           Links: 22

File: /run/
Device: 17h/23d	Inode: 2           Links: 33

File: /run/user/0
Device: 38h/56d	Inode: 2           Links: 5

File: /export/testnfsd/clone_f03d8314c8251da9622a7268996e032f7b86313c_Xt-vRqeIWOIe
Device: 31h/49d	Inode: 34          Links: 4
```

I have also seen the error with the special zfs directory .zfs/snapshot being reported instead of /run/user/0. This directory is as I understand it automatically mounted and umounted as needed. I added a filter for that type of path in populate_posix_file_systems, which seems to have helped.

I'm wondering if the error might simply be about bad-timing, where the filesystem disappears at the wrong time which causes something to propagate an unrelated error a bit too far, but I haven't dug deep enough to really understand the error.

**Comment by dang** [comment] 2020-06-11 14:40
It seems that the dev.major and dev.minor from stat()ing the new FS also matches the dev.major and dev.minor from /run/user/0.  Since claiming a posix FS depends on the device numbers, rather than the path, this means that if those numbers match at the time of the scan, then Ganesha will treat them as the same, and try to open the first one.  In this case, it's /run/user/0, which can't be opened.

**Comment by ghost** [comment] 2020-06-11 15:01
I couldn't square that with the stat-output, but I see now that /run/user/0 is not static, so I guess it's that simple (or I'm reading it wrong).

Is there any obvious workaround for this? If device numbers are not guaranteed to be unique it doesn't seem that robust to rely on them entirely.

**Comment by dang** [comment] 2020-06-11 15:09
I think device numbers *should* be unique, but it appears they're not?

**Comment by ghost** [comment] 2020-06-11 15:16
Just quick speculating without actually checking the code, but maybe some race condition in the duplicate-filesystem detection? This has only happened so far after creating/destroying thousands of filesystems/exports in fairly quick succession, so I assume it's some kind of edge case.

**Comment by malahal** [comment] 2020-06-11 17:54
> I think device numbers _should_ be unique, but it appears they're not?

They are unique at any instant of time,  but they are re-used pretty quickly with mount/unmount!

**Comment by ffilz** [comment] 2020-06-11 19:30
This may be a case of needing the filesystem management stuff that's part of my big patch set. One of the things that I am doing is flushing out old fsal_file_system entries which should clear up the problem with re-used device ids.

**Comment by malahal** [comment] 2020-06-14 04:37
Correct, I think we need that patch to fix this issue.

**Comment by ffilz** [comment] 2020-06-15 16:57
Everyone with an interest in the export stuff should watch my patch set on Gerrithub . I expect to be posting an updated patch set this week.

**Comment by ffilz** [comment] 2020-07-15 21:44
This should be fixed upstream. Please verify and indicate if the issue is resolved.

**Comment by ffilz** [comment] 2020-08-13 23:02
With some code changes that should mitigate this, and no action for nearly 30 days, I will close this as resolved.

**Closed as completed by ffilz** 2020-08-13 23:02 UTC
