### ISSUE TITLE
Poor and unstable performance with ganesha 2.3.3

### ISSUE THREAD

**Issue by mwang911** [nfs-ganesha/nfs-ganesha#319] opened 2018-07-26 13:52 UTC
I use ganesha 2.3.3, and I am confused with the code of function "thr_stallq". This function choose to sleep 1s which in my test it influences the performance and makes the bandwidth very unstable. I wonder if this code is needed,  and I think 1 second is somewhat too long delay time.
Well, I test the performance under 10Gbps network, with which the requests seem to be more than 2048, which is the max of param "dispatch_max_reqs_xprt". I know that if requests surpass "dispatch_max_reqs_xprt", the function above will be executed and thread will delay until unstalled.

I need a way to increase the performance and make the bandwidth stable,  however I have no idea how to do it. Why is 2048 chosen for "dispatch_max_reqs_xprt" ? Can I change it to high number like 3000 or 4000 ? And about the stall function, is there a better way to realize it ?

**Comment by mattbenjamin** [comment] 2018-07-26 13:56
the entire logic is replaced in 2.6 and above;  upgrading would be the most sensible move

**Comment by dang** [comment] 2018-07-27 14:07
That's part of the code that was designed to allow fair client access.  As Matt said, it's been completely reworked in 2.6 and later.  As for why 2048 was chosen, I'm not sure.  It's been that way since close to the very beginning of the Ganesha project, before I was involved.

Also, for the record, 2.3 is very old (3, soon to be 4, major revs out-of-date) and so hard to support.

**Comment by ffilz** [comment] 2020-06-15 23:28
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed by ffilz** 2020-06-15 23:28 UTC
