### ISSUE TITLE
2.3.0-2.3.2: Commit cf1fe24c9e51dd1f5aeea89485bf680d2ba06f1c causes Gluster issue with symlinks

### ISSUE THREAD

**Issue by alexat** [nfs-ganesha/nfs-ganesha#99] opened 2016-05-20 18:30 UTC
How to reproduce:

Create symlink that has no equivalent target on Gluster servers. Even symlink from non-existent file goes. Like
ln -s 1 2
(1 should not exist)
or
ln -s /some/non/existent/file test

Expected result: symlink created and works on mounts (files like /some/non/existent/file can exist on mounting servers locally).
Actual result: error during creation and 'stale file handle' error on trying to access newly created symlink. Not visible, not deletable, etc.

**Comment by soumyakoduri** [comment] 2016-05-23 17:34
FWIH, it could be the regression caused when enabled ACLs by one of the gluster xlators. Could you re-try the test after disabling ACLs.

**Comment by alexat** [comment] 2016-05-23 17:43
I'm feeling dumb there, but how do I check for ACL enabled or disable them? The only option I know is 'acl' mount option, and this volume is not mounted anywhere.

**Comment by soumyakoduri** [comment] 2016-05-23 17:46
in nfs-ganesha ACLs are enabled by default. To disable for a particular share/volume, add below line  in the export file of that volume -

EXPORT {
...
...
Disable_ACL = true;
...
..
}

and then restart ganesha service or re-export the volume.

**Comment by alexat** [comment] 2016-05-23 18:11
Indeed, Disable_ACL = true on export fixed it.

**Comment by soumyakoduri** [comment] 2016-05-23 18:21
okay cool..this is known issue for now ..will fix it soon.

**Comment by thotz** [comment] 2016-05-25 11:49
This regression was caused due to https://review.gerrithub.io/#/c/253518/ change
I going to revert that change.

**Comment by alexat** [comment] 2016-06-25 14:46
Red Hat seems to have introduced a more proper fix.

if (status.minor == ENOENT) {
  if (obj_hdl->type == SYMBOLIC_LINK)
    status = fsalstat(ERR_FSAL_NO_ERROR, 0);
  else
    status = gluster2fsal_error(ESTALE);
}

**Comment by ffilz** [comment] 2017-01-17 23:41
Can this issue be closed? I will close it next week if there is no response otherwise.

**Comment by thotz** [comment] 2017-01-18 06:01
Sorry I lost track of this issue . The patch https://review.gerrithub.io/#/c/279330/ already got merged seven months ago. Hence closing this issue

**Closed** 2017-01-18 17:53 UTC
