### ISSUE TITLE
Very slow "ls -l" performance while using NFS-Ganesha mount

### ISSUE THREAD

**Issue by syspro4** [nfs-ganesha/nfs-ganesha#767] opened 2021-12-07 06:34 UTC
Hi,

I have observed very slow 'ls -l' performance while using nfs-ganesha (NFSv4.2) mount point. Following are the test details:

1. Configured 1 brick gluster volume (to make things simple).
2. Created very simple nfs-ganesh.conf file with just EXPORT{FSAL->GLUSTER} block. 
3. Mounted NFS export on a host with NFSv4.2
     $ mount -t nfs4 -o minorversion=2,rsize=1048576,wsize=1048576 192.168.2.11:/g_vol /mnt 
4. Created 50,000 4k sized files
5. Ran '**time ls -l | wc -l**' test:

          Brick (XFS)         :  0.346s
          NFS Ganesha v4.2.   : 11.778s
          Gluster FUSE client :  3.592s
          Kernel NFSv4.2.     :  0.614s

From above experiments it shows that 'ls -l' is taking very long time to count 50k files compared to other protocols/methods. 

I tried setting entries_hwmark=500000 & chunks_hwmark=500000 but I did not see any improvement.

Is there any configuration setting that is required to lower the time?

Currently I am using NFS-Ganesha v3.5 & GlusterFS 9.4.

Thanks!

**Comment by dang** [comment] 2021-12-08 14:36
The default sizes for the hw_marks are large enough to hold the entire directory, to that isn't a problem.   Readdir with gluster should be fast, and was last time I checked it.  My guess is that USE_GLUSTER_XREADDIR_PLUS was not set when Ganesha was built.  Maybe something changed in Gluster w.r.t. the readdirplus API?

**Comment by syspro4** [comment] 2021-12-08 18:30
Thanks dang for your reply.

I confirmed with gdb that the USE_GLUSTER_XREADDIRPLUS flag is set and it is calling glfs_xreaddirplus_r().
Also according to above numbers we can see that gluster readdir is fast compared to NFS.

**Comment by dang** [comment] 2021-12-08 19:11
I'm not sure what's wrong, then.  I haven't tested gluster personally in a long time (maybe gluster 5?) so I'm not sure what's changed.  It used to return a large buffer of dirents with their stat results in a single call, which was optimal for Ganesha.  If that changed in any way, then it would be slow again.

The overwhelming amount of time Ganesha spends in readdir is round trips to the cluster, so minimizing those has been the goal.

**Comment by syspro4** [comment] 2021-12-08 19:33
Thanks for your reply.
I can explore more on the round trips part if you can share some more details about it.
Thanks!

**Comment by syspro4** [comment] 2021-12-10 18:59
Hi,
Can you please share any thoughts on improving 'ls  -l' performance? 
Thanks!

**Comment by dang** [comment] 2021-12-13 14:19
What I've done in the past is enable lttng and look at timestamps on the traces to see where time is being spent.  That should point us to where the issue is.

**Comment by syspro4** [comment] 2021-12-15 20:29
I will enable lttng & get that info.

**Comment by ffilz** [comment] 2021-12-22 19:27
Bump to keep this ahead of inactive issues.

**Comment by syspro4** [comment] 2021-12-29 22:32
Hi,

I am able to capture the lttng data for 'ls -l | wc -l' command.
From the lttng traces I do not see any abnormal behavior which takes long time BUT I see that nfs-ganesha processes the readdir contents sequentially. I also used Trace Compass Tool to visually check if there are any anomalies but I do not see any thing.

The read_dirents() call (mdcache_populate_dir_chunk->read_dirents) processes 1 dir entry at a time and calls a callback mdc_readdir_chunked_cb for that entry & this happens for all the entries sequentially. 

Following is the sample lttng output. I will also attach complete log  for the reference.

[readdir_trace.tar.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/7790841/readdir_trace.tar.gz)

[06:25:18.755125122] (+0.000002080) node1 mdcache:qlock: { cpu_id = 0 }, { function = "lru_insert_entry", line = 421, qlane = 0x7F3C7CB0E640 }
[06:25:18.755125817] (+0.000000695) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "lru_insert_entry", line = 425, qlane = 0x7F3C7CB0E640 }
[06:25:18.755126847] (+0.000001030) node1 mdcache:mdc_lru_insert: { cpu_id = 0 }, { function = "cih_set_latched", line = 375, obj_handle = 0x7F3C560BA638, refcnt = 2 }
[06:25:18.755142697] (+0.000015850) node1 mdcache:mdc_lru_get: { cpu_id = 0 }, { function = "mdcache_lru_get", line = 1947, obj_handle = 0x7F3C560BAB38, sub_handle = 0x7F3C560BB098, refcnt = 2 }
[06:25:18.755145081] (+0.000002384) node1 mdcache:qlock: { cpu_id = 0 }, { function = "lru_insert_entry", line = 421, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755145764] (+0.000000683) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "lru_insert_entry", line = 425, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755146996] (+0.000001232) node1 mdcache:mdc_lru_insert: { cpu_id = 0 }, { function = "cih_set_latched", line = 375, obj_handle = 0x7F3C560BAB38, refcnt = 2 }
[06:25:18.755449367] (+0.000302371) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref_chunk", line = 2150, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755450862] (+0.000001495) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref_chunk", line = 2160, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755451758] (+0.000000896) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref_chunk", line = 2150, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755452474] (+0.000000716) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref_chunk", line = 2160, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755454015] (+0.000001541) node1 mdcache:qlock: { cpu_id = 0 }, { function = "lru_bump_chunk", line = 2173, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755455262] (+0.000001247) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "lru_bump_chunk", line = 2194, qlane = 0x7F3C7CB0F1A0 }
[06:25:18.755456896] (+0.000001634) node1 mdcache:mdc_lru_ref: { cpu_id = 0 }, { function = "mdcache_get", line = 178, obj_handle = 0x7F3C5607C038, sub_handle = 0x7F3C5602E218, refcnt = 3 }
[06:25:18.755458247] (+0.000001351) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755459024] (+0.000000777) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755460244] (+0.000001220) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607C038, sub_handle = 0x7F3C5602E218, refcnt = 2 }
[06:25:18.755464261] (+0.000004017) node1 mdcache:mdc_readdir_cb: { cpu_id = 0 }, { function = "mdcache_readdir_chunked", line = 3312, dirent_name = "file1", obj_handle = 0x7F3C5607C038, sub_handle = 0x7F3C5602E218, refcnt = 2 }
[06:25:18.755474774] (+0.000010513) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755475471] (+0.000000697) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DA00 }
[06:25:18.755476089] (+0.000000618) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607C038, sub_handle = 0x7F3C5602E218, refcnt = 1 }
[06:25:18.755477375] (+0.000001286) node1 mdcache:mdc_lru_ref: { cpu_id = 0 }, { function = "mdcache_get", line = 178, obj_handle = 0x7F3C5607C538, sub_handle = 0x7F3C5602E398, refcnt = 3 }
[06:25:18.755478153] (+0.000000778) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DCA0 }
[06:25:18.755478796] (+0.000000643) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DCA0 }
[06:25:18.755479434] (+0.000000638) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607C538, sub_handle = 0x7F3C5602E398, refcnt = 2 }
[06:25:18.755480423] (+0.000000989) node1 mdcache:mdc_readdir_cb: { cpu_id = 0 }, { function = "mdcache_readdir_chunked", line = 3312, dirent_name = "file2", obj_handle = 0x7F3C5607C538, sub_handle = 0x7F3C5602E398, refcnt = 2 }
[06:25:18.755482877] (+0.000002454) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DCA0 }
[06:25:18.755483602] (+0.000000725) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DCA0 }
[06:25:18.755484255] (+0.000000653) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607C538, sub_handle = 0x7F3C5602E398, refcnt = 1 }
[06:25:18.755485116] (+0.000000861) node1 mdcache:mdc_lru_ref: { cpu_id = 0 }, { function = "mdcache_get", line = 178, obj_handle = 0x7F3C5607CA38, sub_handle = 0x7F3C5602E518, refcnt = 3 }
[06:25:18.755485892] (+0.000000776) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DF40 }
[06:25:18.755486538] (+0.000000646) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DF40 }
[06:25:18.755487120] (+0.000000582) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607CA38, sub_handle = 0x7F3C5602E518, refcnt = 2 }
[06:25:18.755488057] (+0.000000937) node1 mdcache:mdc_readdir_cb: { cpu_id = 0 }, { function = "mdcache_readdir_chunked", line = 3312, dirent_name = "file3", obj_handle = 0x7F3C5607CA38, sub_handle = 0x7F3C5602E518, refcnt = 2 }
[06:25:18.755490504] (+0.000002447) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0DF40 }
[06:25:18.755491255] (+0.000000751) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0DF40 }
[06:25:18.755491923] (+0.000000668) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607CA38, sub_handle = 0x7F3C5602E518, refcnt = 1 }
[06:25:18.755492774] (+0.000000851) node1 mdcache:mdc_lru_ref: { cpu_id = 0 }, { function = "mdcache_get", line = 178, obj_handle = 0x7F3C5607CF38, sub_handle = 0x7F3C5602E698, refcnt = 3 }
[06:25:18.755493540] (+0.000000766) node1 mdcache:qlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2044, qlane = 0x7F3C7CB0E1E0 }
[06:25:18.755494178] (+0.000000638) node1 mdcache:qunlock: { cpu_id = 0 }, { function = "_mdcache_lru_unref", line = 2051, qlane = 0x7F3C7CB0E1E0 }
[06:25:18.755494728] (+0.000000550) node1 mdcache:mdc_lru_unref: { cpu_id = 0 }, { function = "mdcache_put", line = 199, obj_handle = 0x7F3C5607CF38, sub_handle = 0x7F3C5602E698, refcnt = 2 }
[06:25:18.755495744] (+0.000001016) node1 mdcache:mdc_readdir_cb: { cpu_id = 0 }, { function = "mdcache_readdir_chunked", line = 3312, dirent_name = "file4", obj_handle = 0x7F3C5607CF38, sub_handle = 0x7F3C5602E698, refcnt = 2 }

**Comment by ffilz** [comment] 2022-01-04 17:21
Yea, there is always a callback for each entry.

One question is how many entries is Ganesha returning to the client in each response? We have another issue where a client is requesting a huge response and Ganesha is obliging, returning thousands of entries in one response, causing a lot of latency.

**Comment by syspro4** [comment] 2022-01-04 20:01
NFS client is sending 32k size buffer and Ganesha is filling up entire 32k. In this 32k, it is returning 137 entries. 

Regarding the callback, can we reduce the callback for each entry and process all entires in single callback?

**Comment by dang** [comment] 2022-01-05 13:42
137 entries shouldn't cause a problem, that's small enough.  Processing multiple entries in a callaback shouldn't make a difference.  function call latency isn't that high, and 137 is a tiny number for function call latency to even show up as a factor.  Something else must be dominating the time.

**Comment by ffilz** [comment] 2023-01-24 17:23
This issue is over a year old. Closing as unresolved.

Note that V4.3 has been tagged which may help.

**Closed as completed by ffilz** 2023-01-24 17:23 UTC
Labels: Analyzing, Need Info
