### ISSUE TITLE
nfs client(linux kernel) IO error

### ISSUE THREAD

**Issue by zhengfeihu51** [nfs-ganesha/nfs-ganesha#910] opened 2023-03-02 11:22 UTC
During file read/write test, the nfs client or server is disconnected from the network. The nfs client reports error -5, which corresponds to an I/O error. The protocol of the nfs client is 4.2. During the network disconnection test, the network is disconnected every 10 seconds and the network is restored every 10 seconds. After a period of time (tens of minutes to several hours), the nfs client (linux kernel) reports an error of -5, , which results in service interruption. Is this behavior normal?

[messages_io_err.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/10870974/messages_io_err.txt)

**Comment by dang** [comment] 2023-03-02 15:46
I suspect this cannot work.  The default Grace period is 90 seconds, so flapping the network every 10 seconds will never allow the grace period to expire, and therefore the client will never reconnect properly.  If you want to survive flapping the network every 10 seconds, you will need to adjust Grace_Period and Lease_Lifetime.  However, setting those low enough will potentially cause unexpected timeouts, depending on your network and load.

In general, an NFS server cannot survive flapping the network every 10 seconds.

**Comment by ffilz** [comment] 2023-03-02 15:51
This is certainly extreme yanking back and forth. A 10 second disconnect would not cause lease expiry by itself, though if the timing is bad, maybe the client doesn't manage to renew its lease so that might be one source of an issue. This situation should never result in the client trying to reclaim state since the server has never actually gone down (so clientids and stateids are all still valid baring lease expiry).

Enabling some debug in Ganesha would help. And maybe a tcp dump to understand how this shows up on the wire. What does the server send the client that triggers EIO.

**Comment by zhengfeihu51** [comment] 2023-03-03 02:06
> This is certainly extreme yanking back and forth. A 10 second disconnect would not cause lease expiry by itself, though if the timing is bad, maybe the client doesn't manage to renew its lease so that might be one source of an issue. This situation should never result in the client trying to reclaim state since the server has never actually gone down (so clientids and stateids are all still valid baring lease expiry).
> 
> Enabling some debug in Ganesha would help. And maybe a tcp dump to understand how this shows up on the wire. What does the server send the client that triggers EIO.



> This is certainly extreme yanking back and forth. A 10 second disconnect would not cause lease expiry by itself, though if the timing is bad, maybe the client doesn't manage to renew its lease so that might be one source of an issue. This situation should never result in the client trying to reclaim state since the server has never actually gone down (so clientids and stateids are all still valid baring lease expiry).
> 
> Enabling some debug in Ganesha would help. And maybe a tcp dump to understand how this shows up on the wire. What does the server send the client that triggers EIO.

The ganesha server has a Grace_Period value of 30 and a Lease_Lifetime value of 10. The tool for this test is vdbench. The server will not fail during the test and may not be related to grace. The purpose of our test is to simulate repeated heartbeat timeout and whether the nfs service will be interrupted. vdbench is normal for a long period of test, but the IOPS will periodically drop 0 and exit abnormally after a period of time. In addition, when the client reports an EIO error, it receives a response from the server expire_session in the client log. The EIO error may be related to this error, but there are other combination conditions, which have not been analyzed clearly.

**Comment by Haroldll** [comment] 2023-03-13 13:54
I'm having the same issue too.
When the NFS client lease expires, in the following request, nfs-ganesha replies the error code(NFS4ERR_EXPIRED) to the client.
When the client receives this error code, the EIO will be returned directly to the upper-level application.

I see this issue at Red Hat:
https://access.redhat.com/solutions/1179643

----------By default, the NFS client does not attempt to reclaim locks which were lost due to a lease expiration event, and an application is notified via EIO errors on system calls such as write. The module parameter 'recover_lost_locks' can be used to change the behavior if desired. Enabling 'recover_lost_locks' may cause data corruption.

Therefore, for the NFS server, replying to this error code should be normal behavior, although it will cause the client to return EIO. Is that so?
Also, from the server side, is there any way to avoid this problem?
@dang @ffilz

**Comment by ffilz** [comment] 2023-03-13 23:33
@Haroldll Yea, I think this is expected behavior. I would like to understand if there is an EIO that is related to anything other than expired lease.

**Comment by Haroldll** [comment] 2023-03-14 14:24
> @Haroldll Yea, I think this is expected behavior. I would like to understand if there is an EIO that is related to anything other than expired lease.
I don't see any other EIO.
This EIO doesn't come up very often, as NFS-GANESHA generally replies NFS4ERR_BADSESSION, not NFS4ERR_EXPIRED.
After the client receives the NFS4ERR_BADSESSION, it is processed normally and no EIO occurs.

**Comment by Haroldll** [comment] 2023-03-15 14:19
nfs-ganesha checks whether the client lease expires every 5 seconds, there are two scenarios in this way：
1. when lease time is up, reaper_run also detects that lease has expired.
2. It's time for lease, but reaper_run hasn't detected lease yet. For example, lease is 90 seconds, but it takes 93 to detect it.

For the second case, if the client is recovered at 91, nfs-ganesha receives the op(sequence), will reply  NFS4ERR_EXPIRED. 
The client will think that the lease has expired and the lock has been released, but in fact, the lock will not be released.
After receiving this sequence, the lease time will be reset, and reaper_run will not detect that the client lease has expired.

So is this a problem? 
In this case, is NFS4ERR_EXPIRED necessary? @ffilz

**Comment by ffilz** [comment] 2023-03-15 20:27
@Haroldll Do you have a simple re-create for this? I don't see any case where we can return NFS4ERR_EXPIRED and reset cid_last_renew. I'd like to turn on some debug and recreate.

**Comment by Haroldll** [comment] 2023-03-16 10:31
@ffilz Sorry, I said something wrong.
The NFS4ERR_EXPIRED is returned when the nfs4_op_sequence is processed. see:
```
enum nfs_req_result nfs4_op_sequence(struct nfs_argop4 *op,
	if (!reserve_lease(session->clientid_record)) {
		PTHREAD_MUTEX_unlock(&session->clientid_record->cid_mutex);

		dec_session_ref(session);
		res_SEQUENCE4->sr_status = NFS4ERR_EXPIRED;

```
However cid_last_renew it is reset when the create_session is received, see:
 ```
   enum nfs_req_result nfs4_op_create_session(struct nfs_argop4 *op,
	/* Bump the lease timer */
	conf->cid_last_renew = time(NULL);

```
So this process, lease does not do expired processing. When the create_session is received, the reaper_run has not detected the expiration.
Because of NFS4ERR_EXPIRED, NFS clients will think that the locks they hold have been released, but it was not released by nfs-ganesha.

**Comment by ffilz** [comment] 2023-03-16 14:45
Ah, OK, so sequence is:

Clients start sessoion
Clients get disconnected so lease expires
Client connects again and does a SEQUENCE operation between the expiry time and the reaper thread acting
Client gets NSF4ERR_EXPIRED
Client does EXCHANGE_ID to re-establish session, this resets lease
reaper thread fires, but clientid is no longer expired

Hmm... I think your right, we do need to expire the state immediately

**Comment by Haroldll** [comment] 2023-03-17 12:41
@ffilz  Yes, it is so.
In addition to  expire the state immediately, whether the sequence can be processed normally? It's like lease doesn't expire.
After all, there is no real  expire  state. Give the client an additional lease period.

**Comment by ffilz** [comment] 2023-03-27 23:44
OK, try this fix:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/551789

**Comment by ffilz** [comment] 2023-04-21 23:01
V5.0 has been released. Closing.

**Closed as completed by ffilz** 2023-04-21 23:01 UTC
Labels: Bug, Needs-Verification, Patch Submitted
