### ISSUE TITLE
nfs-ganesha + cephfs crash while mutil mount point

### ISSUE THREAD

**Issue by ducpx** [nfs-ganesha/nfs-ganesha#388] opened 2019-01-04 03:23 UTC
Hi guys, I config nfs-ganesha 2.7 with ceph mimic. When I have 2 mount point to benchmark, nfs-ganesha crashed. I got backtrace in file: 
[gdb-nfs-ganesha.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/2725947/gdb-nfs-ganesha.txt)
I want to know about the problem. Thanks!

**Comment by dang** [comment] 2019-01-07 14:56
Unfortunately, that backtrace doesn't have useful information in it.  Frequently, when attaching to a process, the useful thread isn't being followed by gdb.
Is this reproducible?  If so, can you use this command in gdb next time:

thread apply all backtrace

That will get the backtraces of all the threads in Ganesha, so we can find the proper one and see it's state.

**Comment by ffilz** [comment] 2020-06-16 17:50
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed by ffilz** 2020-06-16 17:50 UTC
