### ISSUE TITLE
"git clone" does not work on NFSv4 mounts

### ISSUE THREAD

**Issue by bjorn-fischer** [nfs-ganesha/nfs-ganesha#577] opened 2020-05-13 13:54 UTC
We experience problems with git(1) terminating with EACCESS during `git clone` on an NFSv4 mount. Server is ganesha with FSAL_CEPH, grace and delegations deactivated. Client side is vanilla Linux 5.x. Using strace(1) I was able to distill this small test case. Running this on a Linux NFSv4 client against a ganesha server will fail on the 2nd `open()`.

Tested on **3.2** and **next** branches.

```#include <stdio.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

#define TESTFILE "foobar"

int main(int argc, char *argv[]) {

    int fd = open(TESTFILE, O_RDWR | O_CREAT | O_EXCL, 0444);
    if (fd < 0) {
        perror("Could not open file");
        return -1;
    }

    ssize_t res = write(fd, "foobar\n", 7);

    int another_fd = open(TESTFILE, O_RDONLY);
    if (another_fd < 0) {
        perror("Could not open file again");
        return -1;
    }

    return 0;
}
```

**Comment by ffilz** [comment] 2020-05-13 18:44
Could you enable some debug in Ganesha just to rule out Ganesha? It could be a Cephfs issue.

Try adding this to your config:

LOG
{
    COMPONENTS
    {
        NFSPROTO=FULL_DEBUG;
        NFS_V4=FULL_DEBUG;
        FSAL=FULL_DEBUG;
        EXPORT=FULL_DEBUG;
        NFS_V4_ACL=FULL_DEBUG;
    }
 
}

**Comment by bjorn-fischer** [comment] 2020-05-14 08:29
It seems to happen in `ceph_open_my_fd()`.

My sample code is running fine on a native CephFS mount on the very same machine ganesha is running on, so CephFS was not on my radar. Maybe I should dig into libcephfs.so...

```
update_share_counters :FSAL :F_DBG :share counter: access_read 1, access_write 1, deny_read 0, deny_write 0, deny_write_v4 0
ceph_open_my_fd :FSAL :F_DBG :my_fd = 0x7fd1601efd80 my_fd->fd = (nil) openflags = 3, posix_flags = 2
ceph_open_my_fd :FSAL :F_DBG :openflags = 3, posix_flags = 2
ceph_open_my_fd :FSAL :F_DBG :open failed with Permission denied
```

[ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/4626861/ganesha.log)

**Comment by bjorn-fischer** [comment] 2020-05-14 09:16
`ceph_open_my_fd()` is called with `openflags = 3` which is...
```
typedef uint16_t fsal_openflags_t;

#define FSAL_O_CLOSED     0x0000  /* Closed */
#define FSAL_O_READ       0x0001  /* read */
#define FSAL_O_WRITE      0x0002  /* write */
```
... not ok, and `ceph_ll_open()` resulting in `EACCESS` is perfectly valid. The second `open()` in my sample code is `O_RDONLY`. So where does the write flag come from?

**Comment by bjorn-fischer** [comment] 2020-05-14 10:51
Got it! I am not entirely sure about the overall correctness of my "fix", but this change works for my special case, at least:

```
diff --git a/src/Protocols/NFS/nfs4_op_open.c b/src/Protocols/NFS/nfs4_op_open.c
index 5f4444a00..5b8e8565a 100644
--- a/src/Protocols/NFS/nfs4_op_open.c
+++ b/src/Protocols/NFS/nfs4_op_open.c
@@ -1003,7 +1003,7 @@ static void open4_ex(OPEN4args *arg,
                LogFullDebug(COMPONENT_STATE, "Calling reopen2");
 
                status = fsal_reopen2(file_obj, *file_state,
-                                     openflags | old_openflags,
+                                     openflags,
                                      false);
 
                if (FSAL_IS_ERROR(status)) {
```

**Comment by bjorn-fischer** [comment] 2020-05-14 11:29
As I suspected, the "fix" is not correct. The 2nd open() of my test case succeeds but the file is empty. The string "foobar\n" should have been written to it.
But the problem is somewhere in the reopen code. The code assumes that a reopen always _upgrades_ the permission flags, which does not seem to be valid.

We only should reopen if we actually do upgrade:
```
diff --git a/src/Protocols/NFS/nfs4_op_open.c b/src/Protocols/NFS/nfs4_op_open.c
index 5f4444a00..13b62e4c0 100644
--- a/src/Protocols/NFS/nfs4_op_open.c
+++ b/src/Protocols/NFS/nfs4_op_open.c
@@ -999,6 +999,9 @@ static void open4_ex(OPEN4args *arg,
                old_openflags =
                        file_obj->obj_ops->status2(file_obj, *file_state);
 
+               /* Only reopen on upgrade */
+               if (~old_openflags & openflags) {
+
                        /* Open upgrade */
                        LogFullDebug(COMPONENT_STATE, "Calling reopen2");
 
@@ -1014,6 +1017,7 @@ static void open4_ex(OPEN4args *arg,
                        /* We need an extra reference below. */
                        file_obj->obj_ops->get_ref(file_obj);
                }
+       }
 
        if (file_obj == NULL) {
                /* We have a new cache inode entry, take the state lock. */
```

**Comment by ffilz** [comment] 2020-05-14 15:15
Ok, I think that works. Could you submit a gerrithub patch? Also, please run the pynfs 4.0 and 4.1 tests to make sure it doesn't have an unexpected consequence.

**Comment by bjorn-fischer** [comment] 2020-05-15 11:33
Finally got it to gerrithub. This was my first time using gerrithub, so please forgive my any inaccuracies.

Please can you point me to some documentation on how to perform the pynfs tests?

**Comment by dang** [comment] 2020-05-15 13:35
pynfs doesn't seem to be well documented... Basically, clone it, run it's setup.py, then go into each of nfs4.0 and nfs4.1 and run:

./testserver.py --maketree <ganeshahost>:/<exported-path>  all ganesha

**Comment by ffilz** [comment] 2020-05-15 14:14
Specifically the pynfs repo is git://linux-nfs.org/~bfields/pynfs.git

**Comment by ffilz** [comment] 2020-05-29 22:11
The patch caused a regression in pynfs, we need to revisit it.

**Comment by bjorn-fischer** [comment] 2020-06-02 08:47
Sorry for the delay. I was on short leave w/o usable internet connection.

There are actually **DENY** flags for NFSv4 that work the other way round. We need to mask FSAL_O_RDWR and (FSAL_O_DENY_READ | FSAL_O_DENY_WRITE | FSAL_O_DENY_WRITE_MAND) separately and invert the test for the latter. That solves the pynfs regression...

...but the problem is even worse. This test case will lock up the entire client-side NFS stack (Linux, that is, Solaris is not affected) with the patch applied. I'm definitively missing something for the not-reopen code path. We probably need to duplicate the NFS side file handle w/o reopening the FSAL side one. I will dig deeper into this.
```
#include <stdio.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>

#define TESTFILE "foobar"
#define MAX 3

int main(int argc, char *argv[]) {

    unlink(TESTFILE);

    int fd = open(TESTFILE, O_RDWR | O_CREAT, 0666);
    if (fd < 0) {
        perror("Could not open file");
        return -1;
    }

    ssize_t res = write(fd, "foobar\n", 7);
    printf("write() returned %ld\n", res);
    fflush(stderr);

    int fds[MAX], i;

    for (i = 0; i < MAX; i++) {
        fds[i] = open(TESTFILE, O_RDONLY);
        if (fds[i] < 0) {
            fprintf(stderr, "%d: Could not open file: %s\n", i + 1, strerror(errno));
            fflush(stderr);
            return -1;
        }
        fprintf(stderr, "open() returned %d\n", fds[i]);
        fflush(stderr);
    }

    close(fd);

    return 0;
}
```

**Comment by bjorn-fischer** [comment] 2020-06-02 11:28
This version actually works for my test cases and it works for **git clone**. Posted as a code fragment since the diff is pretty much illegible.

**EDIT:** I was not aware that fhe FSAL_O_DENY_* flags are mapped from OPEN4_SHARE_DENY_* flags for NFSv4 share reservations. Here is an updated version of my patch:
```
                old_openflags =
                        file_obj->obj_ops->status2(file_obj, *file_state);

                /* Only reopen on actual upgrade */
                if (~old_openflags & openflags & FSAL_O_OPENFLAGS) {
                        /* Open upgrade */
                        LogFullDebug(COMPONENT_STATE, "Calling reopen2");

                        status = fsal_reopen2(file_obj, *file_state,
                                              openflags | old_openflags,
                                              false);

                        if (FSAL_IS_ERROR(status)) {
                                res_OPEN4->status = nfs4_Errno_status(status);
                                goto out;
                        }

                }

                /* We need an extra reference below. */
                file_obj->obj_ops->get_ref(file_obj);
```

**Comment by bjorn-fischer** [comment] 2020-06-02 13:09
Unfortunately I could not get the 4.0 tests running, but the 4.1 tests look promising. Only some tests unrelated to the problem have failed: [pynfs-4.1-output.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/4717307/pynfs-4.1-output.txt)

**Comment by ffilz** [comment] 2020-07-31 21:48
Could you take another look at this?

**Comment by bjorn-fischer** [comment] 2020-08-03 12:26
Last time I checked, [this code](https://github.com/nfs-ganesha/nfs-ganesha/issues/577#issuecomment-637477514) seems to fix the _pynfs_ regression. Currently I'm trying to test it with lastest commit **c25f26f**, but this version hangs completely on v4 mounts on my test systems (tried FSAL_CEPH and FSAL_MEM). Still trying...
**Update:** Tried a complete fresh test setup, vanilla up-to-date Ubuntu 18.04. I simply cannot get **c25f26f** serving v4 mounts even using FSAL_VFS and FSAL_MEM. On the wire I can see session creation but no answer to PUTROOTFH/GETATTR.
I built with:
```
cmake ../../src/nfs-ganesha/src \
    -DCMAKE_INSTALL_RPATH=/opt/ganesha/lib\;/opt/ganesha/lib/ganesha \
    -DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_GLUSTER=OFF \
    -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_XFS=OFF -DUSE_FSAL_PANFS=OFF \
    -DUSE_FSAL_RGW=OFF -DCMAKE_INSTALL_PREFIX=/opt/ganesha -DUSE_GSS=OFF
```
[ganesha.conf](https://github.com/nfs-ganesha/nfs-ganesha/files/5021155/ganesha.conf.txt)

**Update 2:** I could not find the problem, so I started a bisecting session. For me it broke on _June 5th_ with the _NFSv3 ACLs_ and _NTIRPC_ pullup, which makes **V4-dev.19** the last version that worked for me.

So, should I check [my code](https://github.com/nfs-ganesha/nfs-ganesha/issues/577#issuecomment-637477514) with V4-dev.19 or should I wait until the issues with the new RPC code are resolved?

**Comment by ffilz** [comment] 2020-08-05 21:01
Hmm, we need to understand what broke. What client are you using? Any special mount options?

I run pynfs 4.0 and 4.1 on every weeks merge. I have also done actual client mounts on patch sets submitted after V4-dev.19 so I don't think there's a general issue.

**Comment by bjorn-fischer** [comment] 2020-08-05 21:51
No mount options at all. Tried Ubuntu 18.04 and Solaris as clients, behaviour is the same. The Servers are Ubuntu 18.04 bare metal, and Ubuntu 18.04 as a privileged container. I use *sec=sys* and *-DUSE_GSS=OFF*, maybe that's uncommon. I also tried to disable *NFSv3 ACLs* as a cmake option, no change either. Everything points to the new NTIRPC. On the wire, there is no answer to the initial PUTROOTFH/GETATTR compound, right after session creation. An attached gdb says all threads are waiting, when this occurs.
What is your setup you run pynfs against?

**Comment by sparktown** [comment] 2020-11-03 13:42
Any update on this issue? We are exporting home directories from cephfs using ganesha and run in the same problem. If i can provide any information which helps to resolve this issue, i would be happy to.

**Comment by ffilz** [comment] 2020-11-09 19:07
> **Update 2:** I could not find the problem, so I started a bisecting session. For me it broke on _June 5th_ with the _NFSv3 ACLs_ and _NTIRPC_ pullup, which makes **V4-dev.19** the last version that worked for me.
> 
> So, should I check [my code](https://github.com/nfs-ganesha/nfs-ganesha/issues/577#issuecomment-637477514) with V4-dev.19 or should I wait until the issues with the new RPC code are resolved?

If you bisect to specific patches, is it the NFSv3 ACLs that fails or once the ntirpc pullup is included that it fails?

Have you tried again on a more recent build?

I run pynfs against FSAL_VFS exporting an EXT4 file system with AUTHSYS. GSS is enabled but not used.

**Comment by bjorn-fischer** [comment] 2020-11-10 10:15
Just tried V4-dev.41-0-ga7c6c03f8 and it seems to work.

Testing the latest version of my patch now -- I'll report as soon as I have results.

BTW: The last bisecting session was on late September and it pointed to "e6baef3e3 Split state_lock into st_lock and jct_lock".

**Comment by ffilz** [comment] 2020-11-10 18:59
> 
> 
> Just tried V4-dev.41-0-ga7c6c03f8 and it seems to work.
> 
> Testing the latest version of my patch now -- I'll report as soon as I have results.
> 
> BTW: The last bisecting session was on late September and it pointed to "e6baef3e3 Split state_lock into st_lock and jct_lock".

Ah, there was some issues with the split lock. I think they have now been fixed, so hopefully this issue can soon be closed as resolved.

**Comment by bjorn-fischer** [comment] 2020-11-11 10:30
Thank you for pointing me the right direction with the Needs-Verification label. You are right, the original problem with `git clone` was resolved in _fsal_helper.c_ with commit 1cd4ea3: "Use owner_skip for access checks for open reclaims".

My patch 61c83b2 is not needed anymore and as it creates some regressions it should be backed out.

So please, revert the change and this issue can be closed.

**Comment by ffilz** [comment] 2020-11-11 15:13
So we can go ahead and merge the following?

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/494573

I have rebased it and removed "for discussion" from the patch title so it's open for new review. Please test and also put a Verify +1 if it definitely resolves your issue.

**Comment by bjorn-fischer** [comment] 2020-11-11 21:01
My enthusiasm was a bit early. The issue is resolved when running `git clone` as root on the client (with squash=none). It still fails as an unprivileged user. Does this point to a problem in the Linux client?

Tomorrow I have reserved some time for looking into this.

**Comment by ffilz** [comment] 2020-11-11 21:27
Yea, let's figure out what is failing with a non-privileged user.

**Comment by bjorn-fischer** [comment] 2020-11-12 12:19
Unfortunately the problem goes deeper:

The call stack for `fsal_reopen2()` has architectural differences for the FSALs I looked into. For FSAL_VFS and FSAL_MEM there are no credentials from `op_ctx->creds` involved -- or at least I do not see any involvement:

```
mem_reopen2()
  mem_open_my_fd()
    mem_open_my_fd() <- no creds involved

vfs_reopen2()
  vfs_open_my_fd()
    vfs_fsal_open(struct vfs_fsal_obj_handle)
      vfs_open_by_handle(hdl->obj_handle.fs->private_data, hdl->handle)
        open_by_handle_at() <- no creds involved
```

The `EPERM` problem with `git clone` does not occur using these FSALs.

Now for FSAL_CEPH, the callstack does not use any open-by-handle strategy, but uses `ceph_ll_open()` just like opening a file for the first time. This clearly involves `op_ctx->creds` and causes `git clone` to fail for anyone but root.

```
ceph_fsal_reopen2()
  ceph_open_my_fd()
    fsal_ceph_ll_open(..., &op_ctx->creds)
      ceph_ll_open(..., user_cred2ceph(creds))
```

So, my suggestion is still valid and the patch should be backed out. The proper fix would be to circumvent `fsal_ceph_ll_open()` for the reopen2 code path, or calling `fsal_ceph_ll_open()` with root credentials in that case.

**Comment by ffilz** [comment] 2020-11-12 15:23
The problem is I'm pretty sure the callers of fsal_reopen2() are expecting a permission check.

But maybe they aren't if FSAL_VFS and FSAL_MEM don't do a permission check...

**Comment by ffilz** [comment] 2020-11-12 15:25
Ah, wait, fsal_reopen2 does a permission check...

So yea, I think we can use root credentials ok in FSAL_CEPH. We should check all the other FSALs...

Also, since fsal_reopen2 has a flag to skip permission check, I think that one direct call to obj_ops->reopen2 in nfs4_op_open.c could be changed to a call to fsal_reopen2 and make for a cleaner use of the API

**Comment by bjorn-fischer** [comment] 2020-11-12 15:33
There's a comment at `ceph_fsal_reopen2()` that makes me uncomfortable using root credentials unconditionally in that path:

```
/**
 * @brief Re-open a file that may be already opened
 *
 * This function supports changing the access mode of a share reservation and
 * thus should only be called with a share state. The st_lock must be held.
 *
 * This MAY be used to open a file the first time if there is no need for
 * open by name or create semantics. One example would be 9P lopen.
 *
```
When introducing root credentials in `ceph_fsal_reopen2()` it should be guaranteed that the root credentials are never used for opening a file the first time.

**Comment by ffilz** [comment] 2020-11-12 19:33
Ok, here's some relevant bits gleamed with: tools/findlog.sh -f '.*reopen2'

./include/fsal.h:348: fsal_status_t fsal_reopen2(struct fsal_obj_handle *obj, struct state_t *state, fsal_openflags_t openflags, bool check_permission);

./Protocols/9P/9p_lopen.c:89: fsal_status = fsal_reopen2(pfid->pentry, pfid->state, openflags, true);
./Protocols/NFS/nfs4_op_open.c:1007: status = fsal_reopen2(file_obj, *file_state, openflags | old_openflags, false);
./Protocols/NFS/nfs4_op_open.c:1097: status = file_obj->obj_ops->reopen2(file_obj, *file_state, old_openflags);
./Protocols/NFS/nfs4_op_open_downgrade.c:269: fsal_status = fsal_reopen2(data->current_obj, state, openflags, true);
./SAL/state_share.c:268: fsal_status = fsal_reopen2(obj, state, openflags, false);

The call in nfs4_op_open.c:1097 could be re-written:

./Protocols/NFS/nfs4_op_open.c:1097: status = fsal_reopen2(file_obj, *file_state, old_openflags, false);

Note that 9P uses true, so it won't be bypassing permission checking, it's just done in fsal_helper.c

Also the actual OPEN_DOWNGRADE operation does permission checking.

So I think it is genuinely safe to not do permission checking in the FSAL.

**Comment by bjorn-fischer** [comment] 2020-11-12 19:58
No permission checking for the reopen2 code path, not in general, I assume.

So `ceph_open_my_fd()` should get an additional flag to call `fsal_ceph_ll_open()` optionally with root credentials instead of `&op_ctx->creds`, which then can be used by `ceph_fsal_reopen2()`.

**Comment by ffilz** [comment] 2020-11-12 21:14
Yea, that sounds reasonable.

**Comment by bjorn-fischer** [comment] 2020-11-13 10:46
Ok, now it looks like this:
```
diff --git a/src/FSAL/FSAL_CEPH/handle.c b/src/FSAL/FSAL_CEPH/handle.c
index 7282a3ddb..cfb7b5f1d 100644
--- a/src/FSAL/FSAL_CEPH/handle.c
+++ b/src/FSAL/FSAL_CEPH/handle.c
@@ -51,6 +51,9 @@
 #include "gsh_lttng/fsal_ceph.h"
 #endif
 
+#define CEPH_AS_CALLER 0
+#define CEPH_AS_ROOT   1
+
 /**
  * @brief Release an object
  *
@@ -859,21 +862,34 @@ static fsal_status_t ceph_fsal_unlink(struct fsal_obj_handle *dir_pub,
  * @param[in] openflags   Mode for open
  * @param[in] posix_flags POSIX open flags for open
  * @param[in] my_fd       The ceph_fd to open
+ * @param[in] priv        CEPH_AS_CALLER or CEPH_AS_ROOT
  *
  * @return FSAL status.
  */
 
 static fsal_status_t ceph_open_my_fd(struct ceph_handle *myself,
 				     fsal_openflags_t openflags,
-				     int posix_flags, struct ceph_fd *my_fd)
+				     int posix_flags,
+				     struct ceph_fd *my_fd, int priv)
 {
 	int rc;
 	struct ceph_export *export =
 		container_of(op_ctx->fsal_export, struct ceph_export, export);
+	struct user_cred root_creds = {
+		.caller_uid = 0,
+		.caller_gid = 0,
+		.caller_glen = 0,
+		.caller_garray = NULL
+	};
+	struct user_cred *creds = &op_ctx->creds;
+
+	if (priv == CEPH_AS_ROOT) {
+		creds = &root_creds;
+	}
 
 	LogFullDebug(COMPONENT_FSAL,
-		     "my_fd = %p my_fd->fd = %p openflags = %x, posix_flags = %x",
-		     my_fd, my_fd->fd, openflags, posix_flags);
+		     "my_fd = %p my_fd->fd = %p openflags = %x, posix_flags = %x, priv = %d",
+		     my_fd, my_fd->fd, openflags, posix_flags, priv);
 
 	assert(my_fd->fd == NULL
 	       && my_fd->openflags == FSAL_O_CLOSED && openflags != 0);
@@ -883,7 +899,7 @@ static fsal_status_t ceph_open_my_fd(struct ceph_handle *myself,
 		     openflags, posix_flags);
 
 	rc = fsal_ceph_ll_open(export->cmount, myself->i, posix_flags,
-				&my_fd->fd, &op_ctx->creds);
+				&my_fd->fd, creds);
 
 	if (rc < 0) {
 		my_fd->fd = NULL;
@@ -950,7 +966,7 @@ static fsal_status_t ceph_open_func(struct fsal_obj_handle *obj_hdl,
 
 	return ceph_open_my_fd(container_of(obj_hdl,
 		struct ceph_handle, handle), openflags,
-		posix_flags, (struct ceph_fd *)fd);
+		posix_flags, (struct ceph_fd *)fd, CEPH_AS_CALLER);
 }
 
 /**
@@ -1246,7 +1262,8 @@ static fsal_status_t ceph_fsal_open2(struct fsal_obj_handle *obj_hdl,
 		if (my_fd->openflags != FSAL_O_CLOSED) {
 			ceph_close_my_fd(my_fd);
 		}
-		status = ceph_open_my_fd(myself, openflags, posix_flags, my_fd);
+		status = ceph_open_my_fd(myself, openflags, posix_flags,
+					 my_fd, CEPH_AS_CALLER);
 
 		if (FSAL_IS_ERROR(status)) {
 			if (state == NULL) {
@@ -1668,7 +1685,11 @@ static fsal_status_t ceph_fsal_reopen2(struct fsal_obj_handle *obj_hdl,
 
 	PTHREAD_RWLOCK_unlock(&obj_hdl->obj_lock);
 
-	status = ceph_open_my_fd(myself, openflags, posix_flags, my_fd);
+	/* Open the fd with root privileges on reopen. This is safe
+	 * because permission is checked in fsal_helper.c:fsal_reopen2()
+	 */
+	status = ceph_open_my_fd(myself, openflags, posix_flags, my_fd,
+				 CEPH_AS_ROOT);
 
 	if (!FSAL_IS_ERROR(status)) {
 		/* Close the existing file descriptor and copy the new
diff --git a/src/Protocols/NFS/nfs4_op_open.c b/src/Protocols/NFS/nfs4_op_open.c
index 3431bfa9a..661610b9e 100644
--- a/src/Protocols/NFS/nfs4_op_open.c
+++ b/src/Protocols/NFS/nfs4_op_open.c
@@ -999,23 +999,20 @@ static void open4_ex(OPEN4args *arg,
 		old_openflags =
 			file_obj->obj_ops->status2(file_obj, *file_state);
 
-		/* Only reopen on actual upgrade */
-		if (~old_openflags & openflags) {
-			/* Open upgrade */
-			LogFullDebug(COMPONENT_STATE, "Calling reopen2");
+		/* Open upgrade */
+		LogFullDebug(COMPONENT_STATE, "Calling reopen2");
 
-			status = fsal_reopen2(file_obj, *file_state,
-					      openflags | old_openflags,
-					      false);
+		status = fsal_reopen2(file_obj, *file_state,
+				      openflags | old_openflags,
+				      false);
 
-			if (FSAL_IS_ERROR(status)) {
-				res_OPEN4->status = nfs4_Errno_status(status);
-				goto out;
-			}
-
-			/* We need an extra reference below. */
-			file_obj->obj_ops->get_ref(file_obj);
+		if (FSAL_IS_ERROR(status)) {
+			res_OPEN4->status = nfs4_Errno_status(status);
+			goto out;
 		}
+
+		/* We need an extra reference below. */
+		file_obj->obj_ops->get_ref(file_obj);
 	}
 
 	if (file_obj == NULL) {
@@ -1094,9 +1091,7 @@ static void open4_ex(OPEN4args *arg,
 			*new_state = false;
 		} else {
 			/*Do an open downgrade to the old open flags */
-			status = file_obj->obj_ops->reopen2(file_obj,
-							   *file_state,
-							   old_openflags);
+			status = fsal_reopen2(file_obj, *file_state, old_openflags, false);
 			if (FSAL_IS_ERROR(status)) {
 				LogCrit(COMPONENT_NFS_V4,
 					"Failed to allocate handle, reopen2 failed with %s",
```
**pynfs** for NFS4.0 is finished and we could call this a qualified success. Not only the regressed tests from the first approach are gone...
```
OPEN30   st_open.testReplay                                       : PASS
OPEN25   st_open.testDenyWrite1                                   : PASS
OPEN21   st_open.testDenyRead1                                    : PASS
```
... yet two more tests that failed before do now pass:
```
RNM20    st_rename.testLinkRename                                 : PASS
PUTFH3   st_putfh.testStaleHandle                                 : PASS
```
And the original `git clone` issue is no more.

It would be a good idea to include a test for the `git clone` scenario into pynfs...

**Comment by ffilz** [comment] 2020-11-13 23:49
Ok, if that works, submit a patch via Gerrithub.

Thanks

**Comment by ffilz** [comment] 2020-11-13 23:51
And if you tease out the proper sequence to regression test, you can make a pynfs test case and submit that to the linux-nfs mailing list.

**Comment by bjorn-fischer** [comment] 2020-11-21 00:26
> Any update on this issue? We are exporting home directories from cephfs using ganesha and run in the same problem. If i can provide any information which helps to resolve this issue, i would be happy to.

Version V4-dev.43 should have a fix for this. As it would be helpful to have a confirmation that the issue is solved for your setup as well, could you try it out?

**Comment by ffilz** [comment] 2021-03-06 00:05
I'm not sure if this is resolved, but it hasn't seen any action in months so closing.

**Closed as completed by ffilz** 2021-03-06 00:05 UTC
Labels: Bug, Needs-Verification
