### ISSUE TITLE
ganesha(V2.6-stable) cannot receive SM_NOTIFY when nfs3.0 client with ipv6 enabled

### ISSUE THREAD

**Issue by zhoury14** [nfs-ganesha/nfs-ganesha#318] opened 2018-07-25 13:13 UTC
1. client mount with protocol nfs 3.0
`mount -t nfs -o vers=3 10.105.193.23:/dfs001 /mnt/test`
2. client holds a write lock for file /mnt/test/hello
3. reboot client
`echo b > /proc/sysrq-trigger`

According NFS RFC, after a while, the nfs server(ganesha) should receive a SM_NOTIFY request from rpc.statd and release the file lock held by the client. But, in my test, it doesn't work. If you check the file `/var/lib/nfs/statd/sm`, you will find a ipv6 address like `::ffff:10.105.25.226`, which may have some problem?
If I disable ipv6 in ganesha, just set `v6disable=true;` in function nfs_Init_svc. the contents in `/var/lib/nfs/statd/sm` will be a normal ipv4 address `10.105.25.226`. In this case, I redo the step 1-3 mentioned above, after a while, ganesha can receive  SM_NOTIFY request and correctly release file lock held by the reboot client.

**Comment by dang** [comment] 2018-07-25 13:32
4-in-6 addresses should work fine for IPv4.  The client shouldn't even know that the server is listening on on the embedded address at all (and, in fact, this is working for MNT and NFSv3).
Does the client, maybe, have IPv6 disabled?

**Comment by zhoury14** [comment] 2018-07-26 03:12
thanks for your comments! I have checked it, that my client and server all support IPv6 and have IPv6 enabled.
`net.ipv6.conf.lo.disable_ipv6 = 0`
`net.ipv6.conf.default.disable_ipv6 = 0`
`net.ipv6.conf.all.disable_ipv6 = 0`

**Comment by jasonsung1** [comment] 2019-05-08 04:11
Why did I disable ipv6 it does not work in v2.3-stable yet? it is Report error: HASHTABLE_ERROR_NO_SUCH_KEY  when processing sm_notify.

**Comment by malahal** [comment] 2019-05-08 10:38
NFS client should send SM_NOTIFY to rpc.statd and rpc.statd should pass it to Ganesha (NLM service), correct?

**Comment by jasonsung1** [comment] 2019-05-15 07:16
> NFS client should send SM_NOTIFY to rpc.statd and rpc.statd should pass it to Ganesha (NLM service), correct?

yes,But there is some bugs

**Comment by zanglinjie** [comment] 2020-02-08 11:37
yes,But there is some bugs

**Comment by zanglinjie** [comment] 2020-02-08 12:04
Is there any way to solve the above problems?

**Comment by ffilz** [comment] 2020-02-10 18:13
Could you describe the "bugs" you are seeing?

Re-opening so the conversation is more visible

**Comment by zanglinjie** [comment] 2020-02-11 01:42
hi, @ffilz 
1, client mount with protocol nfs 3.0，set v6disable=false，nfs_param.core_param.nsm_use_caller_name=true；
when client add a write lock for file，some error like this：
get_nsm_client-->nsm_monitor-->clnt_call“Can not monitor z07 SM_MON ret ...”
“nlm_send_async:failed to resolve z07 to an address:Name or service not known”

which may have some problem?
If you check the file /var/lib/nfs/statd/sm, you will find a client hostname like “z07”.

Now there is a solution：
I set /etc/hosts in nfs server add " ::ffff:188.188.44.7 z07". Adding a file lock works fine.
Is there any other solution？

2,client mount with protocol nfs 3.0，set v6disable=false，nfs_param.core_param.nsm_use_caller_name=false；
client holds a write lock for file  /mnt/test/hello
reboot client
client sent sm-notify, 
The server nlm4_Sm_Notify cannot release the lock resource ,because key.ssc_nlm_caller_name = op_ctx-> client-> hostaddr_str (127.0.0.1)
Causes no state information found and exits;
After nfs_param.core_param.nsm_use_caller_name=true, add lock error, no host name can be found;

**Comment by ffilz** [comment] 2020-02-11 18:05
Oh, crud, we really did break this... Commit 61c2774d7f2a16f37db41207d9768fb64e824c99 is at fault. For sm_notify we obviously can't use op_ctx->client, we need to take the IP address in the sm_notify and try and find the gsh_client that matches that.

Interesting, with that patch get_nsm_client doesn't even use the SVCXPRT *xprt parameter anymore...

I'll have to carve out some time to try and fix this...

**Comment by ntrishal** [comment] 2020-03-18 11:03
Tried the 'Scenario2' mentioned above (Feb 11 comment) with ibm2.7 code stream and did not hit this problem.

We have v6disable=false and nfs_param.core_param.nsm_use_caller_name=false

Wondering what is the exact community version that has this problem? We do seem to have the code related to commit 61c2774 in our code as well.

The request came in from localhost (Request from ::ffff:127.0.0.1)
But the caller name (client which was reboot) was found fine via check_use_caller_name_ipv6() 
The get_gsh_client() code was also invoked as part of the flow.

**Comment by ffilz** [comment] 2020-03-18 15:25
There is a definite problem here, and I do hope to get to fixing it... Unfortunately right now I'm in the middle of export stuff...

**Comment by ffilz** [comment] 2020-07-15 17:28
This is old, but we do need to fix it.

**Comment by ffilz** [comment] 2021-03-09 15:43
Bump...

**Comment by ffilz** [comment] 2021-10-19 17:45
And bump again - maybe something to work on this week...

**Comment by ffilz** [comment] 2021-10-25 15:54
OK, as of 330f79d which is in V2.5.0.4 which is newer than V2,2-dev-22 where 61c2774 was merged, the issue isn't actually the use of op_ctx->client since 330f79d  actually made that not happen anyway. Instead, the issue I think is that client_mgr.c doesn't match IPv4 addresses that are encapsulated in IPv6, which is actually called out in the original problem description.

We have code to match IPv4 addresses encapsulated in IPv6 (we use it for client matching for export permissions)... I will make that code more generic in client_mgr.c.

**Comment by ffilz** [comment] 2021-10-25 15:58
And it looks like the issue is we actually cause rpc.statd to register the IPv6 encapsulated address. I'm going to hazard a guess that we should instead register the unencapsulated IPv4 address...

**Comment by ffilz** [comment] 2021-10-26 22:15
OK, after some major work, I think I have this all working now... There are several patches, but this is HEAD of my branch:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/526274

It can also be found on github:

https://github.com/ffilz/nfs-ganesha/commits/fix4

I still need to test that things all work for nsm_use_caller_name == true.

**Closed** 2021-12-20 20:56 UTC
Labels: bug, Needs-Verification
