### ISSUE TITLE
mdcache_lru can't reuse the mdcache_entry, even over the `Entries_HWMark` and set `Dir_Chunk = 0` and out of memory

### ISSUE THREAD

**Issue by lpstudy** [nfs-ganesha/nfs-ganesha#702] opened 2021-03-31 04:38 UTC
This is our lru_state, we have disabled the cache in ganesha.conf
```
NParts = 1， Cache_Size = 1， Entries_HWMark = 10
Dir_Chunk = 0,
Attr_Expiration_Time = 0
```

**lru_state**
```
$1 = {entries_hiwat = 10, entries_used = 265470, entries_release_size = 100, chunks_hiwat = 100000, chunks_used = 0, fds_system_imposed = 1048576, fds_hard_limit = 1038090, fds_hiwat = 943718, fds_lowat = 524288,
  futility = 0, per_lane_work = 50, biggest_window = 419430, prev_fd_count = 0, prev_time = 1617107507, fd_state = 0}
```

We can see that `chunks_used = 0`, which won't hold the reference for mdcache_entry_t. But `lru_try_reap_entry` always return `NULL` in our case, so always alloc a new entry rather than reusing the refcnt ==2 entries in the lru. The result is `entries_used = 265470`, which is extremely larger than `entries_hiwat = 10`.

**Comment by lpstudy** [comment] 2021-03-31 04:40
We use the ganesha version:
```
V4-dev.18 64f0146c0c30a5fa9b7f34324d9238d7fbfc2624
```

**Comment by dang** [comment] 2021-03-31 12:49
You should *not* use Entries_HWMark = 0 (and, in fact, we should not allow it).  This does not disable the handle cache, as it cannot be disabled.  It's required for proper operation of Ganesha.  

You might want to upgrade to a newer version.  V2-dev.22 added code to make the LRU more aggressive in re-using entries.

**Comment by lpstudy** [comment] 2021-03-31 12:52
@dang I set Entries_HWMark=100, however the entries_used in lru_state is "entries_used = 265470, "
We have cherry-pick the mdcache release fix.

**Comment by dang** [comment] 2021-03-31 13:00
Sure, entries_used can go above your high-water mark, if there's client pressure.  The high-water is not a limit, it's a point at which we start re-using entries. 

There may be a refcount issue here, although I'm not aware of any at the moment.  Debugging refcount bugs is quite a problem, especially in an active system.  Can you try to get a reproducer, maybe? 

(Note that Entries_HWMark=100 will slow things down in general, since it will need to re-create handles for almost every operation).

**Comment by lpstudy** [comment] 2021-03-31 13:02
> Sure, entries_used can go above your high-water mark, if there's client pressure. The high-water is not a limit, it's a point at which we start re-using entries.
> 
> There may be a refcount issue here, although I'm not aware of any at the moment. Debugging refcount bugs is quite a problem, especially in an active system. Can you try to get a reproducer, maybe?
> 
> (Note that Entries_HWMark=100 will slow things down in general, since it will need to re-create handles for almost every operation).

To be honest, I do not know how to reproduce it. It only occurs when our cluster are experiencing a larger workload. During our daily test, we can not produce it.  Maybe you can give some suggestion on how to debug it ?

**Comment by dang** [comment] 2021-04-01 12:42
Debugging refcount bugs is hard.  What I've done in the past is find a workload that reproduces, and then turn on LTTng tracing of refcounts, and runt he workload.  I then have to analyze the traces to find a handle that leaks it's refcount, and find all the uses of that handle in the trace, and figure out where the missing deref is.

Like I said, it's a pain in the butt.  You may be able to run with LTTng enabled; it has fairly small overhead, and writes to a circular buffer, so it won't grow unbounded.  However, that also means that the events we care about may be gone before you realize the issue has triggered.

**Comment by ffilz** [comment] 2021-10-19 17:34
Is this still an issue? We are soon to release Ganesha V4.0 with rc1 this week. If this is something that is still an issue, let's see if we can get a fix.

**Comment by dang** [comment] 2021-10-27 17:21
Code to improve reuse an release more entries above hwmark was merged in V4-dev.22

**Comment by ffilz** [comment] 2021-10-27 18:32
OK, I'm going to mark this as try on supported version, please try on V4-rc1 (or later)

**Comment by ffilz** [comment] 2021-10-27 19:07
Actually going to change this to needs verification

**Closed as completed** 2021-12-20 20:55 UTC
Labels: Needs-Verification, Analyzing
