### ISSUE TITLE
nfs-ganesha server crash

### ISSUE THREAD

**Issue by derekbit** [nfs-ganesha/nfs-ganesha#914] opened 2023-03-09 16:19 UTC
Hello,
We've encountered several nfs-ganesha servers crash cases when clients were connecting to the server in v4.2.2 and v4.2.3.
Any suggestion for helping figure out the root cause? 

```
[ +8.791068] ganesha.nfsd[23271]: segfault at 118 ip 00007f32fa94cbd2 sp 00007f3249edbfb0 error 4 in libganesha_nfsd.so.4.2[7f32fa8bd000+195000]

# addr2line -e /usr/local/lib64/libganesha_nfsd.so.4.2 -fCi 8FBD2
dec_nfs4_state_ref
:?
```

Many thanks.

**Comment by amartel** [comment] 2023-03-09 16:54
It looks like a duplicate of #904
We are waiting for an official fix but, if you have an urgent need, you can apply my workaround in the meantime

**Comment by derekbit** [comment] 2023-03-09 17:02
@amartel 
Thanks for the information. I will try it.

**Comment by ffilz** [comment] 2023-04-21 23:03
V5.0 has been released. Closing.

**Closed as completed by ffilz** 2023-04-21 23:03 UTC
Labels: Duplicate, Needs-Verification, Patch Submitted
