### ISSUE TITLE
Issue with config parameter initialization

### ISSUE THREAD

**Issue by skmprabhu1** [nfs-ganesha/nfs-ganesha#823] opened 2022-06-07 17:30 UTC
Both MDCache and cacheinode uses same structure to read the config file variable. The problem is that the both blocks calling do_block_init(),  hence config value reset to default value and set only config parameter available in that block. We can't use both block at the same time. We need to support both blocks.

**Comment by dang** [comment] 2022-06-07 18:01
Post 4.1, we can remove cacheinode.

**Comment by ffilz** [comment] 2022-06-07 19:03
Yea, but what do we do for 4.x?

I'm tempted to go ahead and remove cacheinode for 4.1 even though it's technically too late. But we either come up with a somewhat complex "fix" that will just be abandoned in V5.0 or we tell people "it's broke, put your config in MDCACHE...).

**Comment by dang** [comment] 2022-06-08 13:15
If it's not working now (I thought I'd tested it when I put it in?) then it's already removed, and we should remove it for 4.1.

**Comment by skmprabhu1** [comment] 2022-06-08 16:14
In upgrade scenario, We just use old config with new ganesha. I feel we should have support for both blocks for some time.

**Comment by dang** [comment] 2022-06-08 16:48
3 years is a long enough time.  If I'd thought of it, I would have removed cacheinode before 4.0.

**Comment by ffilz** [comment] 2022-06-09 00:15
OK, let's take advantage that none of the actively involved Ganesha vendors have picked up V4.x yet and allow some things into V4.1 that we would not normally take in a stable update and let's drop the CACHEINODE block.

I can put together a patch for that.

**Comment by skmprabhu** [comment] 2022-11-18 07:09
The issue is fixed in latest code. This can be closed.

**Closed as completed** 2022-11-18 16:31 UTC
Labels: Bug
