### ISSUE TITLE
[vfs] Stale file handle error, Ganesha version 3.0

### ISSUE THREAD

**Issue by darwinTtito** [nfs-ganesha/nfs-ganesha#538] opened 2020-02-17 20:18 UTC
Hi,

The scenario is the following:
- Ganesha is running in the docker container `c1`.
- Container `c2 `is created to work as a client.
- In container `c1` many volumes are `mounted `(through `fuse.unionfs`) and `exported `dynamically. Also, those volumes are `unexported `and `unmounted `constantly (as shown in the script below).
- When the container `c1` is removed, another one is created automatically, then Ganesha is started and all volumes that were being exported are mounted and exported again.
- As a result, some volumes (exported through Ganesha) mounted by `c2 ` reestablish the connection automatically, but others show the `Stale file handle` error (note that this happens randomly).

```
$ mkdir -p /data
$ mkdir -p /data/1
$ mkdir -p /export/dir2
$ mkdir -p /export/dir1
$ 
$ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data=RW /export/dir1
$ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data/1=RW /export/dir2
$ 
$ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir1)"
$ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir2)"
$ dbus-send --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.RemoveExport uint16:1
$ dbus-send --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.RemoveExport uint16:2
$ 
$ umount /export/dir1
$ umount /export/dir1

$ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data=RW /export/dir1
$ unionfs -o uid=999,gid=999,cow,nonempty,allow_other /data/1=RW /export/dir2
$ 
$ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir1)"
$ dbus-send --system --print-reply --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/vfs.conf string:"EXPORT(Path=/export/dir2)"
```

**Comment by ffilz** [comment] 2020-02-17 20:27
Ok, so you've basically got transient file systems. I think the issue is that the device number for the file systems can change between iterations of the container. From your other issue ( https://github.com/nfs-ganesha/nfs-ganesha/issues/536 ) it looks like blkid is not working with the transient file systems so we can't get a uuid which means we are relying on the device number to create an fsid for the file system. The fsid needs to be part of the handle (which otherwise is essentially an inode number and inode version and maybe a few other bits) so that different file systems have unique handles.

I'm not sure if we can really solve this issue if we can't get a stable fsid for each file system.

**Comment by ffilz** [comment] 2020-02-17 21:12
Another point is that NFS depends on the inode numbers being stable (or the file system at least generates a stable handle - it's possible for a VFS file system to use something other than inode number - though the client side might also be confused if inode number (file id) changes - I have seen confusion happen there also beyond the issues of handles).

**Comment by malahal** [comment] 2020-02-19 04:00
One thing I noticed is that you are removing exports before unmounting file systems. So you will have Ganesha running with exports removed. This will certainly result in ESTALE errors if clients were to send requests in that time frame. You should stop Ganesha (or stop container) without unexporting and unmounting. This will make the NFS clients get timeouts (not ESTALE errors) and they retry provided you did NOT use "soft" mount option.

**Comment by dang** [comment] 2020-02-20 14:40
I also suspect that fuse.unionsfs may not have stable handles across remounts.

**Comment by k-angelo** [comment] 2020-02-26 15:23
Hello all and sorry for the long period of silence.
@malahal We are making sure that at the time of the unexport no clients will be making calls to that export.

@dang @ffilz  fuse.unionfs does not have stable inodes across remounts, that is true. In my experience, clients of kernel NFS can recover in a reasonable time frame. I am not 100% sure how the client works but from a black box view to me it seems that it will invalidate its inode caches, so at least when a client tries to open the file again it will work.  

So we are willing to incur some downtime on clients due to a stale file handle if we are certain that the client will recover. Now I am not gonna lie and say that this works 100% even on kernel NFS but more or less its quite reliable and the unrecoverable cases are rare.

I also have to point out that since we are running on Kubernetes  we have the luxury to restore all exports before reporting our service as ready. So while the server is down it means that packets are dropped and the clients can connect again only if all the exports are restored to their previous state.

**Comment by ffilz** [comment] 2020-02-26 15:34
Not having stable inodes (and thus probably not having stable handles) means that any open files a client has over a restart may be unrecoverable. It is probably true that eventually clients will be able to use lookups for new opens and get the new handle.

Now if directory handles can change, that may be more of an issue.

But if the fsid can't be stable, then there is little that can be done. ALL the clients handles (including the one for the mount) will go bad. Ganesha puts the fsid into the handle so that it can maintain handle uniqueness between file systems (otherwise, all file systems might well have the same handle for the root of the file system). There is nothing we can do about this, using the fsid in the handle is one of the things we did to allow exporting multiple file systems.

**Comment by darwinTtito** [comment] 2020-03-04 14:22
Hi @ffilz, 

just a few last questions:

1. what is the difference between the export option `Filesystem_id` of Ganesha and the `FSID` of the NFS kernel? 
2. Not sure if I caught correctly the code, but basically the `Filesystem_id` is used instead of the major/minor device id, right? 
3. the Filesystem_id is used to build the FSID?
4. set the `fsid_device` option to `false` should not help to build the `FSID` without using the device number?
5. I saw in the log file that each time that we `populate the posix file systems`, each `FS` already contains an `FSID` assigned even when this was not exported. This `FSID` is used to build the handle or a new one is build once the `FS` is exported? _**log file**_: https://paste.ubuntu.com/p/HXh495RhWn/

**Comment by ffilz** [comment] 2020-03-04 19:44
The Filesystem_id is used only to set the fsid field in NFS attributes.

The fsid used inside the FSAL is generated either from the device number or from the UUID of the file system. The fsid_device parameter if true indicates that only the device number is used if we can't get a UUID and the fs_fsid field from statfs is 0.0.

The FSAL fsid is put into the NFS handle so that the layers above (primarily MDCACHE) can differentiate handles from different file systems for the same FSAL.

When scanned, each file system is given an fsid as noted above. When an FSAL claims a POSIX file system, it has the opportunity to re-index the file system with a different fsid which may be done because there won't be room in the NFS handle for a UUID based fsid. XFS also has it's own fsid that it uses. But this new fsid is either based on the uuid or the device number (or it COULD be something the FSAL invents). It has no connection to Filesystem_id.

The Filesystem_id option is problematic since it doesn't allow for an export to have multiple file systems. For example, if your export path is /exports/fs1 and you have the following EXT4 filesystems mounted, FSAL_VFS will export them all (just like knfsd would with nohide/crossmnt):

/export/fs1
/export/fs1/some/path/fs2
/export/fs1/some/other/path/fs3
/export/fs1/some/other/path/fs3/and/another/path/fs4

That is why we do the file system scanning, to find all those sub-mounted/nested file systems that could be exported if we export /export/fs1 (or even /export/fs1/some).

**Comment by ffilz** [comment] 2020-08-13 23:00
With some code changes that should mitigate this, and no action for nearly 30 days, I will close this as resolved.

**Closed as completed by ffilz** 2020-08-13 23:00 UTC
