### ISSUE TITLE
Why use client hostname as the key of client record ?

### ISSUE THREAD

**Issue by liyinshubyte** [nfs-ganesha/nfs-ganesha#753] opened 2021-10-24 04:04 UTC
@ffilz Hi, excuse me, recently I found ganesha use [client hostname](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_exchange_id.c#L217) as the key of client record, but in docker, there maybe exist the same client hostname for different pods, so error maybe happens. Could we use other variable as the key of client record ? which can make sure the uniqueness.

**Comment by ffilz** [comment] 2021-10-26 22:17
Which client record? I'm not sure how well Ganesha is going to work if the same client name refers to multiple actual clients...

**Comment by liyinshubyte** [comment] 2021-10-27 00:48
@ffilz Thanks the reply.

> Which client record?

The client record saved in `ht_client_record`

> I'm not sure how well Ganesha is going to work if the same client name refers to multiple actual clients

The session will be created and deleted infinitely. For example, clientA and clientB use the same hostname. clientA created sessionA1, then clientB created sessionB1 and will delete sessionA1 by [nfs_client_id_expire](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_create_session.c#L444) when clientB found clientid does not [match](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_create_session.c#L430)(i.e. `conf->cid_clientid` belongs to clientA, but `clientid` belongs to clientB). Then clientA send OP_SEQUENCE use sessionA1, but clientA can not found the deleted sessionA1 in ganesha, so clientA create sessionA2, and will also delete sessionB1 by [nfs_client_id_expire](https://github.com/nfs-ganesha/nfs-ganesha/blob/next/src/Protocols/NFS/nfs4_op_create_session.c#L444) when clientA found clientid does not match, and so on, clientA and clientB will delete the other's session infinitely.

**Comment by ffilz** [comment] 2021-10-27 02:20
Because it's called out in section 16.33.5. IMPLEMENTATION of RFC 7530:

To understand how to implement SETCLIENTID, make the following
notations. Let:

x be the value of the client.id subfield of the SETCLIENTID4args structure.

v be the value of the client.verifier subfield of the SETCLIENTID4args structure.

c be the value of the client ID field returned in the SETCLIENTID4resok structure.

k represent the value combination of the callback and callback_ident fields of the SETCLIENTID4args structure.

s be the setclientid_confirm value returned in the SETCLIENTID4resok structure.

{ v, x, c, k, s } be a quintuple for a client record. A client record is confirmed if there has been a SETCLIENTID_CONFIRM operation to confirm it. Otherwise, it is unconfirmed. An unconfirmed record is established by a SETCLIENTID call.

And then this clause:

o The server has previously recorded a confirmed { u, x, c, l, s } record such that v != u, l may or may not equal k, and has not recorded any unconfirmed { *, x, *, *, * } record for x. The server records an unconfirmed { v, x, d, k, t } (d != c, t != s).

The server returns { d, t }.

The server awaits confirmation of { d, k } via SETCLIENTID_CONFIRM { d, t }.

The server does NOT remove client (lock/share/delegation) state for x.

So if the client id field is the same, the server is supposed to identify that as the same client.

There may be something to make the clientid more unique than host name. I'll check into that tomorrow.

**Comment by ffilz** [comment] 2021-10-27 14:16
See this documentation for the Linux client:

https://www.kernel.org/doc/html/latest/admin-guide/nfs/nfs-client.html#the-nfs4-unique-id-parameter

However that doesn't solve the issue for containers (see the bottom of the section)...

This Red Hat Bugzilla sheds some light on the issue:

https://bugzilla.redhat.com/show_bug.cgi?id=1801326

You might also search the linux-nfs mailing list archives to see if the subject is discussed there.

In any case, this is beyond the scope of the nfs-ganesha project to resolve, but I will keep this open for some time for further discussion.

**Comment by ffilz** [comment] 2021-10-27 14:16
Adding wontfix to make it clear there will be no Ganesha code changes for this.

**Comment by liyinshubyte** [comment] 2022-03-05 09:55
@ffilz Hi, use hostname as key of client record,  can help state recovery when client restart. But if we do not care about state recovery, and care more about docker case. Can we use some unique-id generated by ganesha as the key of client, and also pass this unique-id to client. For example, can we use `clientid4` as the key of client record?

```
clientid4 new_clientid(void)
{
	clientid4 newid = atomic_inc_uint32_t(&clientid_counter);
	uint64_t epoch_low = nfs_ServerEpoch & UINT32_MAX;

	return newid + (epoch_low << (clientid4) 32);
}
```

**Comment by ffilz** [comment] 2022-03-07 21:03
Look at this upstream kernel patch and discussion:

https://lore.kernel.org/all/6e05bf321ff50785360e6c339d111db368e7dfda.1644349990.git.bcodding@redhat.com/

I don't know if that is heading towards a resolution for this issue.

**Comment by ffilz** [comment] 2023-01-24 15:47
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.

**Closed as completed by ffilz** 2023-01-24 15:47 UTC
Labels: Wontfix, Analyzing
