### ISSUE TITLE
Concurrent writes produce wrong WCC response?

### ISSUE THREAD

**Issue by artemy-vo** [nfs-ganesha/nfs-ganesha#553] opened 2020-03-09 20:19 UTC
I am testing Ganesha 2.8.3 on top of WekaFS filesystem, and I've experienced presumably wrong WCC results.
The test program randomly writes, reads, truncates and stats file. At some point stat call returned file size below offset that was just written and acked by NFS client.
NFS client is CentOS 7.3, mounted with '-o vers=3' option, Ganesha is running in Ubuntu14-based LXC container and is using VFS FSAL.

Looking at Ganesha logs at the time of failure:

The first write to offset 0xba000, the file size was way below offset being written:

`[svc_192] nfs3_write :NFS3 :DEBUG :REQUEST PROCESSING: Calling nfs_Write handle: File Handle V3: Len=48 430000012a44000000000040000027000006beabf27b0100000000000000005f73746174655f743a7330002390ffff00 start: ba000 len: 1000 FILE_SYNC
[svc_192] fsal_reopen_obj :RW LOCK :F_DBG :Got read lock on 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/commonlib.c:2609
[svc_192] fsal_reopen_obj :FSAL :F_DBG :Open mode = 3, desired mode = 2
[svc_192] find_fd :FSAL :F_DBG :Found fd=31 for file 0x7fdccc001740 of type REGULAR_FILE`

Second write to offset 0xc9000

`[svc_172] nfs3_write :NFS3 :DEBUG :REQUEST PROCESSING: Calling nfs_Write handle: File Handle V3: Len=48 430000012a44000000000040000027000006beabf27b0100000000000000005f73746174655f743a7330002390ffff00 start: c9000 len: 1000 FILE_SYNC
[svc_172] fsal_reopen_obj :RW LOCK :F_DBG :Got read lock on 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/commonlib.c:2609
[svc_172] fsal_reopen_obj :FSAL :F_DBG :Open mode = 3, desired mode = 2
[svc_172] find_fd :FSAL :F_DBG :Found fd=31 for file 0x7fdccc001740 of type REGULAR_FILE`

First write returned to Ganesha, and I see getattr going to the FS presumably to fill in WCC data

`[svc_192] vfs_write2 :RW LOCK :F_DBG :Unlocked 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/FSAL_VFS/file.c:1394
[svc_192] nfs3_write_cb :NFS3 :F_DBG :write fsal_status=No error
[svc_192] mdcache_getattrs :RW LOCK :F_DBG :Got read lock on 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:924
[svc_192] mdcache_getattrs :RW LOCK :F_DBG :Unlocked 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:932
[svc_192] mdcache_getattrs :RW LOCK :F_DBG :Got write lock on 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:933
[svc_192] fsal_reopen_obj :RW LOCK :F_DBG :Got read lock on 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/commonlib.c:2609
[svc_192] vfs_getattr2 :FSAL :F_DBG :Got fd 31 closefd = false`

In WekaFS logs I've seen that getattr after the first write entered the system and was served before the second write was committed, therefore it returned 0xbb000 as file size and appropriate mtime+ctime when the first write was committed.

However, Ganesha got ack on the second write before it got getattr reply (the machine was artificially stressed to 100% CPU consumption)

`[svc_172] vfs_write2 :RW LOCK :F_DBG :Unlocked 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/FSAL_VFS/file.c:1394
[svc_172] nfs3_write_cb :NFS3 :F_DBG :write fsal_status=No error`

According to Ganesha source, I assume that second write is now waiting to acquire attr_lock for read...

Now getattr from the first write finally arrives to Ganesha:

`[svc_192] vfs_getattr2 :RW LOCK :F_DBG :Unlocked 0x7fdccc001768 (&obj_hdl->obj_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/FSAL_VFS/file.c:1908
[svc_192] mdcache_refresh_attrs :INODE :F_DBG :attrs  obj attributes Request Mask=0011dfce Valid Mask=0011dfce Supported Mask=0091dfce REGULAR_FILE numlinks=0x1 size=0xbb000 mode=0644 owner=0x0 group=0x0 atime=03/03/2020 14:23:33 mtime=03/03/2020 14:23:36
[svc_192] mdcache_getattrs :RW LOCK :F_DBG :Unlocked 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:962
[svc_192] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=0001dfce Valid Mask=0011dfce Supported Mask=0091dfce REGULAR_FILE numlinks=0x1 size=0xbb000 mode=0644 owner=0x0 group=0x0 atime=03/03/2020 14:23:33 mtime=03/03/2020 14:23:36
[svc_192] nfs3_FSALattr_To_PartialFattr :NFS3 :F_DBG :Compressing fsid for NFS v3 from fsid major 0 (0), minor 0X4000 (16384) to nfs3_fsid = 0X400000000000 (70368744177664)`

From log we see that it is going to return size 0xbb000 which is perfect reply as WCC for the first write.

Then svc_172 gets unblocked, but for some reason it doesn't call getattr, but returns attributes that it just got as WCC for the second write as well:

`[svc_172] mdcache_getattrs :RW LOCK :F_DBG :Got read lock on 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:924
[svc_172] mdcache_getattrs :RW LOCK :F_DBG :Unlocked 0x7fdccc0018a0 (&entry->attr_lock) at /build/nfs-ganesha-41mpwz/nfs-ganesha-2.8.3/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:962
[svc_172] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=0001dfce Valid Mask=0011dfce Supported Mask=0091dfce REGULAR_FILE numlinks=0x1 size=0xbb000 mode=0644 owner=0x0 group=0x0 atime=03/03/2020 14:23:33 mtime=03/03/2020 14:23:36
[svc_172] nfs3_FSALattr_To_PartialFattr :NFS3 :F_DBG :Compressing fsid for NFS v3 from fsid major 0 (0), minor 0X4000 (16384) to nfs3_fsid = 0X400000000000 (70368744177664)`

From this point client continued with wrong attributes

Did I miss anything on VFS protocol? Or is it Ganesha bug?
I didn't find any attributes invalidation in nfs3 write completion code.

**Comment by dang** [comment] 2020-03-10 13:54
This is a side effect of using atomics for attribute trust, rather than locks (which are much more expensive in this case).  What happens is this:

192 -> mdcache_write() (block)
172 -> mdcache_write() (block)
192 -> Write returns, mdc_write_super_cb() clears MDCACHE_TRUST_ATTRS
192 -> mdcache_getattrs() (got attr_lock for write) (block)
172 -> Write returns, mdc_write_super_cb() clears MDCACHE_TRUST_ATTRS
172 -> mdcache_getattrs() (block on attr_lock for read)
192 -> getattrs returns, updates attributes, sets MDCACHE_TRUST_ATTRS
192 -> Release attr_lock
172 -> Gets attr_lock, checks MDCACHE_TRUST_ATTRS, uses cached attributes.

The only way around this would be to read/write MDCACHE_TRUST_ATTRS under the attr_lock, which would add a lot of expensive lock ops to various paths, I think.  If you absolutely need attributes to be correct at all times, you can turn off attribute caching by setting Attr_Expiration_Time to zero in EXPORT or EXPORT_DEFAULTS.

**Comment by alxgit** [comment] 2020-03-11 10:28
@dang what about using a "generation" number in addition to the MDCACHE_TRUST_ATTRS flag? 
* The generation would be increased upon return of a write/truncate operation and MDCACHE_TRUST_ATTRS cleared.
* Generation would be saved aside at the beginning of a getattr, and compared at the end of it to know if it's valid to cache the attrs and set MDCACHE_TRUST_ATTRS.

**Comment by ffilz** [comment] 2020-03-11 14:39
Hmm, I think a possible solution would be to take the attr_lock in mdc_write_super_cb while clearing the MDCACHE_TRUST_ATTRS flag. It may only need to take it READ since what it needs to do is make sure it clears the flag AFTER any in progress attribute refresh.

Truncate as part of setattr already does it's clear of the MDCACHE_TRUST_ATTRS flag while holding the attr_lock.

**Comment by alxgit** [comment] 2020-03-22 16:45
Hey @ffilz , we want to fix this, and we're trying to think of the best way. We don't understand what you have offered - as we see in @dang 's comment above, the issue is not with preventing something intervening between  mdc_write_super_cb() and mdcache_getattrs() which takes the attr_lock - they happen serialised anyways, so taking the lock a bit before won't change something? what am I missing?

**Comment by ffilz** [comment] 2020-07-15 18:35
Looks like a bug that should be addressed.

**Comment by alxgit** [comment] 2020-07-16 07:32
@ffilz it was addressed by https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/491544.

**Comment by ffilz** [comment] 2020-07-16 14:50
> @ffilz it was addressed by https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/491544.

Thanks, closing as resolved then.

**Closed as completed by ffilz** 2020-07-16 14:50 UTC
Labels: Bug
