### ISSUE TITLE
NFS-Ganesha NFS4 Mount issues with vmware 6.7

### ISSUE THREAD

**Issue by madmax01** [nfs-ganesha/nfs-ganesha#459] opened 2019-08-21 13:35 UTC
Hi Guys,

i have a lab with 2 Gluster Nodes (4.1.9) with nfs-ganesha 2.7.6

once i mount NFS3 mount Point to an Esxi Cluster > both Hosts seeing the NFS Datastore as shared.  all works fine with vmotion,... .   

But once i add the same mount point as NFS 4.1  > the 2nd Host getting an completely differently UUID.  so i have  2 differently Datastores then.

i'am not sure where the Issue could be,......  something must be special with NFS 4.1

do i need to have a special setting on NFS-Ganesha side?   as on Vmware Side there are no options to place

thx

Max

**Comment by ffilz** [comment] 2019-08-21 17:03
Is the issue that the NFS v4.1 mount has a different UUID than the NFS v3 mount? That may be caused by the fsid in NFS v3 being 64 bits and NFS v4 being 128 bits. We have a solution to that issue for FSAL_VFS, but that solution isn't applicable to FSAL_GLUSTER.

**Comment by madmax01** [comment] 2019-08-23 15:25
i don't have issue that the NFS3 UUID are differ from NFS4.  what i mean is   NFS4 working somehow strange.    as once mounting the same Share from differently IP's  then it's recognize it with differently UUID.    this not happening with NFS3 through ganesha.   NFS3 seems doesn't care about if IP's are same or differently behind an FQDN.

2 esxi Hosts  

mount with (NFS3)

i see Test

if i do exact same with NFS4

then i see

Test
and 
Test(1)

as it's getting other UUID 

even if i mount it based on fqdn > it's recognize the differently IP behind.

anything i could do here?

many thx ;)

**Comment by ffilz** [comment] 2019-08-23 15:53
Could you construct a limited test case (with instructions of what you do from mount commands to the other commands) to show the issue and provide a tcpdump packet trace (use the -s0 -w /tmp/trace options)?

**Comment by ffilz** [comment] 2020-07-14 21:22
Closing due to age. Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org

**Closed as completed by ffilz** 2020-07-14 21:22 UTC
