### ISSUE TITLE
delete snapshots is still in cache (FSAL_CEPH)

### ISSUE THREAD

**Issue by zs0723** [nfs-ganesha/nfs-ganesha#711] opened 2021-04-30 04:08 UTC
How to reproduce:
1. create snapshot by ceph command
2. access the snapshot in nfs client, we can check if the snapshot has been accessed by nfs client:
```
172.27.0.49:/export1/.snap/snapshot6 on /mnt/nfs/.snap/snapshot6 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.27.0.37,local_lock=none,addr=172.27.0.49)
```
3. delete snapshot by ceph command
4. ls -ltr .snap 
The snapshot6 is not listed in .snap directory 
5. access the snapshot6 manually 
cd .snap/snapshot6  this command success
6. check fuse client cache the snapshot exists
  ceph daemon dump_cache

How to workaround the issue:
 Restart nfs-ganesha , access ./snap/snapshot6 will get Stale Handle Error

**Comment by dang** [comment] 2021-04-30 12:51
2 issues here, I think.  First, ganesha caches metadata for (by default) 60 seconds, so unless Ceph sends an UP-call to notify of the snapshot's deletion, Ganesha will still make metadata (although not data) available for 60 seconds.  Second, libcephfs has it's own caches for metadata and data, which are not under Ganesha's control in any way.  I'm not sure what the timescales are for that.

**Comment by zs0723** [comment] 2021-04-30 13:42
yes, after 60 seconds. we can not see the deleted snapshot under .snap directory. we still can stat the deleted snapshot
```
root@xxxxx .snap]# ls -ltr
total 2
drwxrwxrwx 2 root root   33776778 Apr 29 21:14 snapshot3
drwxrwxrwx 3 root root 2578686580 Apr 30 14:39 snapshot7
drwxrwxrwx 3 root root 2578686580 Apr 30 14:39 snapshot6
[root@xxxx .snap]# stat snapshot999
  File: ‘snapshot999’
  Size: 2578686580      Blocks: 1          IO Block: 32768  directory
Device: 2ah/42d Inode: 1099511627776  Links: 3
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-04-29 21:10:49.821107265 +0800
Modify: 2021-04-30 14:39:31.495515088 +0800
Change: 2021-04-30 21:35:55.261548319 +0800
 Birth: -
```

**Comment by dang** [comment] 2021-04-30 13:58
That has to be a libcephfs caching issue, then, because after 60 seconds, the metadata returned by stat in Ganesha is gone, and the next stat will call into libcephfs.  It should, at that point, return ESTALE.  @jtlayton Ideas?

**Comment by jtlayton** [comment] 2021-04-30 14:37
Not right offhand. It does sound like a libcephfs issue, but it might be good to collect some NIV_DEBUG level output from ganesha and verify that it called down into libcephfs when it went to do the lookup of snapshot999.

Assuming it did though, then it sounds like the ceph client didn't get the memo that that snapshot had been deleted. You may want to open a tracker ticket at https://tracker.ceph.com, and we can get someone better versed in the snapshot logic to comment.

They are supposed to be "eventually consistent" so it may just have been the delay in updating that. It's hard to say for sure without reproducing it and figuring out what it's doing.

**Comment by zs0723** [comment] 2021-05-01 14:19
Checked the logs, it seems the issue related to  ganesha mdcache or export object ?
Check libcephfs logs, the client got error no -2 when lookup deleted snapshot object.
```

2021-05-01 17:23:18.114 7fce545f6700  3 []client.107297 ll_lookupx 0x100000254ff.snapdir .snapshot1
2021-05-01 17:23:18.114 7fce545f6700 20 []client.107297 may_lookup 0x100000254ff.snapdir(faked_ino=0 ref=3 ll_ref=1 cap_refs={} open={} mode=40777 size=0/0 nlink=1 btime=0.000000 mtime=2021-05-01 11:36:17.479768 ctime=2021-05-01 11:36:48.891631 caps=- flags=0 0x7fce34013d50); UserPerm(uid: 0, gid: 0)
2021-05-01 17:23
2021-05-01 17:23:18.114 7fce545f6700 10 []client.107297 send_request client_request(unknown.0:594 lookupsnap #0x100000254ff//.snapshot1 2021-05-01 17:23:18.115327 caller_uid=0, caller_gid=0{0,})
 v4 to mds.0
 2021-05-01 17:23:18.114 7fce545f6700 10 []client.107297 _do_lookup res is -2 <<<<<<<<<<<<<<<<<
 2021-05-01 17:23:18.114 7fce545f6700 10 []client.107297 _lookup 0x100000254ff.snapdir(faked_ino=0 ref=3 ll_ref=1 cap_refs={} open={} mode=40777 size=0/0 nlink=1 btime=0.000000 mtime=2021-05-01 11:36:17.479768 ctime=2021-05-01 11:36:48.891631 caps=- flags=0 0x7fce34013d50) .snapshot1 = -2
 2021-05-01 17:23:18.114 7fce545f6700  3 []client.107297 ll_lookupx 0x100000254ff.snapdir .snapshot1 -> -2 (0)
 2021-05-01 17:23:24.640 7fce4cdf7700 20 []client.107297 _lookup have dn snapshot1 mds.0 ttl 2021-06-20 04:49:17.853574 seq 0
 2021-05-01 17:23:24.640 7fce4cdf7700 15 []inode.get on 0x7fce5000de40 0x100000254ff.11 now 4
 2021-05-01 17:23:24.640 7fce4cdf7700 10 []client.107297 _lookup 0x100000254ff.snapdir(faked_ino=0 ref=3 ll_ref=1 cap_refs={} open={} mode=40777 size=0/0 nlink=1 btime=0.000000 mtime=2021-05-01 11:36:17.479768 ctime=2021-05-01 11:36:48.891631 caps=- flags=0 0x7fce34013d50) snapshot1 = 0x100000254ff.11(faked_ino=0 ref=4 ll_ref=1 cap_refs={} open={} mode=40777 size=0/0 nlink=1 btime=2021-05-01 11:31:09.778801 mtime=2021-05-01 11:36:17.479768 ctime=2021-05-01 11:36:51.521737 caps=pAsLsXsFscrl COMPLETE flags=3 parents=0x100000254ff.snapdir["snapshot1"] has_dir_layout 0x7fce5000de40)
 2021-05-01 17:23:24.640 7fce
```
Checked ganesha log, it responded the error:
```
 1/05/2021 17:23:18 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_995] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=7c76d06b3baf973a fsal=0x7fce671083e0 key=0xff54020000010000ffffffffffffffff00000000000000000200
 01/05/2021 17:23:18 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_995] mdcache_find_keyed_reason :INODE :F_DBG :Found entry 0x7fce340142b0
 01/05/2021 17:23:18 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_995] mdcache_refresh_attrs :INODE :F_DBG :attrs  obj attributes Request Mask=0211dfce Valid Mask=0011ffce Supported Mask=0011dfce DIRECTORY numlinks=0x2 size=0x0 mode=0777 owner=0x0 group=0x0 atime=01/05/2021 11:31:09 mtime=01/05/2021 11:36:17
 01/05/2021 17:23:18 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_995] mdc_lookup :INODE :F_DBG :Lookup .snapshot1
 01/05/2021 17:23:18 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_995] mdc_lookup_uncached :INODE :DEBUG :lookup .snapshot1 failed with No such file or directory. <<<<<<<<<<<
 01/05/2021 17:23:19 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_999] mdcache_find_keyed_reason :INODE :F_DBG :Looking for hk=20ad4a8bf73d2ee6 fsal=0x7fce671083e0 key=0xff54020000010000feffffffffffffff00000000000000000200
 01/05/2021 17:23:19 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_999] mdcache_find_keyed_reason :INODE :F_DBG :Found entry 0x10d5130
 01/05/2021 17:23:19 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_999] mdcache_refresh_attrs :INODE :F_DBG :attrs  obj attributes Request Mask=0211dfce Valid Mask=0011ffce Supported Mask=0011dfce DIRECTORY numlinks=0x2 size=0x4181de mode=0777 owner=0x0 group=0x0 atime=01/05/2021 11:31:09 mtime=01/05/2021 11:36:17
 01/05/2021 17:23:19 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_999] mdcache_getattrs :INODE :F_DBG :attrs  obj attributes Request Mask=00000080 Valid Mask=0011ffce Supported Mask=0011dfce DIRECTORY numlinks=0x2 size=0x4181de mode=0777 owner=0x0 group=0x0 atime=01/05/2021 11:31:09 mtime=01/05/2021 11:36:17
 01/05/2021 17:23:19 : epoch 608ccbe3 : VM-0-49-centos : ganesha.nfsd-2899340[svc_999] fsal_statfs :FSAL :F_DBG :dynamicinfo: {total_bytes = 132120576000, free_bytes = 129536884736, avail_bytes = 129536884736, total_files = 2, free_files = 18446744073709551615, avail_files = 18446744073709551615
```
More informations:
When we visited the snapshot directory,  NFS client will have a new mount point, does the new mount point cause trigger the issue ?
```
172.27.0.49:/export2/.snap/snapshot1 on /mnt/csptest/.snap/snapshot1 type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.27.0.12,local_lock=none,addr=172.27.0.49)
```

**Comment by jtlayton** [comment] 2021-05-03 13:01
I wonder if this is just a case of the client caching a dentry beyond the point that you are expecting. Note that the default acdirmin= mount option is 30s. A cached dentry can live for quite a while before the client notices that it's gone. You may want to look at the NFS traffic between client and server and determine whether there are any actual on the wire lookups after the snapshot dir is unlinked while the client thinks it's there.

The new mount point is just how the NFS client deals with the potential for inode number collisions. When it sees that a child dentry's inode has a different fsid than the parent, it transparently does a new mount to ensure that it has its own superblock. Each snapshot will get a new snapid, which is what gansha puts into the fsid field. So, a new mount point is expected there and shouldn' t be an issue.

**Comment by ffilz** [comment] 2021-10-19 18:18
Closing this one for lack of any response. It doesn't sound like it's a Ganesha code issue.

**Closed as completed by ffilz** 2021-10-19 18:18 UTC
Labels: Analyzing
