### ISSUE TITLE
how to increase Parallel reading?

### ISSUE THREAD

**Issue by agin719** [nfs-ganesha/nfs-ganesha#595] opened 2020-06-10 08:53 UTC
Hello, I have some questions to ask. 
I add a sleep operation in the function nfs4_read(in Protocols/NFS/nfs4_op_read.c). In version nfs-ganesha-2.5, I observer that nfs4_read is called about 3 times a second.  Why I increase the  concurrent read requests of different files in the client, the times are not be increased.  so can I increate the Parallel reading(or writing) in nfs-ganesha-2.5.

**Comment by malahal** [comment] 2020-06-10 10:57
How many worker threads you have? You may need few NFS clients (maybe limited by one client, not sure about this though) and create bunch of processes to read different files.

number of worker threads and your sleep time limits the number reads you can do per second.

It is lot easier to create parallel writes though. "dd" of a big file will send multiple writes in parallel by write behind code.

**Comment by agin719** [comment] 2020-06-11 02:45
I did't set any worker threads in conf file, It may 200 in default? creating bunch of processes to read different files with one client cant't work. with several  new clients  in different machine can improve the Parallel reading(or writing). Are there any solutions to make it improve in one client?

**Comment by malahal** [comment] 2020-06-11 18:03
> I did't set any worker threads in conf file, It may 200 in default? creating bunch of processes to read different files with one client cant't work. with several new clients in different machine can improve the Parallel reading(or writing). Are there any solutions to make it improve in one client?

It is 256 in ganesha2.5. What is preventing single client making lots of reads in parallel? They all use the same TCP/IP connection but I thought the RPC slots are dynamic. What is your exact client distro/kernel? I will have to experiment this someday....

**Comment by malahal** [comment] 2020-06-11 18:05
Try fio tool https://fio.readthedocs.io/en/latest/fio_doc.html, it may have some options to achieve what you want.

**Comment by agin719** [comment] 2020-06-12 12:15
> > I did't set any worker threads in conf file, It may 200 in default? creating bunch of processes to read different files with one client cant't work. with several new clients in different machine can improve the Parallel reading(or writing). Are there any solutions to make it improve in one client?
> 
> It is 256 in ganesha2.5. What is preventing single client making lots of reads in parallel? They all use the same TCP/IP connection but I thought the RPC slots are dynamic. What is your exact client distro/kernel? I will have to experiment this someday....

I use this commnad to mount :   
mount -t nfs -o vers=4 ....
And the client version  is Client nfs v4. 
This situation will improve in nfs-ganesha 2.8 (the reads/writes in parallel up to about 60)， I think which is because of the Asynchronous read/write mechanism in nfs-ganesha 2.8 . But when I improve the parallelly reading/writing , It also seem not  improve the  reads/writes in parallel in nfs-ganesha 2.8 ( still about 60).

**Comment by agin719** [comment] 2020-06-12 12:18
> > I did't set any worker threads in conf file, It may 200 in default? creating bunch of processes to read different files with one client cant't work. with several new clients in different machine can improve the Parallel reading(or writing). Are there any solutions to make it improve in one client?
> 
> It is 256 in ganesha2.5. What is preventing single client making lots of reads in parallel? They all use the same TCP/IP connection but I thought the RPC slots are dynamic. What is your exact client distro/kernel? I will have to experiment this someday....

I use this commnad to mount :
mount -t nfs -o vers=4 ....
And the client version is Client nfs v4.
This situation will improve in nfs-ganesha 2.8 (the reads/writes in parallel up to about 60)， I think which is because of the Asynchronous read/write mechanism in nfs-ganesha 2.8 . But when I improve the parallelly reading/writing in one client , It also seem not improve the reads/writes in parallel in nfs-ganesha 2.8 ( still about 60).

**Comment by malahal** [comment] 2020-06-14 04:29
Since you don't seem to care if this is either reads or writes, writes are easier to generate in parallel from a single client and single large file. How ganesha handles these is a different matter. I didn't understand your previous comment. You said you think ganesha2.8 will get 60 in parallel, I am not sure if you tested with ganesha2.8 or you are guessing due to some understanding of ganesha2.8.

**Comment by agin719** [comment] 2020-06-16 06:16
I tested with ganesha 2.8 and get about 60 in parallel in one client. the tested way is what I said in the beginning of this topic.

**Comment by malahal** [comment] 2020-06-16 12:56
As far as I know, there shouldn't be anything holding up parallelism in ganesha2.5 with respect to sleep in nfs4_read. If you share your code via github (or some other means) and how you measured and arrived at parallelism number, we can recreate and find the root cause.

ganesha2.5 is not maintained anymore, but I am curious to know what limits it.

**Comment by agin719** [comment] 2020-06-16 13:19
I modify file Protocols/NFS/nfs4_op_write.c in line 331:
static int nfs4_write(struct nfs_argop4 *op, compound_data_t *data,                                                                                                                            
             struct nfs_resop4 *resp, fsal_io_direction_t io,                      
             struct io_info *info)                                                 
{
........
    offset = arg_WRITE4->offset;                                                
    size = arg_WRITE4->data.data_len;                                           
    stable_how = arg_WRITE4->stable;                                            
    **LogEvent(COMPONENT_NFS_V4, "offset: %lu, size: %lu", offset, size);         
    sleep(3);**                                                                   
........
}
The ganesha.log's contents are as follow:
**16/06/2020 21:09:52** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-23] nfs4_write :NFS4 :EVENT :offset: 0, size: 1048576
16/06/2020 21:09:52 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-24] nfs4_write :NFS4 :EVENT :offset: 1048576, size: 1048576
16/06/2020 21:09:52 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-25] nfs4_write :NFS4 :EVENT :offset: 2097152, size: 1048576
**16/06/2020 21:09:55** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-26] nfs4_write :NFS4 :EVENT :offset: 3145728, size: 1048576
16/06/2020 21:09:55 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-27] nfs4_write :NFS4 :EVENT :offset: 4194304, size: 1048576
16/06/2020 21:09:55 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-28] nfs4_write :NFS4 :EVENT :offset: 5242880, size: 1048576
**16/06/2020 21:09:58** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-29] nfs4_write :NFS4 :EVENT :offset: 6291456, size: 1048576
16/06/2020 21:09:58 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-30] nfs4_write :NFS4 :EVENT :offset: 7340032, size: 1048576
16/06/2020 21:09:58 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-31] nfs4_write :NFS4 :EVENT :offset: 8388608, size: 1048576
**16/06/2020 21:10:01** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-32] nfs4_write :NFS4 :EVENT :offset: 9437184, size: 1048576
16/06/2020 21:10:01 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-33] nfs4_write :NFS4 :EVENT :offset: 10485760, size: 1048576
16/06/2020 21:10:01 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-34] nfs4_write :NFS4 :EVENT :offset: 11534336, size: 1048576
**16/06/2020 21:10:04** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-35] nfs4_write :NFS4 :EVENT :offset: 12582912, size: 1048576
16/06/2020 21:10:04 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-36] nfs4_write :NFS4 :EVENT :offset: 13631488, size: 1048576
16/06/2020 21:10:04 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-37] nfs4_write :NFS4 :EVENT :offset: 14680064, size: 1048576
**16/06/2020 21:10:07** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-38] nfs4_write :NFS4 :EVENT :offset: 15728640, size: 1048576
16/06/2020 21:10:07 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-39] nfs4_write :NFS4 :EVENT :offset: 16777216, size: 1048576
16/06/2020 21:10:07 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-40] nfs4_write :NFS4 :EVENT :offset: 17825792, size: 1048576
**16/06/2020 21:10:10** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-41] nfs4_write :NFS4 :EVENT :offset: 18874368, size: 1048576
16/06/2020 21:10:10 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-42] nfs4_write :NFS4 :EVENT :offset: 19922944, size: 1048576
16/06/2020 21:10:10 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-43] nfs4_write :NFS4 :EVENT :offset: 20971520, size: 1048576
**16/06/2020 21:10:13** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-44] nfs4_write :NFS4 :EVENT :offset: 22020096, size: 1048576
16/06/2020 21:10:13 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-45] nfs4_write :NFS4 :EVENT :offset: 23068672, size: 1048576
16/06/2020 21:10:13 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-46] nfs4_write :NFS4 :EVENT :offset: 24117248, size: 1048576
**16/06/2020 21:10:16** : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-47] nfs4_write :NFS4 :EVENT :offset: 25165824, size: 1048576
16/06/2020 21:10:16 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-48] nfs4_write :NFS4 :EVENT :offset: 26214400, size: 1048576
16/06/2020 21:10:16 : epoch 5ee8c442 : VM_16_6_centos : ganesha.nfsd-27987[work-49] nfs4_write :NFS4 :EVENT :offset: 27262976, size: 1048576

The log tells me about three parallel writing in one client. If It is the nfs protocal to limit parallel, But Why It can improve to about 60 parallel writing in ganesha 2.8?

**Comment by dang** [comment] 2020-06-17 12:14
The entire threading model has been re-written between 2.5 and 2.8.  In addition, an ASYNC API for read/write was added, and non-blocking I/O was added, so basically everything related to parallelism is different.

**Comment by ffilz** [comment] 2020-07-15 21:57
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed as completed by ffilz** 2020-07-15 21:57 UTC
