### ISSUE TITLE
Regression: 101cfb8 broke NFSv3 with FSAL_CEPH

### ISSUE THREAD

**Issue by bjorn-fischer** [nfs-ganesha/nfs-ganesha#661] opened 2020-11-26 09:52 UTC
Seems that 101cfb8 broke NFSv3 with Ceph backends. After that commit you can still mount an export with NFS version 3. You can `ls` the mounted (root) directory, but `ls` on any subdirectory yields EINVAL:

```
root@testnfs# mount -o vers=3 ganesha-dev:/foobar /mnt
root@testnfs# ls /mnt
total 2
drwxr-xr-x 176 juser users   59316 Sep 10 11:21 simple_dir
drwxr-xr-x 173 juser users    2932 Sep 10 11:21 simple_dir_2
root@testnfs# ls /mnt/simple_dir
ls: reading directory '/mnt/simple_dir/': Invalid argument
total 0
```

**Comment by bjorn-fischer** [comment] 2020-11-26 11:25
In `handle.c:ceph_fsal_handle_to_wire()` the `fh_desc->len` is set to `sizeof(*hhdl)`, so a fix may be:
```
--- a/src/FSAL/FSAL_CEPH/export.c
+++ b/src/FSAL/FSAL_CEPH/export.c
@@ -259,7 +259,7 @@ static fsal_status_t create_handle(struct fsal_export *export_pub,
 
        *pub_handle = NULL;
 
-       if (desc->len != sizeof(*key)) {
+       if (desc->len != sizeof(*hhdl)) {
                status.major = ERR_FSAL_INVAL;
                return status;
        }
```

**Comment by ffilz** [comment] 2020-11-30 15:49
Can you make this fix and test?

**Comment by bjorn-fischer** [comment] 2020-11-30 16:19
Already tested with Linux clients, no regressions so far.

But as I understand 101cfb8 that commit already addressed the size comparison. I would feel more confident if viCEnTECheNg could look into this.

Also, I'd like to test this against some of our more obscure v3 clients. And, just to be sure not to introduce some new v4 problems, I plan to pynfs this.

**Comment by bjorn-fischer** [comment] 2020-12-03 15:52
Looks like `create_handle()` in `FSAL_CEPH/export.c` acts on **wire handles**, which are `struct ceph_host_handle` (and not `struct ceph_handle_key`). So, I do not really get what 101cfb8 wants to achieve. What situation triggered EINVAL before 101cfb8?
The following partially rolls back 101cfb8 keeping the name `hhdl` for the handle identifier. It has been tested with _pynfs_, resolving 2 fails in v4.0 and no changes in v4.1. Still, I would like to have a test case at hand which lead to the EINVAL initially.

```
        /* FSAL status to return */
        fsal_status_t status = { ERR_FSAL_NO_ERROR, 0 };
        /* The FSAL specific portion of the handle received by the client */
-       struct ceph_handle_key *key = desc->addr;
-       struct ceph_host_handle *hhdl = &key->hhdl;
+       struct ceph_host_handle *hhdl = desc->addr;
        /* Ceph return code */
        int rc = 0;
        /* Stat buffer */
@@ -259,7 +258,7 @@ static fsal_status_t create_handle(struct fsal_export *export_pub,
 
        *pub_handle = NULL;
 
-       if (desc->len != sizeof(*key)) {
+       if (desc->len != sizeof(*hhdl)) {
                status.major = ERR_FSAL_INVAL;
                return status;
        }
```
**Update:** V4-dev.43 with this patch is now running on one of our production servers (we badly need the Ceph feature "respond to cache pressure") and no problems so far -- neither on  NFSv3 clients nor on v4.

**Comment by ffilz** [comment] 2020-12-11 15:43
I going to close this as resolved. If you don't consider it resolved, please re-open.

**Comment by Vicente-Cheng** [comment] 2020-12-14 17:21
Hi @ffilz @bjorn-fischer,
sorry for late to see this issue, I already test it and try to figure out why that could happen.

For the wire-handle, module fsal_ceph would have different behavior.
1. hand_to_wire would make type ceph_host_handle from fsal_obj_handle w/o export id.
2. wire_to_host would make type ceph_handle_key from fsal_obj_handle w/ export id.

The first case in nfs3_readdir would happen in reading `..` after lookup `.`.
After 101cfb8 I change the checking mechanism in create_handle, so return EINVAL in this case.
(nfs4 would not meet this problem  because the `..` and `.` are the special cases)

The changes in 101cfb8 are for `putfh` in nfs4.
In putfh, we would set up fh again with wire_to_host like the above case 2.
That would cause the EINVAL with create_handle before introduce 101cfb8.

Maybe we should keep the consistency about handle buffer checking in create_handle?
For FSAL_CEPH, we use the struct ceph_handle_key. We make type ceph_handle_key on
handle_to_wire but don't set up export id (because that would be set up later).
I think that would not break the behavior with handle_to_wire now and also make create_handle
do the handle buffer checking consistency.

I would make a fix patch for it. (Already tested with nfs3/nfs4)
If there is anything I have a misunderstanding feel free to let me know.

thanks
vicente.

**Comment by ffilz** [comment] 2020-12-15 19:40
Not actually resolved yet...

**Comment by ffilz** [comment] 2020-12-15 19:41
Patch under review: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/507499

**Comment by ffilz** [comment] 2020-12-15 21:52
I don't have a setup to try to debug or fix this issue, but I think the problem is that FSAL_CEPH doesn't have host_to_key which is implicated in the v3 READDIR case for lookup of ..

This patch and the one Vincente posted in gerrothub are not right fixes.

**Comment by ffilz** [comment] 2020-12-16 00:29
See https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/507717 for my attempt to fix the issue.

**Comment by bjorn-fischer** [comment] 2020-12-16 00:39
I will test it tomorrow and keep you updated.

**Comment by Vicente-Cheng** [comment] 2020-12-16 05:02
Already tested your patch in nfsv4/nfsv3.
The above patch is more make sense to me.

And sorry @bjorn-fischer, I lost to test nfsv3 then make your problems with 101cfb8..
 
Thanks, @ffilz

**Comment by ffilz** [comment] 2020-12-16 18:59
After review I updated the patch set, please test again.

**Comment by bjorn-fischer** [comment] 2020-12-17 10:44
Testing complete, results positive.
[gerrithub:507717](https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/507717) and [gerrithub:507773](https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/507773) resolve the NFSv3 problems and some _pynfs_ fails.

So, this can be closed after commit.

**Comment by ffilz** [comment] 2021-03-06 00:07
Closing as resolved.

**Closed as completed by ffilz** 2021-03-06 00:07 UTC
Labels: Bug
