### ISSUE TITLE
NFS Ganesha frequent restarts

### ISSUE THREAD

**Issue by rajasec** [nfs-ganesha/nfs-ganesha#982] opened 2023-08-02 13:47 UTC
We are having version Ganesha **NFS 2.7.1**, it silently restarts. Before restarts, I could see the below error.
We are running in k8s environment, Pod silent restarts

nfs-ganesha-20[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
: nfs-ganesha-20[main] nfs_start :NFS STARTUP :EVENT : NFS SERVER INITIALIZED
: nfs-ganesha-20[main] nfs_start :NFS STARTUP :EVENT :-------------------------------------------------
: nfs-ganesha-20[reaper] nfs_lift_grace_locked :STATE :EVENT :NFS Server Now NOT IN GRACE
: nfs-ganesha-20[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 193298, old: 193297; deq new: 193297, old: 193297
: nfs-ganesha-20[dbus_heartbeat] nfs_health :DBUS :WARN :Health status is unhealthy. enq new: 501857, old: 501856; deq new: 501856, old: 501856
: nfs-ganesha-24[main] main :MAIN :EVENT :nfs-ganesha Starting: Ganesha Version 2.7.1

**Comment by dang** [comment] 2023-08-02 15:42
2.7.1 is 5 years old, and completely unsupported, sorry.

**Comment by ffilz** [comment] 2023-08-02 16:25
We should look at that unhealthy message sometime....

That's not the cause of the problem here, some other crash, but as Daniel points out, 2.7.1 is way out of support.  Please try on Ganesha V5.4 (or V4.4.1 if absolutely necessary).

**Comment by rajasec** [comment] 2023-08-03 01:22
@ffilz   @dang Any stable recommended version as we need to have in Production ?

**Comment by ffilz** [comment] 2023-08-03 14:31
V4.4.1 should be stable for production though limited support. We are a small team and can not support multiple versions, with V5.x out, we prefer to support that, however, there ARE some instabilities being worked through. Because of this, you will want to move to V5.5 when it becomes available this week or next. V5.x includes mdcache LRU changes that should eliminate unbounded growth of the memory footprint.

**Comment by rajasec** [comment] 2023-08-08 03:45
@ffilz 
As it is related to clinical data from patients, we want to use the stable version. we will use 4.4.1 for current release in production. Once 5.X is stabilized, we will move to 5.X line.
Thank you for the support.

**Comment by Brike70** [comment] 2023-08-15 16:26
Hello,

I'm running debian and looking to get v5.5 as we're having issues with the bookworm release.

Do you know when https://download.nfs-ganesha.org/ will have the binaries available for any v5?

Cheers.

**Comment by GuyFoetz** [comment] 2023-08-17 12:37
HI.

it seems that the bookworm binaries are present, just in the wrong folder (arm64)

[https://download.nfs-ganesha.org/5/5.5/Debian/bookworm/**arm64**/apt/pool/main/n/nfs-ganesha/](https://download.nfs-ganesha.org/5/5.5/Debian/bookworm/arm64/apt/pool/main/n/nfs-ganesha/)

maybe the repo path needs to be fixed :face_with_spiral_eyes: 

Regards.

**Comment by Brike70** [comment] 2023-08-18 16:15
Yeah.  I spotted those go in the other day.

I've tried them manually by pulling the .deb files down and doing a `dpkg -i` on them but it looks like they want the old dependencies from bullseye?

It depends on liburcu6 and daemon which don't exist in bookworm but liburcu8 does?

**Comment by Brike70** [comment] 2023-08-27 20:44
Quick update. 

The main ganesha package is now installing okay thanks to kkeithley but the nfs-ganesha-gluster package is looking for libgfapi which doesn't exist but libgfapi0 does.

Cheers.

**Comment by ffilz** [comment] 2024-02-21 00:54
Can we close this or is there still an issue?

**Comment by ffilz** [comment] 2024-07-23 23:43
Closing, no response in more than 60 days.

**Closed as completed** 2024-07-23 23:44 UTC
Labels: Try-on-supported-version, Can we close?
