### ISSUE TITLE
Memory Violation - ganesha-gluster-2.5.5-1

### ISSUE THREAD

**Issue by lewisstrong1991** [nfs-ganesha/nfs-ganesha#474] opened 2019-09-06 12:43 UTC
Good Afternoon

We're currently experiencing ongoing issues where the NFS-Ganesha service is terminating due to Memory Violation errors. The below is an example extract from the messages log on a RHEL7 instance where the issues occurs. Following a restart of the service it will continue to work again for an unspecified period until this error is encountered again.   

-------------------------------------------------------------------------------------
```
Sep  5 05:43:49 gfs1 kernel: ganesha.nfsd[17097]: segfault at 0 ip 000055a83630768e sp 00007f7560fd6940 error 4 in ganesha.nfsd[55a8361df000+19c000]

Sep  5 05:43:49 gfs1 audispd: node=gfs1.example.co.uk type=ANOM_ABEND msg=audit(1567658629.399:2444180): auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:ganesha_t:s0 pid=16997 comm="ganesha.nfsd" reason="memory violation" sig=11

Sep  5 05:43:49 gfs1 systemd: nfs-ganesha.service: main process exited, code=killed, status=11/SEGV

Sep  5 05:43:49 gfs1 systemd: Unit nfs-ganesha.service entered failed state.

Sep  5 05:43:49 gfs1 systemd: nfs-ganesha.service failed.
```
-------------------------------------------------------------------------------------

Has this been seen before? We are using **nfs-ganesha-gluster-2.5.5-1.el7.x86_64**

Thanks

Lewis

**Comment by soumyakoduri** [comment] 2019-09-06 12:46
If you have a core, could you paste the 'bt'. Until we know why the process crashed, cannot confirm if the issue is seen already. 

Also nfs-ganesha-2.5.x is not maintained anymore. Could you please upgrade to latest V2.7-stable or V2.8 ?

**Comment by lewisstrong1991** [comment] 2019-09-06 12:57
Thanks @soumyakoduri, unfortunately core dumps were disabled at the time of the crash. I'll look to enable this if possible to get a backtrace of the dump.

We can also look to upgrade when possible to the latest version as you mention.

**Comment by ffilz** [comment] 2020-07-14 21:30
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed as completed by ffilz** 2020-07-14 21:30 UTC
