### ISSUE TITLE
Failing to AddExport or UpdateExport over dbus calls

### ISSUE THREAD

**Issue by silvacarloss** [nfs-ganesha/nfs-ganesha#999] opened 2023-09-12 19:34 UTC
Hello, I'm currently using Ganesha 5.1 and have a deployment with OpenStack Manila consuming it.

We are running into an issue in OpenStack Manila while attempting to send dbus calls to AddExport or UpdateExport that throws an [exception](https://paste.opendev.org/show/bIwoMml92G69M42B5Nug/).

In summary, the exception shows:
`2023-09-12 18:25:06.234 6 ERROR oslo_messaging.rpc.server Stderr: 'Error org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable\n'`

So when we increased the logs verbosity and checked the Ganesha logs, [this error](https://paste.opendev.org/show/bktNx5M1Anfq6r1QSWem/) was shown in the logs. Apparently, one minute after this, the service [restarted](https://paste.opendev.org/show/bPhDzKIa449sBjRJyqwW/).

**Comment by ffilz** [comment] 2023-09-12 23:51
Oh, you need at least Ganesha V5.2, there was a known bug in V5.1 that inevitably caused crashes... Please try Ganesha V5.5

I'm not sure if that's the cause of your dBus problem.

**Comment by ffilz** [comment] 2024-02-21 00:55
Can we close this?

**Comment by gouthampacha** [comment] 2024-02-21 02:50
Yes; we don't see this issue on nfs-Ganesha 5.2+ we can close this

**Closed as completed** 2024-02-21 15:57 UTC
Labels: Try-on-supported-version, Can we close?
