### ISSUE TITLE
Ganesha service can’t listen both ipv4 and ipv6 at the same time?

### ISSUE THREAD

**Issue by zanglinjie** [nfs-ganesha/nfs-ganesha#301] opened 2018-06-05 09:40 UTC
Hey,
V2.6.1
I am experiencing issues with ipv6/v4 when using NFS Ganesha. If I set the v6disable=false (use tcp6 ok)within the EXPORT block, the client use ipv6 format mount can connect. 
The issues:
For example the Client 
mount -t nfs 100.7.4.1:/nfs /mnt/test1 -o vers=3 
mount -t nfs [fe80::20c::29ff:fe26:5f62%eno16777984]:/nfs /mnt/test2 -o vers=3
use"ss -6" “ss -4”, listen ipv4 ,ipv6  respectively.

However ,the server 
both listen tcp6,  not tcp4

**Comment by dang** [comment] 2018-06-05 13:04
If ganesha is listening on v6, it's listening on both.  IPv4 addresses get automatically converted to 4-in-6 addresses in the format ffff::ddd.ddd.ddd.ddd and arrive to Ganesha as IPv6.  So the question is not v4 or v6, it's v4 only or both.

**Comment by zanglinjie** [comment] 2018-06-06 06:41
Thank you for your help.@dang
If ganesha is listening on v6, the client have both ipv4 and ipv6 requests and arrive to Ganesha as only IPv6.
**Can Ganesha parse ipv4 ,ipv6 respectively? Do not converted to 4-in-6, when v6disable=false (use tcp6 ).** 
**Because the format ffff::ddd.ddd.ddd.ddd are problems in high availability scenarios .**

**Comment by dang** [comment] 2018-06-06 13:33
No, because this isn't up to Ganesha, it's done automatically by the kernel.  This is how IPv6 was designed to work.  All standard libraries properly handle the 4in6 addresses, so it should be doable.

**Comment by ffilz** [comment] 2018-06-06 13:53
Ganesha does convert the 4in6 addresses to plain 4 for CIDR comparison for EXPORT/CLIENT matching.

**Comment by ffilz** [comment] 2020-06-15 23:24
Closing this due to age, feel free to re-open if it's still of interest and you have explored using a currently supported version of Ganesha (V2.8 or V3 at this time).

**Closed by ffilz** 2020-06-15 23:24 UTC
