### ISSUE TITLE
Issue with NFS-Ganesha Release = V2.7.1 when Filesystem_id = 152.152

### ISSUE THREAD

**Issue by rolnick** [nfs-ganesha/nfs-ganesha#615] opened 2020-07-18 11:25 UTC
Hi,
We are using NFS-Ganesha as NFS provisioner(ranchercharts/kubernetes_incubator-nfs-provisioner:v2.2.1-k8s1.12) for our clusters.
We have deployment which contains hundreds of pods and many deployments. We easily hits 200 PV on cluster.
For some unknown reason we saw in logs:

>  error writing ‘test’: File too large

And all files inside NFS share had only 512 bytes (512 B).
After some further investigation, we saw some patern in Ganesha configuration:
```
EXPORT
{
        Export_Id = 152;
        Path = /export/pvc-6d18a542-13fd-4606-9d26-4ec1cb60005b;
        Pseudo = /export/pvc-6d18a542-13fd-4606-9d26-4ec1cb60005b;
        Access_Type = RW;
        Squash = no_root_squash;
        SecType = sys;
        Filesystem_id = 152.152;
        FSAL {
                Name = VFS;
        }
}
```
If export contains Filesystem_id = 152.152, error occours:
```
[root@somePC vol]# dd if=/dev/sda of=test bs=1 count=5120
dd: error writing ‘test’: File too large
513+0 records in
512+0 records out
512 bytes (512 B) copied, 0,0074975 s, 68,3 kB/s
```

where vol is mounted NFS share.

If i change Filesystem_id = 153.152 Everything works.

Regards

**Comment by dang** [comment] 2020-07-20 12:33
152.152 is the default root filesystem.  It's not a real filesystem, but an in-memory PSEUDO filesystem.  You'll have to avoid that ID for now.  @ffilz This doesn't seem a great idea.  Can we get rid of the specific ID?  Or change it to UINT64_MAX/UINT64_MAX?

**Comment by ffilz** [comment] 2020-07-20 14:12
I'm not quite sure why we picked 152.152 (other than that it has been the Filesystem_id from the beginning of the nfs-ganesha project), but yes, that is the fsid used for the default PseudoFS.

It is configurable however, all you have to do is provide an explicit FSAL_PSEUDO config block:

EXPORT {
    Export_Id=0;
    Path="/";
    Pseudo="/";
    Access=MDONLY_RO;
    Protocols=4;
    SecType=none,sys,krb5,krb5i,krb5p; # actually just has to list all the SecTypes used by your exports
    Filesystem_Id=x.y; # some value that doesn't conflict
    FSAL {
        Name=PSEUDO;
    }
}

However another question is why you actually need to specify the Filesystem_Id at all. FSAL_VFS will use the UUID or device ID of the underlying filesystem for Filesystem_Id if it's not configured. The primary reason to specify Filesystem_Id is if our POSIX filesystem processing can not identify a unique stable filesystem id (which I will grant MAY be the case in a Kubernetes environment).

One trouble with changing Ganesha's default on this is that it would change the pseudofs for all existing installs that subsequently upgraded to whichever version of Ganesha such a change went into.

**Comment by rolnick** [comment] 2020-07-20 14:53
Hi,
I am not configuring anything, i use default configuration.
What i see from source code:
[kubernetes-incubator L176](https://github.com/kubernetes-incubator/external-storage/blob/5c38d738d49dd6c7b1f1ad9de2583f56693bd18d/nfs/pkg/volume/export.go#L176).

I think i need to rise this issue too.

**Comment by ffilz** [comment] 2020-07-20 17:11
So I see that script is using exportid:exportid for Filesystem_id. Do you have any idea why it is doing this? If the backend filesystem has a stable and unique UUID, it is best to not specify the Filesystem_Id parameter. If UUID is not available but the filesystem is mounted on a consistent device id, it is best to allow nfs-ganesha to use that as the Filesystem_Id.

The Filesystem_Id parameter is to some extent a legacy parameter, though it is still useful for filesystems that don't have a stable UUID or device id or similar the FSAL can use to fill in the NFS fsid attribute. The default Pseudo File System is one such thing since it's created anew each time in memory, there is no stable ID to use. Since the PseudoFS had been assigned Filesystem_Id 152:152 back in the days when fsid ONLY came from the Filesystem_Id parameter and not from the backend filesystem it made sense to continue to use 152:152.

If your setup is dependent on continuing to use export_id:export_id as the Filesystem_Id, you can explicitly configure the Pseudo File System as I described above, giving it a Filesystem_Id that will not conflict with your Kubernetes assigned values (you could use 65536:65536 for example since Export_Id is only 16 bit... Note that if you change this, any clients that have PseudoFS inodes cached will see their fsid change which may cause some confusion. The explicitly configured Pseudo FS will be constructed in memory from the Pseudo paths specified in the exports the same way it is constructed if you don't specify it and allow Ganesha to build the default Pseudo FS export. The only constraints in defining your own Pseudo FS export is that the Pseudo path MUST be "/" (otherwise Ganesha will create the default Pseudo FS root filesystem) and it must be exported with Protocols=4 and it SHOULD have a Filesystem_Id (otherwise I think it will end up defaulting to 0:0). It should be MDONLY_RO but nothing will break if it isn't (it will never have any regular files, so RO vs MDONLY_RO doesn't actually make a difference. If you make it RW in any way, you can create directories and rename directories and change attributes of directories from the client (which might break something...).

**Comment by rafal-prasal** [comment] 2020-07-21 05:20
hey ffilz

We do not setup anything within ganesha on our own. we are using it as built in service in nfs-provisioner, which is creating this configuration for ganesha automatically, when there is persistent volume claim in k8s.

we need to update the nfs-client-provisioner then to change this particular default to 65536

can you please provide the sample config for that?

Thank you

**Comment by rafal-prasal** [comment] 2020-07-21 09:49
After some digging this 152 is an arbitrary number which cannot be changed with the configuraiton.
it can be always recoded to UINT16_MAX


src/support/exports.c

```
    LogDebug(COMPONENT_EXPORT,
         "Allocating Pseudo root export");
    export = alloc_export();

    export->filesystem_id.major = 152;
    export->filesystem_id.minor = 152;

```

**Comment by ffilz** [comment] 2020-07-21 13:58
The problem is recoding changes the fsid for in use installations that subsequently upgrade. This is likely to cause problems on clients preventing seamless "rolling" upgrades.

But it's also wrong that it isn't configurable. While the constant is hard coded with no configuration, it is used in the function that creates the default PseudoFS. That code doesn't execute if the PseudoFS is explicitly defined in the config file as I mentioned above, in which case the Filesystem_Id of the PseduoFS comes from the config file and need not be 152:152.

Now we could make changing this one parameter for the PseudoFS a little easier by making a config variable for the value.

But I still wonder if you REALLY need the Filesystem_Id parameter in your provisioned exports.

**Comment by rolnick** [comment] 2020-07-23 19:07
Hi,

Thank you for example. I was able to setup it. Works like charm.
One draw back is that I need to make this change manually in docker container each time when i am deploying nfs-provisioner on a big cluster.
```
EXPORT
{
        # Export Id (mandatory, each EXPORT must have a unique Export_Id)
        Export_Id = 0;
        # Exported path (mandatory)
        Path = "/";
        # Pseudo Path (required for NFS v4)
        Pseudo = "/";
        # Required for access (default is None)
        # Could use CLIENT blocks instead
        Access_Type = MDONLY_RO;
        Protocols = 4;
        SecType = none,sys,krb5,krb5i,krb5p;
        Filesystem_Id = 6500.1;
        FSAL {
                Name = PSEUDO;
        }
}
```
About Filesystem_Id, I will try to test it. 
I would like to not build new docker image with nfs-provisioner, as do I not have time to support it.

Regards,
Lukasz

**Comment by ffilz** [comment] 2020-07-24 16:56
Do you know who put nfs-provisioner together? I'd really like to understand why it is specifying Filesystem_Id which has been a discouraged option for years...

**Comment by ffilz** [comment] 2020-07-30 20:54
I commented in this issue: https://github.com/kubernetes-incubator/external-storage/issues/1345

I would like to make sure we have a satisfactory resolution here before closing.

**Comment by ffilz** [comment] 2020-08-07 20:41
Opened a new issue https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/issues/7

**Comment by ffilz** [comment] 2020-08-13 22:57
I tried a couple ways to get this issue resolved in the provisioner and I don't see any movement there. If no further action occurs within 30 days I will close this issue. For now, I will mark it will not fix.

**Comment by ffilz** [comment] 2020-11-10 00:41
Closing as resolved.

**Closed as completed by ffilz** 2020-11-10 00:41 UTC
Labels: Question, Wontfix
