### ISSUE TITLE
Copying binary file from nfs client to share is not executing in ganesha(server) node

### ISSUE THREAD

**Issue by skmprabhu22** [nfs-ganesha/nfs-ganesha#871] opened 2022-11-01 06:43 UTC
Ganesha version 4.0.9
FSAL : VFS

Steps to create the issue:
1. mount nfs share on client node
2. copy local binary to nfs share
  $  cp /usr/bin/ls ls
   ==> I dont see any issue with this step. The binary file is executing in nfs client as well as nfs server. 
3. again, copy ls command. 
    $ cp /usr/bin/ls ls
     cp: overwrite ‘ls’? y
=> After above copy, binary file is executing in nfs client, but _bot_ in nfs server. Getting below error in server node
$ ./ls
bash: ./ls: Text file busy

It seems ganesha doesn't close File FD in server. 

$vlsof -p 20775 | grep test
ganesha.n 20775 root    4r      DIR              253,2       62 806593206 /home/pmurugesan/testexp
ganesha.n 20775 root   31u      REG              253,2   117608   5832223 /home/pmurugesan/testexp/exp1/ls

from below logs, close request sent to server. 
$ tshark -tad -r /tmp/trc.pcap | grep NFS | egrep "OPEN|CLOSE"
417 2022-11-01 01:59:17 10.36.80.147 -> 10.36.80.147 NFS 304 V4 Call OPEN DH: 0xa515fd69/ls
418 2022-11-01 01:59:17 10.36.80.147 -> 10.36.80.147 NFS 412 V4 Reply (Call In 417) OPEN StateID: 0x0155
425 2022-11-01 01:59:17 10.36.80.147 -> 10.36.80.147 NFS 248 V4 Call CLOSE StateID: 0x0155
427 2022-11-01 01:59:17 10.36.80.147 -> 10.36.80.147 NFS 204 V4 Reply (Call In 425) CLOSE

move (mv) command is working fine.

**Comment by ffilz** [comment] 2022-11-01 17:30
OK, replicated and I see the cause, now to find a fix...

Stateless setattr is opening the global fd. I'm still not quite sure why that causes problems with local execution, I'll have to check nfsv3 copy of a binary to see if that works after fixing setattr.

**Comment by ffilz** [comment] 2022-11-01 20:48
OK, I have a fix for NFSv4, we were expecting a Read/Write fd for SETATTR truncate (uses a stateid), but if the stateid is write only (which is the case for the scenario of cp) then we didn't use the stateid fd for the truncate and instead opened the global fd rdwr and then the global fd remains open...

Now that doesn't fix NFSv3 where you can't even execute a binary copied the first time... The problem is again the global fd, but in this case, we opened the global fd to copy the file...

I'm going to do an experiment and see if closing the global fd when we SETATTR with an executable bit set will resolve the problem.

**Comment by ffilz** [comment] 2022-11-01 22:50
So we have a problem, the SETATTR comes before the WRITE calls. We don't know when writing to the file is complete...

**Comment by ffilz** [comment] 2022-11-02 17:14
So I see no solution for NFSv3, but I would offer the following comments based on IRC conversation:

It's probably not wise to use NFS to push files onto a server that will be executed locally on the server.

If that IS important, using NFSv4 works.

If NFSv3 is required, a work around is to set the number of file descriptors low enough that the client can sort of force LRU to close the executable file by causing enough other files to be opened as to use fds in a way that causes LRU to work on closing open fds and closing the executable file in a reasonable time frame.

A call out to developers of things like the cp command... If the executable mode bits were set AFTER writing the file, Ganesha COULD trigger closing the fd after the SETATTR that sets the executable mode bit(s).

**Comment by ffilz** [comment] 2022-11-15 15:16
Patch for V4 fix: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/545617

**Comment by skmprabhu** [comment] 2022-11-17 13:22
Above patch is not working. I'm able to recreate the issue with above patch. 
kindly let me know if you need more logs/info.

**Comment by ffilz** [comment] 2022-11-17 16:14
Oops. I didn't change FSAL_GPFS with that patch...

**Comment by ffilz** [comment] 2022-11-17 16:38
OK, so FSAL_GPFS doesn't use the global fd for setattr. It will take debugging on GPFS to understand why there is an fd open for write on the file. With NFSv4, the client should be writing using the stateid, and then closing, so the file I/O is occurring on an fd that is closed when the client closes.

**Comment by ffilz** [comment] 2022-11-17 16:39
I suggest using GPFS tracing to determine where the open fd is coming from.

**Comment by skmprabhu** [comment] 2022-11-18 06:56
Hi Frank, 

I'm using VFS FSAL  and ganesha build version is 4.0.9. I just cherry-picked patch and tested. The issue is not fixed. 
Am i missing something here? Kindly let me know. 
I'll debug SETATTR call and post here if I find anything interesting. 

Thanks,
Prabhu

**Comment by ffilz** [comment] 2022-11-18 16:41
Oh, sorry, I keep forgetting you've switched from GPFS team...

Please do some debug, I tested and it worked for me. There may be some other issue.

**Comment by skmprabhu** [comment] 2022-11-22 15:03
My apologies for confusion..

I have retested the fix and it is working fine. 

Thank you very much for the fix. 

We can close the issue now.

**Comment by ffilz** [comment] 2022-11-28 17:52
Thanks

**Closed as completed by ffilz** 2022-11-28 17:52 UTC
Labels: Bug, Verified

**Comment by deepanshuwadhwa7** [comment] 2023-02-02 10:11
@ffilz  @skmprabhu22 
we did merge the patch in our ganesha repository and post that we were experimenting with ganesha and other executable files and we hit the error again 

Steps ->

1. mount nfs export using nfsv4 on a client
2. ran - singularity pull docker//centos:latest ->

```
[root@wosbmk131 test]# singularity pull docker://centos:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...

Getting image source signatures

Copying blob a1d0c7532777 done

Copying config 8c1402b22a done

Writing manifest to image destination

Storing signatures
2023/02/02 08:48:06  info unpack layer: sha256:a1d0c75327776413fa0db9ed3adcdbadedc95a662eb1d360dad82bb913f8a1d1
INFO:    Creating SIF file...

```

3. tried to execute the file on lustre client

```
[root@machine157 ~]# cd /mnt/lustre2/mac5758/nfs
[root@machine157 nfs]# ls
centos_latest.sif
[root@machine157 nfs]# ./centos_latest.sif
-bash: ./centos_latest.sif: /usr/bin/env: bad interpreter: Text file busy
[root@machine157 nfs]# strace ./centos_latest.sif
execve("./centos_latest.sif", ["./centos_latest.sif"], 0x7ffc21d80030 /* 29 vars */) = -1 ETXTBSY (Text file busy)
strace: exec: Text file busy
+++ exited with 1 +++

```
4. ganesha lsof output

```
[root@nsds1 yum.repos.d]# ps aux | grep ganesharoot         945  0.0  0.0 1551284 21932 ?       Ssl  08:41   0:01 /usr/bin/ganesha.nfsd -C -L /var/log/ganesha.log -f /etc/ganesha/ganesha.conf -N NIV_EVENTroot       22573  0.0  0.0  10708  2228 pts/0    S+   09:20   0:00 grep --color=auto ganesha
[root@nsds1 yum.repos.d]# lsof -p 945 | grep centosganesha.n 945 root   31w      REG        3318,486100 79540224 144115574522249251 /mnt/lustre2/mac5758/nfs/centos_latest.sif

```
5. Also to be noted, we did try out to reproduce the issue with copying /usr/bin/ls and it did work out fine. We faced issue with the singularity pulled file.

```
nfs client ->
[root@wosbmk131 test]# ls
centos_latest.sif            index.html          releases    singularity-ce-3.10.5-1.el7.x86_64.rpm
ganesha.log.1649074099.fail  linux_ex_only.html  repomd.xml
[root@wosbmk131 test]# cp /usr/bin/ls my_ls

lustre client ->
[root@machine157 /]# cd /mnt/lustre2/mac5758/nfs
[root@machine157 nfs]# ls
centos_latest.sif            index.html          my_ls     repomd.xml
ganesha.log.1649074099.fail  linux_ex_only.html  releases  singularity-ce-3.10.5-1.el7.x86_64.rpm
[root@machine157 nfs]# ./my_ls
centos_latest.sif	     index.html		 my_ls	   repomd.xml
ganesha.log.1649074099.fail  linux_ex_only.html  releases  singularity-ce-3.10.5-1.el7.x86_64.rpm

```


Can you please check it once more with the above scenario?
All testing is done with nfsv4.

Singularity ->
Dependencies -
https://docs.sylabs.io/guides/3.5/admin-guide/installation.html
Rpms -
https://github.com/sylabs/singularity/releases

**Comment by deepanshuwadhwa7** [comment] 2023-02-03 06:14
Hi @ffilz  @skmprabhu @skmprabhu22  @mschwenke-ddn 

We tried to recreate the scenario with executable files of different size and below are the observations

Nfs client  (CentOS7.9)
```
[root@wosbmk131 ~]# ls -lrt zeroes-104857*
-rwxr-xr-x 1 root root 1048576 Feb  3 06:04 zeroes-1048576.sh
-rwxr-xr-x 1 root root 1048577 Feb  3 06:04 zeroes-1048577.sh
[root@wosbmk131 ~]# cp zeroes-104857* /mnt/test
[root@wosbmk131 ~]# hexdump -C zeroes-1048576.sh | head
00000000  23 21 2f 62 69 6e 2f 73  68 0a 65 78 69 74 0a 00  |#!/bin/sh.exit..|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
000ffff0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 0a  |................|
00100000

```

Lustre Client ->

```
[root@machine157 ~]# /mnt/lustre2/mac5758/nfs/zeroes-1048576.sh
[root@machine157 ~]# /mnt/lustre2/mac5758/nfs/zeroes-1048577.sh
-bash: /mnt/lustre2/mac5758/nfs/zeroes-1048577.sh: /bin/sh: bad interpreter: Text file busy

```
##these are simple shell scripts that exit padded out with nulls to desired length
##1048576 = 1M
##1048577 >1M


So it looks like If the file size exceeds 1M, we hit the “Text File busy” error (so nothing to do with singularity, any executable bigger than the 1M size gives us the error)

Attached are the shell files ->
[zeroes-1048576.sh.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/10576047/zeroes-1048576.sh.gz)
[zeroes-1048577.sh.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/10576048/zeroes-1048577.sh.gz)

**Comment by ffilz** [comment] 2023-02-03 15:46
That's definitely a different problem, could you please open a new issue? It's much easier to track things when distinct issues are tracked separately.

**Comment by deepanshuwadhwa7** [comment] 2023-02-05 13:33
> That's definitely a different problem, could you please open a new issue? It's much easier to track things when distinct issues are tracked separately.


Link to new issue -https://github.com/nfs-ganesha/nfs-ganesha/issues/902
