### ISSUE TITLE
ganesha + cephfs + rgw

### ISSUE THREAD

**Issue by tony-yin** [nfs-ganesha/nfs-ganesha#227] opened 2017-11-04 13:55 UTC
`cmake -DUSE_FSAL_RGW=ON -DUSE_FSAL_CEPH=ON ../src/` run normally 
![image](https://user-images.githubusercontent.com/18906553/32405970-6aa7c316-c1aa-11e7-87dd-3faef5aca51e.png)

But when run  `make`, it show error at process 79%
![image](https://user-images.githubusercontent.com/18906553/32405985-ceddb462-c1aa-11e7-93d5-c9fb9eaf9b24.png)

version is v2.4stable

**Comment by taoCH** [comment] 2017-11-06 02:03
You should make sure that your Ceph is compatible with ganesha v2.4 stable. You could check this here [wiki](https://github.com/nfs-ganesha/nfs-ganesha/wiki)

**Comment by dang** [comment] 2017-11-06 14:31
The problem is that 2.4 is old, and newer ceph doesn't work with it.  The cmake checks check minimum versions, since maximum versions aren't known at the time a release is made.  This means that, when a new version of ceph changes in an incompatible way, there's no way for an old version of ganesha's cmake to know that.

**Comment by tony-yin** [comment] 2017-12-07 02:44
thanks, i have changed version from 2.4 to 2.5, and it works. This issue can be closed. But i suggest that if nfs-ganesha can show the version map between ceph or other and ganesha in wiki, it'll be more helpful.

**Comment by supriti** [comment] 2018-02-13 09:21
Closing the issue. I have added a card to track the issue of adding wiki entry that shows the compatible versions for FSAL/NFS-Ganesha

**Closed by supriti** 2018-02-13 09:21 UTC
