### ISSUE TITLE
Add POSIX ACL support to FSAL_VFS [was nfs4_getfacl: Operation to request attribute not supported.]

### ISSUE THREAD

**Issue by coolinger** [nfs-ganesha/nfs-ganesha#518] opened 2019-12-05 15:54 UTC
Hi,

I just switched from nfs-kernel-server to nfs-ganesha, and now I am encountering the problem that the extended ACLs are not mapped. I am using Ubuntu Bionic with the ~nfs-ganesha ppa from launchpad.

I tried ganesha 2.8 and 3.0. Current ganesha.conf is bare minimum, just replaced the path to the filesystem and added FULL_DEBUG . Filesystem is ext4, also tried xfs. getfacl and setfacl works on filesystem.

I set the ACL on the filesystem.

```
> getfacl /storage/local/test
getfacl: Removing leading '/' from absolute path names
# file: storage/local/test
# owner: root
# group: root
user::rw-
user:lohr:rwx
group::r--
mask::rwx
other::r--
```

mountstats shows for this mount:
> NFS mount options: rw,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,acregmin=3,acregmax=60,acdirmin=30,acdirmax=60,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.24.20.129,local_lock=none
> NFS server capabilities: caps=0x1fbffd7,wtmult=512,dtsize=32768,bsize=0,namlen=255
> NFSv4 capability flags: bm0=0xfdff8fff,bm1=0x40f9be3e,bm2=0x802,acl=0x1,sessions,pnfs=notconfigured
> NFS security flavor: 1  pseudoflavor: 0

I think the NFSv4 capability flags/acl should be 0x3?

What am I missing?

Many thanks!

Attached the config and a log consisting of server start, mount, nfs4_getfacl command and server stop.
[ganesha.conf.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/3927780/ganesha.conf.gz)
[ganesha.log.gz](https://github.com/nfs-ganesha/nfs-ganesha/files/3927781/ganesha.log.gz)

**Comment by dang** [comment] 2019-12-05 16:16
The problem is that NFS ACLs are not Linux ACLs, and mapping between them is difficult.  There is experimental code in FSAL_VFS to do this mapping, but it's not enabled by default.  You can turn it on with the ENABLE_VFS_DEBUG_ACL build option to cmake.

**Comment by ffilz** [comment] 2020-07-14 23:47
In theory we could hook FSAL_VFS up to the same POSIX<->NFS4_ACL code FSAL_GLUSTER uses to implement this, but we currently don't have plans to do so.

Feel free to re-open if you still require this functionality and we will consider if it's something we can commit to doing.

**Comment by Keeper-of-the-Keys** [comment] 2021-11-09 09:23
This would be a very cool feature to have, we're using nfs-ganesha to access a lustre system and are also playing around with gluster and for both having linux acls available/enforced on clients that can't connect using native clients for whatever reason would be awesome.

**Comment by ffilz** [comment] 2021-11-09 14:55
I'll re-open this as an enhancement.

FSAL_GLUSTER does have ACL support.

Perhaps someone could step up to hook FSAL_VFS to the POSIX ACL handling.

**Comment by Keeper-of-the-Keys** [comment] 2021-11-12 13:47
Cool thanks!

**Comment by ffilz** [comment] 2021-11-12 15:27
Note that this being listed as an enhancement is no guarantee anyone will work on it. If it's something you want to work on, we always welcome new contributors. I don't think this will actually be all the hard, mostly just wiring up FSAL_VFS to existing code (and a conversation about what to do with the ACL test code that's in FSAL_VFS - one option is to move that to FSAL_MEM).

**Comment by mathrock74** [comment] 2023-04-18 13:42
Just in case someone looking for ACL support in FSAL_VFS ends up here (like I did):
since nfs-ganesha 4.1 this seems to be supported: https://github.com/nfs-ganesha/nfs-ganesha/wiki/ReleaseNotes_4#user-content-New_Features_in_V41

IMHO this issue should be closed

**Comment by ffilz** [comment] 2023-04-18 19:04
> Just in case someone looking for ACL support in FSAL_VFS ends up here (like I did): since nfs-ganesha 4.1 this seems to be supported: https://github.com/nfs-ganesha/nfs-ganesha/wiki/ReleaseNotes_4#user-content-New_Features_in_V41
> 
> IMHO this issue should be closed

Oops, sorry, my right hand can't keep track of what my left hand is doing... :-)

Yes, this is implemented. Closing.

**Closed as completed by ffilz** 2023-04-18 19:04 UTC
Labels: Enhancement, Patch Submitted
