### ISSUE TITLE
Compile failure with GCC 6 and -Werror

### ISSUE THREAD

**Issue by rossburton** [nfs-ganesha/nfs-ganesha#355] opened 2018-10-05 14:36 UTC
When building ganesha:

```
| <snip>/nfs-ganesha-2.7.0/src/Protocols/NFS/nfs_proto_tools.c: In function ‘decode_change’:
| <snip>/recipe-sysroot-native/usr/include/ntirpc/rpc/xdr_inline.h:158:32: error: ‘change’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
|    u[0] = (uint32_t) (*uint64_p >> 32) & 0xffffffff;
|                      ~~~~~~~~~~~^~~~~~
| <snip>nfs-ganesha-2.7.0/src/Protocols/NFS/nfs_proto_tools.c:517:11: note: ‘change’ was declared here
|   uint64_t change;
|            ^~~~~~
```

**Comment by dang** [comment] 2018-10-05 14:54
So, I don't see this on my rawhide machine with
gcc (GCC) 8.2.1 20180905 (Red Hat 8.2.1-3)

What version, exactly, do you have?

**Comment by rossburton** [comment] 2018-10-05 21:28
My mistake, wrong compiler.  gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by rossburton** [comment] 2018-10-05 21:29
Also 2.7.0 tarball, in case there are related changes in git.

**Comment by dang** [comment] 2018-10-08 14:41
Okay, I can't reproduce on any system I have access to.  Can you test with this patch:
https://github.com/dang/nfs-ganesha/commit/4c2908e134f7c4286389779c2722811f4039b981

**Comment by rossburton** [comment] 2018-10-10 09:38
Yes, that fixes it.

However:

```
| FAILED: FSAL/FSAL_PROXY/CMakeFiles/fsalproxy.dir/handle.c.o
| /data/poky-tmp/master/hosttools/gcc -D_GNU_SOURCE -D__USE_GNU -Dfsalproxy_EXPORTS -Iinclude -I/data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/nfs-ganesha-2.7.0/src/include -I/data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/nfs-ganesha-2.7.0/src/include/os/linux -I/data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/recipe-sysroot-native/usr/include/ntirpc -isystem/data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/recipe-sysroot-native/usr/include -O2 -pipe -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Werror -Wall -Wimplicit -Wformat -Wmissing-braces -Wreturn-type -Wunused-variable -Wuninitialized -Wno-pointer-sign -Wno-strict-aliasing -g -fPIC -MD -MT FSAL/FSAL_PROXY/CMakeFiles/fsalproxy.dir/handle.c.o -MF FSAL/FSAL_PROXY/CMakeFiles/fsalproxy.dir/handle.c.o.d -o FSAL/FSAL_PROXY/CMakeFiles/fsalproxy.dir/handle.c.o   -c /data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/nfs-ganesha-2.7.0/src/FSAL/FSAL_PROXY/handle.c
| /data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/nfs-ganesha-2.7.0/src/FSAL/FSAL_PROXY/handle.c: In function ‘pxy_lookup_impl’:
| /data/poky-tmp/master/work/x86_64-linux/nfs-ganesha-native/2.7.0-r0/nfs-ganesha-2.7.0/src/FSAL/FSAL_PROXY/handle.c:1366:17: error: ‘atok_per_file_system_attr’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
|   GETATTR4resok *atok_per_file_system_attr;
|                  ^~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rossburton** [comment] 2018-10-10 09:41
Looks like a simple NULL default would solve that one too.

**Comment by rossburton** [comment] 2018-10-10 09:43
Good news: with this patch to FSAL_PROXY/handle.c:

```
-	GETATTR4resok *atok_per_file_system_attr;
+	GETATTR4resok *atok_per_file_system_attr = NULL;
```

I have a success compile.

**Comment by dang** [comment] 2018-10-11 13:45
This one is definitely a compiler bug, which explains why later version don't complain.  I've submitted this fix:
https://review.gerrithub.io/#/c/ffilz/nfs-ganesha/+/428978

**Comment by ffilz** [comment] 2020-06-15 23:44
Closed as resolved.

**Closed by ffilz** 2020-06-15 23:44 UTC
