### ISSUE TITLE
DBus failed to start in containerized nfs-ganesha.

### ISSUE THREAD

**Issue by supriti** [nfs-ganesha/nfs-ganesha#637] opened 2020-10-07 11:06 UTC
We are deploying FSAL Ceph using cephadm, that deploys nfs-ganesha in a container. 

The log file contains 
```
ganesha.nfsd-1[main] gsh_dbus_pkginit :DBUS :CRIT :dbus_bus_get failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
ganesha.nfsd-1[main] gsh_dbus_register_path :DBUS :CRIT :dbus_connection_register_object_path called with no DBUS connection
ganesha.nfsd-1[main] nfs_Init_svc :DISP :CRIT :Cannot acquire credentials for principal nfs
ganesha.nfsd-1[dbus] gsh_dbus_thread :DBUS :CRIT :DBUS not initialized, service thread exiting
ganesha.nfsd-1[dbus] gsh_dbus_thread :DBUS :EVENT :shutdown
```

I have few basic questions.
1. Is DBus used only for collecting stats in nfs-ganesha code? We are not using stats anywhere. So maybe it make sense to compile without DBus.
2. Does DBus require RPC services? I think as we are running in container it fails to get started because of missing RPC services.

**Comment by dang** [comment] 2020-10-07 14:25
DBus is used for a lot of things in Ganesha: collecting stats, controlling Grace/failover, config modification (such as adding/deleting exports and clients), and getting information such as client listings, cache contents, and so on.  So it's used for quite a bit.

It's not, however, required.  You can compile it out, and Ganesha will work correctly (although with more limited run-time interaction).  If you're using the FSAL_CEPH container-based HA, you'll need DBus, because that's how it's controlled.

DBus does require a service (the system DBus daemon) to work.  If that's not running inside the container, then the container needs to have access to the system DBus session outside the container.

**Comment by Davidrjx** [comment] 2020-11-16 02:27
https://github.com/nfs-ganesha/nfs-ganesha/issues/637#issuecomment-704972763
very good, i am new to ganasha NFS details. 
In containerd ganesha server, sometime mount.nfs would hang ,and only reboot can fix.
And strace "strace /bin/mount -t nfs -o retrans=2,rsize=1048576,soft,timeo=300,vers=4.2,wsize=1048576 \<ganeshaNFS server proxy IP\>:/ /mnt/" , but this case log shows stuck in wait4 syscall and vers changed to 3.0 not stuck, any guide will be appreciated

**Comment by dang** [comment] 2020-11-16 14:44
We're far from experts in the kernel client.  Strace showing wait4 is not very useful, at least we'd need to know what happened before the wait was called.  A better solution would be to get a packet trace between the client an the ganesha.

**Comment by Davidrjx** [comment] 2020-11-18 05:39
https://github.com/nfs-ganesha/nfs-ganesha/issues/637#issuecomment-728106812
in failed case, no any packets reached to egress gateway so no traffic can be captured.
currently, i think kernel client may be not compatible with ganeshaNFS server, just not sure.

**Comment by dang** [comment] 2020-11-18 15:01
The linux kernel client is pretty much the only client used with Ganesha, so it definitely works.  And, Ganesha has been used in containers in the past, so that also works.  Please open a new issue (so as to not hijack this one) and include as much info as you can.  Things like your host OS, what container system you're using, Ganesha version, where you're mounting from and it's kernel version, at least.

**Comment by Davidrjx** [comment] 2020-11-19 11:20
OK

**Comment by ffilz** [comment] 2020-11-19 22:06
Is the original question in this issue resolved?

**Comment by Davidrjx** [comment] 2020-11-26 08:39
hi, @ffilz, this issue has been move to #653, and this may be closed. My local reproduction and test yet continues with advice or guide from @dang.

**Comment by ffilz** [comment] 2020-11-30 16:01
Ok, with the new issue in it's own issue, and no action on the original, I'm going to close this.

If the original question is still relevant and unanswered, please re-open.

**Closed as completed by ffilz** 2020-11-30 16:01 UTC
Labels: Question

**Comment by chrispro-21** [comment] 2026-03-12 01:31
I am also having this issue with ceph 20.2.0. Was there a solve?
