### ISSUE TITLE
Nfs Ganesha fail to load export after changing export ID.

### ISSUE THREAD

**Issue by adirhaziz** [nfs-ganesha/nfs-ganesha#556] opened 2020-03-15 19:24 UTC
I am running nfs ganesha over wekaFS, version is (2.8.3-ubuntu1~xenial2).

My initial configuration file `/etc/ganesha/ganesha.conf` is:
```
NFS_CORE_PARAM
{
    Protocols = 3;
    mount_path_pseudo = true;
}

NFSV4 {
    GRACELESS = true;
}

EXPORT {
    Export_Id = 3;
    Path = "/tmp/wekafs/nfs_229_3/";
    Pseudo = "/default/";
    Protocols = 3;
    Access_Type = "none";

    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = *;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}
```

Now when trying to mount `/default/`, it works just fine.
```
\[root@adirnfs-0 ~] 2020-03-15 21:07:33 $ mount -t nfs -o vers=3 host-0:/default/ /mnt/nfs
[root@adirnfs-0 ~] 2020-03-15 21:07:43 $ mount -t nfs
host-0:/default/ on /mnt/nfs type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.31.25.222,mountvers=3,mountport=38362,mountproto=udp,local_lock=none,addr=172.31.25.222)
```

I am changing the export ID of this export from 3 to 4, and sending SIGHUP signal to ganesha  in order for it to reload the exports.
The state of the configuration file now:
```
NFS_CORE_PARAM
{
    Protocols = 3;
    mount_path_pseudo = true;
}

NFSV4 {
    GRACELESS = true;
}

EXPORT {
    Export_Id = 4; # <---------------------------
    Path = "/tmp/wekafs/nfs_229_3/";
    Pseudo = "/default/";
    Protocols = 3;
    Access_Type = "none";

    FSAL {
        Name = VFS;
    }

    CLIENT {
        Clients = *;
        Access_Type = "RW";
        Squash = No_root_squash;
        Anonymous_Uid = 65534;
        Anonymous_Gid = 65534;
        Manage_Gids = False;
    }
}
```

The command used to send the signal:
`pkill ganesha --signal SIGHUP`

When trying to mount this path now, I fail on access denied:
```
mount -t nfs -o vers=3 host-0:/default/ /mnt/nfs
mount.nfs: access denied by server while mounting host-0:/default/
```

Looking at ganesha logs, I can see this errors:
```
15/03/2020 19:11:47 : epoch 5e69036f : adirnfs-0 : ganesha.nfsd-43[sigmgr] export_commit_common :CONFIG :CRIT :Pseudo path (/default) is a duplicate
15/03/2020 19:11:47 : epoch 5e69036f : adirnfs-0 : ganesha.nfsd-43[sigmgr] export_commit_common :CONFIG :CRIT :Duplicate export id = 4
15/03/2020 19:11:47 : epoch 5e69036f : adirnfs-0 : ganesha.nfsd-43[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): 1 validation errors in block EXPORT
15/03/2020 19:11:47 : epoch 5e69036f : adirnfs-0 : ganesha.nfsd-43[sigmgr] config_errs_to_log :CONFIG :CRIT :Config File (/etc/ganesha/ganesha.conf:16): Errors processing block (EXPORT)
```

Now after sending another SIGHUP, I am able to mount this path again:
```
root@adirnfs-0:/samba# pkill ganesha --signal SIGHUP

[root@adirnfs-0 ~] 2020-03-15 21:18:57 $ mount -t nfs -o vers=3 host-0:/default/ /mnt/nfs
[root@adirnfs-0 ~] 2020-03-15 21:19:11 $ mount -t nfs
host-0:/default/ on /mnt/nfs type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=172.31.25.222,mountvers=3,mountport=38362,mountproto=udp,local_lock=none,addr=172.31.25.222)
```

My theory is that Ganesha was first looking for new exports, and when it saw that there was new export ID with the same pseudo path as one it already knew it returned a failure. And only after that ganesha searches which exports have been deleted and deletes them. This is why In the second SIGHUP it succeeded to load the export.
Assuming 2 sighups is the only way around this - is there a way to make sure that the first one finished?

Looking for your response :)

**Comment by dang** [comment] 2020-03-16 18:16
Stop and restart... Or use a different pseudo path. In general, changing only the Export_id is going to be problematic.  In general, I'd say "don't do that".

**Comment by ffilz** [comment] 2020-03-16 18:47
You are right, the export_id 4 appears to be a new export. Since we haven't finished processing the export config, we can't prune old exports yet (export_id 3 will become old and eligible for pruning). This problem probably isn't worth trying to solve because we would have to make a first pass of the export config to see what exports will exist in the new schema, then remove any exports that won't exist, then process the new export file for real.

Unfortunately some kinds of export config changes will require a restart.

I am working in reducing the number of changes that require a restart because some other work made things easier, plus some of what needs to be done for export reload MUST be done for dbus single export removal.

Actually, you COULD accomplish this without a restart. Use dbus to remove export_id 3, then either use dbus to add export_id 4 or SIGHUP to reload the export config. If you have other exports this will be less disruptive and in fact, no more disruptive than necessary since the export_id goes into the handle, any clients that were mounted on export_id 3 will have stale file handles.

There are aspects even with remove followed by reload that may not work right now, but after I complete the work I have in progress, that scenario should fully work.

**Comment by adirhaziz** [comment] 2020-03-17 13:12
Thanks for the fast reply :)
The scenario I afraid of is that a user will remove an export and add a new one very fast, and the new export will receive the same export ID in our system. There is a chance that ganesha will receive an update of the configuration file only with the delta of the changes, and therefor what I described here might happend. So I must handle with this case.

I actually managed to accomplish this by sending two SIGHUP's, but there is a follow-up question. is there a way to make sure the first sighup finished before sending the scond one? to make sure both sighups will occure.

**Comment by ffilz** [comment] 2020-03-17 18:22
SIGHUP is handled by a single thread that uses sigwait to wait for SIGHUP and SIGTERM. This serializes handling of any number of these signals. I am working on code that introduces a mutex so that any export admin action will be serialized such that DBUS export admin actions will also be serialized with SIGHUP and SIGTERM.

**Comment by ffilz** [comment] 2020-04-17 21:14
Please have a look at this patch (and the other patches in the relation chain): https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/490334/

It may help your situation.

**Comment by ffilz** [comment] 2020-06-15 16:58
Watch for an updated patch set this week.

**Comment by ffilz** [comment] 2020-07-15 21:47
The export patches have been merged, please verify and report if the issue is not resolved otherwise please close it.

**Comment by ffilz** [comment] 2020-08-13 23:02
With some code changes that should mitigate this, and no action for nearly 30 days, I will close this as resolved.

**Closed as completed** 2020-08-17 19:05 UTC
