### ISSUE TITLE
FSAL_GLUSTER unable to copy files with 0444 permissions; Inconsistent with other FSALS or OS 

### ISSUE THREAD

**Issue by kriszentner** [nfs-ganesha/nfs-ganesha#262] opened 2018-02-15 23:26 UTC
This started with us attempting to perform a simple ```git clone``` on a mount shared by an nfs-ganesha Gluster FSAL which fails. I've tested this with nfs-ganesha 2.5 on Ubuntu 16.04, and nfs-ganesha 2.6rc3 on Debian stretch. This should be fairly easy to repro. This issue doesn't occur on the VFS FSAL, or obviously on the local filesystem. The issue also doesn't occur using the native GlusterFS FUSE client.

My ganesha.conf
```
EXPORT
{
        Export_Id = 1 ;   # Export ID unique to each export
        Path = "/glustest";  # Path of the volume to be exported. Eg: "/test_volume"

        FSAL {
                name = GLUSTER;
                hostname = "127.0.0.1";  # IP of one of the nodes in the trusted pool
                volume = "glustest";     # Volume name. Eg: "test_volume"
        }

        Access_type = RW;        # Access permissions
        Squash = no_root_squash; # To enable/disable root squashing
        Disable_ACL = TRUE;     # To enable/disable ACL
        Pseudo = "/glustest";    # NFSv4 pseudo path for this export. Eg: "/test_volume_pseudo"
        Protocols = "4" ;   # NFS protocols supported
        Transports = "TCP" ; # Transport protocols supported
        SecType = "sys";         # Security flavors supported
        CLIENT {
                 Clients = *;
        }
}
```
The core issue seems to be that you can't copy a file with perms 0444 from another file systom onto the NFS share, no can you copy that file within the share, which is what the git clone is essentially trying to do inside the _repository_/.git/objects directory. Technically it's the git/sha1_file.c code here. It attempts to create a tmp file, and then that file gets copied:
```
From:   git/sha1_file.c
  1527          strbuf_add(tmp, filename, dirlen);
  1528          strbuf_addstr(tmp, "tmp_obj_XXXXXX");
  1529          fd = git_mkstemp_mode(tmp->buf, 0444);
  1530          if (fd < 0 && dirlen && errno == ENOENT) {
```

Here's a little bash session on the nfs-ganesha share that also demonstrates the inconsistency. You can do this on the local filesystem, or using the VFS FSAL without the permission denied error.
```
$ touch file
$ echo "foo" >> file
$ chmod 444 file
$ cp file file2
cp: failed to close 'file2': Permission denied
```

**Comment by kriszentner** [comment] 2018-02-16 01:13
Additional information:
* This doesn't happen as root, only as a non-root user.

ganesha.log:
```
ganesha.nfsd-84188[work-4] glusterfs_close_my_fd :FSAL :CRIT :Error : close returns with Permission denied
```
ganesha-gfapi.log:
```
[2018-02-16 01:09:42.825988] E [MSGID: 114031] [client-rpc-fops.c:435:client3_3_open_cbk] 0-glustest-client-0: remote operation failed. Path: /testdir/file2 (87f82d48-6e60-4cd0-971b-beb98a3939df) [Permission denied]
```
T

**Comment by bhuntley** [comment] 2018-02-21 17:03
I've confirmed similar behavior with a small python script as well:
`#!/usr/bin/python
import os
os.umask(0)
with os.fdopen(os.open('/ganesha/gluster/scratch/test.txt', os.O_WRONLY | os.O_CREAT, 0o444), 'w') as fh:
  fh.write('test content')`

This behavior of being able to write to a read only file pointer succeeds when using either classic NFS, or the local file system.  As with Kris' bug statement, this is an issue for our group because it breaks git clone operations.

**Comment by rtheys** [comment] 2018-03-03 20:58
Hi,

I believe this is the same issue that I reported in the Red Hat bugzilla a few weeks ago.
https://bugzilla.redhat.com/show_bug.cgi?id=1543996

Regards,

Rik

**Comment by pablorsk** [comment] 2018-05-03 12:36
Temporary solution:

```bash
$ touch file
$ echo "foo" >> file
$ # chmod 444 file
$ # cp file file2
$ cat file > file2
$ ## checking if all it's ok
$ md5sum file
$ md5sum  file2
```

**Comment by soumyakoduri** [comment] 2019-09-13 11:05
Got a chance to debug this issue  .. have updated the RCA in bug1735480. Will update once the fixes are ready.

**Comment by memorais** [comment] 2019-10-13 18:53
I'm having this same error on Ganesha 2.8.2 and Gluster 6.5. This is already fixed? If yes, in which version?

Thanks.

**Comment by dang** [comment] 2019-10-14 13:59
It's fixed on next, which will be the next release (3.0, in this case).  It's in release candidate, but not yet out.  Some time in the next few weeks, we'll do a set of backports, and release a new 2.8 version.

**Comment by memorais** [comment] 2019-10-15 15:15
I did a backport of the following patches and the fix seems to work properly on my tests:

https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/468805
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/468806

If anyone it's interested you can check this:

https://github.com/memorais/nfs-ganesha/tree/V2.8-stable-fix-262

It also depend of the following patch to Glusterfs:

https://review.gluster.org/#/c/glusterfs/+/23448/

All that work was done by Soumya Koduri [1], I did some small changes to make it work properly on latest 2.8 code.

[1] - https://bugzilla.redhat.com/show_bug.cgi?id=1735480

**Comment by ffilz** [comment] 2020-07-14 21:56
Closed as resolved.

**Closed by ffilz** 2020-07-14 21:56 UTC
