### ISSUE TITLE
readdir by chunk is slow when the number of files is large. 

### ISSUE THREAD

**Issue by zhengfeihu51** [nfs-ganesha/nfs-ganesha#868] opened 2022-10-23 06:55 UTC
Here is my test scenario：
7 servers，14 clients，60 million files，dir_chunk of configuration file is set to 128, other parameter is default value,  it takes over 10 hour to finished readdir. 
Enable logging dynamically, chunks are frequently be set dirty and refill it again. How can I improve the performance of readdir？

**Comment by zhengfeihu51** [comment] 2022-10-25 01:16
Question is not clear

**Comment by dang** [comment] 2022-10-25 14:43
Readdir is difficult in the presence of changes.  We've tested huge directory listings on RGW, and it's fast when there's no changes to the directory (a few minutes for a static bucket) but slows down a lot when the directory is changing.

Then, too, different FSALs have different readdir speeds, depending on what APIs they support for readdir.  Which FSAL is this?

**Comment by zhengfeihu51** [comment] 2022-10-26 06:59
>the FSAL is cephfs, we creat and write a lots of file(60million files). After write file, we do readdir operation. It has no changes of files when readdir. 
I read the code of readdir by chunk, and make some tests, find that chunks will set dirty and refill again when files changes or entries cache can't find in avl.  Chunks set dirty and refill happened many times in my scenario, and it waste a lot of time. I'm thinking about how to modify the code is better?

**Comment by zhengfeihu51** [comment] 2022-10-26 07:00
> Readdir is difficult in the presence of changes. We've tested huge directory listings on RGW, and it's fast when there's no changes to the directory (a few minutes for a static bucket) but slows down a lot when the directory is changing.
> 
> Then, too, different FSALs have different readdir speeds, depending on what APIs they support for readdir. Which FSAL is this?

the FSAL is cephfs, we creat and write a lots of file(60million files). After write file, we do readdir operation. It has no changes of files when readdir.
I read the code of readdir by chunk, and make some tests, find that chunks will set dirty and refill again when files changes or entries cache can't find in avl. Chunks set dirty and refill happened many times in my scenario, and it waste a lot of time. I'm thinking about how to modify the code is better?

**Comment by dang** [comment] 2022-10-27 13:11
What is your Entries_HWMark set to in the MDCACHE block?  If you've left it at the default (100k), then it's way to small for a working set of 60m files.  Setting that to larger might help with this workload.

**Comment by zhengfeihu51** [comment] 2022-11-03 01:33
> What is your Entries_HWMark set to in the MDCACHE block? If you've left it at the default (100k), then it's way to small for a working set of 60m files. Setting that to larger might help with this workload.

Increse Entries_HWMark does work, but i found that readdir by chunk has defect: Readdir fills all the files to chunks in the directory under the current offset at one time, which may contain multiple chunks, but read only a part of the chunks. When the files are in the chunks but not in the global avl tree, they will release the chunks and refill the chunks, and this may happen repeatedly. Is there any way to avoid this problem?

I came up with two methods: 
1、 Add the chunk dirty detection mechanism. If the chunk is set dirty, go to the readdir uncached branch next readdir, and recover to the read chunk mechanism after a period of time(for example, 10 minutes).
2、 Add a chunk dirty detection mechanism and add a window value for filling chunks. For example, if the initial window value is 50, a readdir can fill up to 50 chunks at a time at most. If it is found that the chunk is set dirty, the window value will be halved. If the chunk is not dirty for a period of time, the window will gradually recover.

**Comment by ffilz** [comment] 2022-11-07 16:23
Patch submitted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/545764

**Comment by iamtiger51** [comment] 2022-11-12 01:07
> Patch submitted: https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/545764

Why is the entire directory being read in before the response is served?
Normally we read a single chunk (def. 128 entries) and then serve the response. With read ahead (used by FSAL_RGW) we read 1000 entries (so 8 chunks) not the whole directory.
This needs more understanding of the problem before we try and fix it.
Is there an associated github issue we can go back to discussion the problem and see configuration files and such?

------------------------------------------------------------------------------------------------------------------------
I mean mdcache_populate_dir_chunk function fills all files to chunks at one time under the current offset when FSAL is ceph or gluster(I am not sure the situation about FSAL_RGW), and only read a apart of chunk before the response is served  in an readdir.

**Comment by ffilz** [comment] 2023-01-24 19:18
Please see the comments in the patch, this issue definitely still needs some work. Now that V4.3 has been released, there is more opportunity to make progress on this.

**Comment by ffilz** [comment] 2023-01-24 20:10
Bump

**Comment by iamtiger51** [comment] 2023-02-13 15:59
Found the root cause of the problem, the code has been submitted, please review.


九天揽月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nfs-ganesha/nfs-ganesha"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月25日(星期三) 凌晨4:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nfs-ganesha/nfs-ganesha] readdir by chunk is slow when the number of files is large.  (Issue #868)





 
Bump

**Comment by ffilz** [comment] 2023-02-20 16:13
Which patch did you submit for this? Is my patch still relevant?

**Comment by ffilz** [comment] 2023-02-27 22:17
I have posted my patch set that includes the LRU rework:

https://github.com/nfs-ganesha/nfs-ganesha/compare/next...ffilz:nfs-ganesha:ceph-async

You should check it out and see if your issues are resolved, we will want any additional LRU changes to go on top of that patch set.

**Comment by ffilz** [comment] 2023-03-10 21:24
The LRU changes have been merged to V5-dev.4. Please try that.

**Comment by ffilz** [comment] 2023-04-21 23:04
V5.0 has been released. Closing.

**Closed as completed by ffilz** 2023-04-21 23:04 UTC
Labels: Analyzing, Try-on-supported-version
